/*
 * ImageToolbox is an image editor for android
 * Copyright (c) 2026 T8RIN (Malik Mukhametzyanov)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/LICENSE-2.0>.
 */

package com.t8rin.imagetoolbox.core.ksp.processor

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSValueParameter

internal class FastNoiseTextureMappingsProcessor : SymbolProcessorProvider {
    override fun create(
        environment: SymbolProcessorEnvironment
    ): SymbolProcessor = FastNoiseTextureMappingsProcessorImpl(environment)
}

private class FastNoiseTextureMappingsProcessorImpl(
    environment: SymbolProcessorEnvironment
) : SymbolProcessor {

    private val codeGenerator = environment.codeGenerator
    private val logger = environment.logger
    private var generated = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()

        val textureType = resolver.getSymbolsWithAnnotation(MAPPINGS_ANNOTATION)
            .filterIsInstance<KSClassDeclaration>()
            .singleOrNull() ?: return emptyList()

        val entries = textureType.declarations
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.classKind == ClassKind.ENUM_ENTRY }
            .mapNotNull { it.toTextureEntry(resolver) }
            .toList()
            .withoutConventionDuplicates()

        if (entries.isEmpty()) {
            logger.error("No fast-noise textures found for ${textureType.qualifiedName?.asString()}")
            return emptyList()
        }

        codeGenerator.createNewFile(
            dependencies = Dependencies(
                aggregating = false,
                requireNotNull(textureType.containingFile)
            ),
            packageName = GENERATED_PACKAGE,
            fileName = GENERATED_FILE
        ).bufferedWriter().use { writer ->
            writer.appendLine("// Generated by KSP — do not edit")
            writer.appendLine("package $GENERATED_PACKAGE")
            writer.appendLine()
            writer.appendLine("import android.graphics.Bitmap")
            writer.appendLine("import $FAST_NOISE_PACKAGE.*")
            writer.appendLine("import $TEXTURE_MODEL_PACKAGE.FastNoiseTextureParams")
            writer.appendLine("import $TEXTURE_MODEL_PACKAGE.TextureFilterType")
            writer.appendLine()
            writer.appendLine("internal fun createFastNoiseTexture(")
            writer.appendLine("    width: Int,")
            writer.appendLine("    height: Int,")
            writer.appendLine("    type: TextureFilterType,")
            writer.appendLine("    params: FastNoiseTextureParams")
            writer.appendLine("): Bitmap? {")
            writer.appendLine("    val values = params.values")
            writer.appendLine("    val colors = params.colors.map { it.colorInt }")
            writer.appendLine()
            writer.appendLine("    return when (type) {")

            entries.forEach { writer.appendMapping(it) }

            writer.appendLine("        else -> error(\"Unsupported fast-noise texture type: \$type\")")
            writer.appendLine("    }")
            writer.appendLine("}")
        }

        generated = true
        return emptyList()
    }

    private fun KSClassDeclaration.toTextureEntry(
        resolver: Resolver
    ): TextureEntry? {
        val enumName = simpleName.asString()
        val nameOverride = annotations.firstOrNull {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == NAME_ANNOTATION
        }?.arguments?.firstOrNull()?.value as? String
        val textureName = nameOverride ?: enumName

        val generatorClass = resolver.getClassDeclarationByName(
            resolver.getKSNameFromString("$FAST_NOISE_PACKAGE.${textureName}TextureGenerator")
        ) ?: return null
        val parametersClass = resolver.getClassDeclarationByName(
            resolver.getKSNameFromString("$FAST_NOISE_PACKAGE.${textureName}TextureParameters")
        ) ?: run {
            logger.error("No ${textureName}TextureParameters found for $enumName", this)
            return null
        }

        val parameters = parametersClass.primaryConstructor?.parameters.orEmpty()
        if (!parameters.haveSupportedShape(logger, parametersClass)) return null

        return TextureEntry(
            enumName = enumName,
            textureName = textureName,
            hasNameOverride = nameOverride != null,
            generatorName = generatorClass.simpleName.asString(),
            parametersName = parametersClass.simpleName.asString(),
            parameters = parameters
        )
    }

    private fun List<TextureEntry>.withoutConventionDuplicates(): List<TextureEntry> =
        groupBy { it.textureName }.values.mapNotNull { entries ->
            if (entries.size == 1) return@mapNotNull entries.single()

            val overrides = entries.filter { it.hasNameOverride }
            when (overrides.size) {
                1 -> overrides.single()
                else -> {
                    logger.error(
                        "Ambiguous fast-noise texture mapping for ${entries.first().textureName}: " +
                                entries.joinToString { it.enumName }
                    )
                    null
                }
            }
        }

    private fun List<KSValueParameter>.haveSupportedShape(
        logger: KSPLogger,
        declaration: KSClassDeclaration
    ): Boolean {
        val types = map { it.type.resolve().declaration.qualifiedName?.asString() }
        val valid = size >= 2 &&
                types[0] == "kotlin.Int" &&
                types[1] == "kotlin.Float" &&
                types.drop(2).all { it == "kotlin.Float" || it == "kotlin.Int" }

        if (!valid) {
            logger.error(
                "${declaration.simpleName.asString()} must contain seed: Int, scale: Float, " +
                        "then only Float values and Int colors",
                declaration
            )
        }
        return valid
    }

    private fun Appendable.appendMapping(entry: TextureEntry) {
        appendLine("        TextureFilterType.${entry.enumName} -> ${entry.generatorName}().generate(")
        appendLine("            width = width,")
        appendLine("            height = height,")
        appendLine("            parameters = ${entry.parametersName}(")

        var valueIndex = 0
        var colorIndex = 0
        entry.parameters.forEachIndexed { index, parameter ->
            val name = parameter.name?.asString()
                ?: error("Unnamed parameter in ${entry.parametersName}")
            val value = when (index) {
                0 -> "params.seed"
                1 -> "params.scale"
                else -> when (parameter.type.resolve().declaration.qualifiedName?.asString()) {
                    "kotlin.Float" -> "values[${valueIndex++}]"
                    "kotlin.Int" -> "colors[${colorIndex++}]"
                    else -> error("Unsupported parameter type in ${entry.parametersName}")
                }
            }
            val suffix = if (index == entry.parameters.lastIndex) "" else ","
            appendLine("                $name = $value$suffix")
        }

        appendLine("            )")
        appendLine("        )")
        appendLine()
    }

    private data class TextureEntry(
        val enumName: String,
        val textureName: String,
        val hasNameOverride: Boolean,
        val generatorName: String,
        val parametersName: String,
        val parameters: List<KSValueParameter>
    )

    companion object {
        private const val PACKAGE = "com.t8rin.imagetoolbox"
        private const val MAPPINGS_ANNOTATION =
            "$PACKAGE.core.ksp.annotations.FastNoiseTextureMappings"
        private const val NAME_ANNOTATION =
            "$PACKAGE.core.ksp.annotations.FastNoiseTextureName"
        private const val FAST_NOISE_PACKAGE = "com.t8rin.fast_noise.texture"
        private const val TEXTURE_MODEL_PACKAGE =
            "$PACKAGE.texture_generation.domain.model"
        private const val GENERATED_PACKAGE = "$PACKAGE.texture_generation.data"
        private const val GENERATED_FILE = "FastNoiseTextureMappings"
    }
}
