/*
 * ImageToolbox is an image editor for android
 * Copyright (c) 2026 T8RIN (Malik Mukhametzyanov)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/LICENSE-2.0>.
 */

@file:Suppress("unused")

package com.t8rin.imagetoolbox.core.ksp.processor

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType

internal class NavigationNodeProcessor : SymbolProcessorProvider {
    override fun create(
        environment: SymbolProcessorEnvironment
    ): SymbolProcessor = NavigationNodeProcessorImpl(environment)
}

private class NavigationNodeProcessorImpl(
    environment: SymbolProcessorEnvironment
) : SymbolProcessor {

    private val codegen = environment.codeGenerator
    private val logger = environment.logger
    private var generated = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()

        val nodeAnnotation = "$PACKAGE.core.ksp.annotations.NavigationNode"
        val contentAnnotation = "$PACKAGE.core.ksp.annotations.NavigationContent"

        val components = resolver.getSymbolsWithAnnotation(nodeAnnotation)
            .filterIsInstance<KSClassDeclaration>()
            .sortedBy { it.qualifiedName?.asString().orEmpty() }
            .toList()

        if (components.isEmpty()) return emptyList()

        val contents = resolver.getSymbolsWithAnnotation(contentAnnotation)
            .filterIsInstance<KSFunctionDeclaration>()
            .toList()

        val entries = components.mapNotNull { component ->
            component.toNavigationEntry(
                nodeAnnotation = nodeAnnotation,
                contents = contents,
                logger = logger
            )
        }

        if (entries.isEmpty()) return emptyList()

        val file = codegen.createNewFile(
            dependencies = Dependencies(
                aggregating = false,
                *entries.flatMap { it.files }.distinct().toTypedArray()
            ),
            packageName = entries.first().generatedPackage,
            fileName = "GeneratedNavigationNodes"
        )

        file.bufferedWriter().use { writer ->
            writer.apply {
                appendLine("// Generated by KSP — do not edit")
                appendLine("package ${entries.first().generatedPackage}")
                appendLine()
                appendLine("import androidx.compose.runtime.Composable")
                appendLine("import com.arkivanov.decompose.ComponentContext")
                appendLine("import com.t8rin.imagetoolbox.core.ui.utils.navigation.NavigationChild")
                appendLine("import com.t8rin.imagetoolbox.core.ui.utils.navigation.NavigationHost")
                appendLine("import com.t8rin.imagetoolbox.core.ui.utils.navigation.NavigationNodeFactory")
                appendLine("import com.t8rin.imagetoolbox.core.ui.utils.navigation.Screen")
                appendLine("import dagger.Binds")
                appendLine("import dagger.Module")
                appendLine("import dagger.hilt.InstallIn")
                appendLine("import dagger.hilt.components.SingletonComponent")
                appendLine("import dagger.multibindings.IntoSet")
                appendLine("import javax.inject.Inject")
                appendLine()

                entries.forEach { entry ->
                    appendEntry(entry)
                    appendLine()
                }

                appendLine("@Module")
                appendLine("@InstallIn(SingletonComponent::class)")
                appendLine("internal interface GeneratedNavigationNodesModule {")
                entries.forEach { entry ->
                    appendLine("    @Binds")
                    appendLine("    @IntoSet")
                    appendLine("    fun bind${entry.generatedClassName}(")
                    appendLine("        factory: ${entry.generatedClassName}")
                    appendLine("    ): NavigationNodeFactory")
                    appendLine()
                }
                appendLine("}")
            }
        }

        generated = true
        return emptyList()
    }

    private fun Appendable.appendEntry(entry: NavigationEntry) {
        appendLine("internal class ${entry.generatedClassName} @Inject constructor(")
        appendLine("    private val componentFactory: ${entry.componentType}.Factory")
        appendLine(") : NavigationNodeFactory {")
        appendLine("    override val screenClass = ${entry.screenType}::class")
        appendLine()
        appendLine("    override fun create(")
        appendLine("        config: Screen,")
        appendLine("        componentContext: ComponentContext,")
        appendLine("        host: NavigationHost")
        appendLine("    ): NavigationChild {")
        appendLine("        val typedConfig = config as ${entry.screenType}")
        appendLine("        val component = componentFactory(")
        entry.factoryParameters.forEachIndexed { index, parameter ->
            val suffix = if (index == entry.factoryParameters.lastIndex) "" else ","
            appendLine("            ${parameter.name} = ${entry.expressionFor(parameter)}$suffix")
        }
        appendLine("        )")
        appendLine()
        appendLine("        return object : NavigationChild {")
        appendLine("            @Composable")
        appendLine("            override fun Content() = ${entry.contentFunction}(component)")
        appendLine("        }")
        appendLine("    }")
        appendLine("}")
    }

    private fun KSClassDeclaration.toNavigationEntry(
        nodeAnnotation: String,
        contents: List<KSFunctionDeclaration>,
        logger: KSPLogger
    ): NavigationEntry? {
        val annotation = annotations.firstOrNull {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == nodeAnnotation
        } ?: return null

        val annotationArgs = annotation.arguments.associateBy { it.name?.asString() }
        val screenDeclaration = annotationArgs["screen"]?.value.toClassDeclaration()
        val screenType = screenDeclaration
            ?.qualifiedName
            ?.asString()
        val mode = annotationArgs["mode"]?.value?.toString() ?: "DEFAULT"

        if (screenType == null) {
            logger.error("NavigationNode requires screen", this)
            return null
        }

        val componentType = qualifiedName?.asString()
        if (componentType == null) {
            logger.error("NavigationNode component should be a top-level class", this)
            return null
        }

        val content = contents.firstOrNull { content ->
            content.parameters.firstOrNull()
                ?.type
                ?.resolve()
                ?.declaration
                ?.qualifiedName
                ?.asString() == componentType
        }

        if (content == null) {
            logger.error(
                "$componentType should have @NavigationContent function with it as the first parameter",
                this
            )
            return null
        }

        val factory = declarations
            .filterIsInstance<KSClassDeclaration>()
            .firstOrNull { it.simpleName.asString() == "Factory" }
        val invokeFunction = factory?.getAllFunctions()
            ?.firstOrNull { it.simpleName.asString() == "invoke" }

        if (invokeFunction == null) {
            logger.error("$componentType should declare Factory.invoke", this)
            return null
        }

        return NavigationEntry(
            generatedPackage = "${packageName.asString()}.generated",
            generatedClassName = "${simpleName.asString()}NavigationNodeFactory",
            screenType = screenType,
            componentType = componentType,
            contentFunction = content.qualifiedName?.asString().orEmpty(),
            mode = mode,
            screenProperties = screenDeclaration.getAllProperties()
                .map { it.simpleName.asString() }
                .toSet(),
            factoryParameters = invokeFunction.parameters.mapNotNull { parameter ->
                FactoryParameter(parameter.name?.asString() ?: return@mapNotNull null)
            },
            files = listOfNotNull(containingFile, content.containingFile)
        )
    }

    private fun NavigationEntry.expressionFor(parameter: FactoryParameter): String =
        when (parameter.name) {
            "componentContext" -> "componentContext"
            "onGoBack" -> "host::navigateBack"
            "onNavigate" -> "host::${navigateFunction()}"
            "onTryGetUpdate" -> "host::tryGetUpdate"
            "onGetClipList" -> "host::updateUris"
            "isUpdateAvailable" -> "host.isUpdateAvailable"
            "initialComparableUris" -> "typedConfig.uris?.takeIf { it.size == 2 }?.let { it[0] to it[1] }"
            "initialCategory" -> "typedConfig.categoryName"
            "initialTipId" -> "typedConfig.tipId"
            "initialSearchQuery" -> "typedConfig.searchQuery"
            "libraryName" -> "typedConfig.name"
            "libraryDescription" -> "typedConfig.htmlDescription"
            "libraryLink" -> "typedConfig.link"
            "targetSetting" -> "typedConfig.targetSetting"
            "uriToAnalyze" -> "typedConfig.uriToAnalyze"
            else -> "typedConfig.${configPropertyNameFor(parameter)}"
        }

    private fun NavigationEntry.navigateFunction(): String = when (mode) {
        "NEW" -> "navigateToNew"
        "REPLACE" -> "replaceTo"
        else -> "navigateTo"
    }

    private fun FactoryParameter.configPropertyName(): String = name
        .removePrefix("initial")
        .replaceFirstChar { it.lowercase() }

    private fun NavigationEntry.configPropertyNameFor(parameter: FactoryParameter): String {
        val propertyName = parameter.configPropertyName()
        if (propertyName in screenProperties) return propertyName

        return when (propertyName) {
            "uris" -> "uri"
            "uri" -> "uris"
            else -> propertyName
        }
    }

    companion object {
        private const val PACKAGE = "com.t8rin.imagetoolbox"
    }
}

private fun Any?.toClassDeclaration(): KSClassDeclaration? = when (this) {
    is KSType -> declaration as? KSClassDeclaration
    is KSClassDeclaration -> this
    else -> null
}

private data class NavigationEntry(
    val generatedPackage: String,
    val generatedClassName: String,
    val screenType: String,
    val componentType: String,
    val contentFunction: String,
    val mode: String,
    val screenProperties: Set<String>,
    val factoryParameters: List<FactoryParameter>,
    val files: List<KSFile>
)

private data class FactoryParameter(
    val name: String
)
