/// Every tool, with the English title used to find its card through the search field.
enum UITestTools {
  static let all: [(id: String, title: String)] = [
    ("base64", "Base64"),
    ("deleteExif", "Delete EXIF"),
    ("editExif", "Edit EXIF"),
    ("rotateFlip", "Rotate and flip"),
    ("loadFromURL", "Load image from URL"),
    ("colorPicker", "Color picker"),
    ("colorLibrary", "Color library"),
    ("perlinNoise", "Perlin noise"),
    ("asciiArt", "ASCII art"),
    ("imagePreview", "Image preview"),
    ("snowfall", "Snowfall"),
    ("libraries", "Libraries"),
    ("help", "Help"),
    ("appLogs", "App logs"),
    ("usageStatistics", "Usage statistics"),
    ("easterEgg", "Easter egg"),
    ("resizeConvert", "Resize and convert"),
    ("weightResize", "Resize to file size"),
    ("limitsResize", "Resize within limits"),
    ("crop", "Crop"),
    ("imageCutting", "Image cutting"),
    ("imageSplitting", "Image splitting"),
    ("imageStitch", "Image stitching"),
    ("imageStacking", "Image stacking"),
    ("compare", "Compare images"),
    ("watermarking", "Watermarks"),
    ("singleEdit", "Single edit and export profiles"),
    ("batchRename", "Batch rename"),
    ("duplicateFinder", "Duplicate finder"),
    ("checksumTools", "Checksums"),
    ("colorTools", "Color tools"),
    ("gifTools", "GIF tools"),
    ("apngTools", "APNG tools"),
    ("webpTools", "WebP tools"),
    ("documentScanner", "Document scanner"),
    ("scanQRCode", "Scan QR and barcodes"),
    ("wallpapersExport", "Wallpapers export"),
    ("audioCoverExtractor", "Audio cover extractor"),
    ("screenshotFraming", "Screenshot framing"),
    ("codePreview", "Code preview"),
    ("gradientMaker", "Gradients and mesh"),
    ("paletteToPDF", "Palette to PDF"),
    ("photomosaic", "Photomosaic"),
  ]
}
