/*
 * ImageToolbox is an image editor for android
 * Copyright (c) 2026 T8RIN (Malik Mukhametzyanov)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/LICENSE-2.0>.
 */

package com.t8rin.imagetoolbox.core.resources.icons

import androidx.compose.material.icons.Icons
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Icons.Rounded.Face5: ImageVector by lazy(LazyThreadSafetyMode.NONE) {
    ImageVector.Builder(
        name = "Rounded.Face5",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        path(fill = SolidColor(Color(0xFF000000))) {
            moveTo(480f, 240f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(560f, 240f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(400f, 240f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(680f, 280f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(360f, 280f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(280f, 280f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(440f, 280f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(520f, 280f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(600f, 280f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(480f, 320f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(560f, 320f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(640f, 320f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(400f, 320f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(320f, 320f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(360f, 360f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(280f, 360f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(440f, 360f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(520f, 360f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(600f, 360f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(680f, 360f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(200f, 360f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(240f, 320f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(320f, 240f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(360f, 200f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(440f, 200f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(520f, 200f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(600f, 200f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(640f, 240f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(720f, 320f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(760f, 360f)
            quadToRelative(-8f, 0f, -14f, -6f)
            reflectiveQuadToRelative(-6f, -14f)
            quadToRelative(0f, -8f, 6f, -14f)
            reflectiveQuadToRelative(14f, -6f)
            quadToRelative(8f, 0f, 14f, 6f)
            reflectiveQuadToRelative(6f, 14f)
            quadToRelative(0f, 8f, -6f, 14f)
            reflectiveQuadToRelative(-14f, 6f)
            close()
            moveTo(360f, 570f)
            quadToRelative(-21f, 0f, -35.5f, -14.5f)
            reflectiveQuadTo(310f, 520f)
            quadToRelative(0f, -21f, 14.5f, -35.5f)
            reflectiveQuadTo(360f, 470f)
            quadToRelative(21f, 0f, 35.5f, 14.5f)
            reflectiveQuadTo(410f, 520f)
            quadToRelative(0f, 21f, -14.5f, 35.5f)
            reflectiveQuadTo(360f, 570f)
            close()
            moveTo(600f, 570f)
            quadToRelative(-21f, 0f, -35.5f, -14.5f)
            reflectiveQuadTo(550f, 520f)
            quadToRelative(0f, -21f, 14.5f, -35.5f)
            reflectiveQuadTo(600f, 470f)
            quadToRelative(21f, 0f, 35.5f, 14.5f)
            reflectiveQuadTo(650f, 520f)
            quadToRelative(0f, 21f, -14.5f, 35.5f)
            reflectiveQuadTo(600f, 570f)
            close()
            moveTo(480f, 880f)
            quadToRelative(-82f, 0f, -155f, -31.5f)
            reflectiveQuadToRelative(-127.5f, -86f)
            quadTo(143f, 708f, 111.5f, 635f)
            reflectiveQuadTo(80f, 480f)
            quadToRelative(0f, -83f, 31.5f, -156f)
            reflectiveQuadToRelative(86f, -127f)
            quadTo(252f, 143f, 325f, 111.5f)
            reflectiveQuadTo(480f, 80f)
            quadToRelative(83f, 0f, 156f, 31.5f)
            reflectiveQuadTo(763f, 197f)
            quadToRelative(54f, 54f, 85.5f, 127f)
            reflectiveQuadTo(880f, 480f)
            quadToRelative(0f, 82f, -31.5f, 155f)
            reflectiveQuadTo(763f, 762.5f)
            quadToRelative(-54f, 54.5f, -127f, 86f)
            reflectiveQuadTo(480f, 880f)
            close()
            moveTo(480f, 800f)
            quadToRelative(134f, 0f, 227f, -93.5f)
            reflectiveQuadTo(800f, 480f)
            quadToRelative(0f, -134f, -93f, -227f)
            reflectiveQuadToRelative(-227f, -93f)
            quadToRelative(-133f, 0f, -226.5f, 93f)
            reflectiveQuadTo(160f, 480f)
            quadToRelative(0f, 133f, 93.5f, 226.5f)
            reflectiveQuadTo(480f, 800f)
            close()
        }
    }.build()
}
