/*
 * ImageToolbox is an image editor for android
 * Copyright (c) 2026 T8RIN (Malik Mukhametzyanov)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/LICENSE-2.0>.
 */

package com.t8rin.imagetoolbox.core.resources.icons

// Generated by Valkyrie from Font Awesome Free 7.3.1 (CC BY 4.0).

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.t8rin.imagetoolbox.core.resources.Icons

val Icons.Rounded.LinkedIn: ImageVector by lazy(LazyThreadSafetyMode.NONE) {
    ImageVector.Builder(
        name = "Rounded.LinkedIn",
        defaultWidth = 21.dp,
        defaultHeight = 24.dp,
        viewportWidth = 448f,
        viewportHeight = 512f
    ).apply {
        path(fill = SolidColor(Color(0xFF000000))) {
            moveTo(416f, 32f)
            lineTo(31.9f, 32f)
            curveTo(14.3f, 32f, 0f, 46.5f, 0f, 64.3f)
            lineTo(0f, 447.7f)
            curveTo(0f, 465.5f, 14.3f, 480f, 31.9f, 480f)
            lineTo(416f, 480f)
            curveToRelative(17.6f, 0f, 32f, -14.5f, 32f, -32.3f)
            lineToRelative(0f, -383.4f)
            curveTo(448f, 46.5f, 433.6f, 32f, 416f, 32f)
            close()
            moveTo(135.4f, 416f)
            lineToRelative(-66.4f, 0f)
            lineToRelative(0f, -213.8f)
            lineToRelative(66.5f, 0f)
            lineToRelative(0f, 213.8f)
            lineToRelative(-0.1f, 0f)
            close()
            moveTo(102.2f, 96f)
            arcToRelative(38.5f, 38.5f, 0f, isMoreThanHalf = true, isPositiveArc = true, 0f, 77f)
            arcToRelative(38.5f, 38.5f, 0f, isMoreThanHalf = true, isPositiveArc = true, 0f, -77f)
            close()
            moveTo(384.3f, 416f)
            lineToRelative(-66.4f, 0f)
            lineToRelative(0f, -104f)
            curveToRelative(0f, -24.8f, -0.5f, -56.7f, -34.5f, -56.7f)
            curveToRelative(-34.6f, 0f, -39.9f, 27f, -39.9f, 54.9f)
            lineToRelative(0f, 105.8f)
            lineToRelative(-66.4f, 0f)
            lineToRelative(0f, -213.8f)
            lineToRelative(63.7f, 0f)
            lineToRelative(0f, 29.2f)
            lineToRelative(0.9f, 0f)
            curveToRelative(8.9f, -16.8f, 30.6f, -34.5f, 62.9f, -34.5f)
            curveToRelative(67.2f, 0f, 79.7f, 44.3f, 79.7f, 101.9f)
            lineToRelative(0f, 117.2f)
            close()
        }
    }.build()
}
