/*
 * ImageToolbox is an image editor for android
 * Copyright (c) 2026 T8RIN (Malik Mukhametzyanov)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/LICENSE-2.0>.
 */

package com.t8rin.imagetoolbox.core.resources.icons

import androidx.compose.material.icons.Icons
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Icons.Rounded.QrCodeScanner: ImageVector by lazy(LazyThreadSafetyMode.NONE) {
    ImageVector.Builder(
        name = "Rounded.QrCodeScanner",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        path(fill = SolidColor(Color(0xFF000000))) {
            moveTo(120f, 280f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(80f, 240f)
            verticalLineToRelative(-120f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(120f, 80f)
            horizontalLineToRelative(120f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(280f, 120f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(240f, 160f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(80f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(120f, 280f)
            close()
            moveTo(120f, 880f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(80f, 840f)
            verticalLineToRelative(-120f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(120f, 680f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(160f, 720f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(80f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(280f, 840f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(240f, 880f)
            lineTo(120f, 880f)
            close()
            moveTo(720f, 880f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(680f, 840f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(720f, 800f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(-80f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(840f, 680f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(880f, 720f)
            verticalLineToRelative(120f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(840f, 880f)
            lineTo(720f, 880f)
            close()
            moveTo(840f, 280f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(800f, 240f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(-80f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(680f, 120f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(720f, 80f)
            horizontalLineToRelative(120f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(880f, 120f)
            verticalLineToRelative(120f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(840f, 280f)
            close()
            moveTo(700f, 760f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(700f, 640f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(640f, 700f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(580f, 760f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(520f, 700f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(640f, 580f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(580f, 640f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(520f, 580f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(560f, 440f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(520f, 400f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(560f, 200f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(760f, 240f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(720f, 440f)
            lineTo(560f, 440f)
            close()
            moveTo(240f, 760f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(200f, 720f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(240f, 520f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(440f, 560f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(400f, 760f)
            lineTo(240f, 760f)
            close()
            moveTo(240f, 440f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(200f, 400f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(240f, 200f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(440f, 240f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(400f, 440f)
            lineTo(240f, 440f)
            close()
            moveTo(260f, 700f)
            horizontalLineToRelative(120f)
            verticalLineToRelative(-120f)
            lineTo(260f, 580f)
            verticalLineToRelative(120f)
            close()
            moveTo(260f, 380f)
            horizontalLineToRelative(120f)
            verticalLineToRelative(-120f)
            lineTo(260f, 260f)
            verticalLineToRelative(120f)
            close()
            moveTo(580f, 380f)
            horizontalLineToRelative(120f)
            verticalLineToRelative(-120f)
            lineTo(580f, 260f)
            verticalLineToRelative(120f)
            close()
        }
    }.build()
}
