/*
 * ImageToolbox is an image editor for android
 * Copyright (c) 2026 T8RIN (Malik Mukhametzyanov)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/LICENSE-2.0>.
 */

package com.t8rin.imagetoolbox.core.resources.icons

import androidx.compose.material.icons.Icons
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Icons.Rounded.QrCode2: ImageVector by lazy(LazyThreadSafetyMode.NONE) {
    ImageVector.Builder(
        name = "Rounded.QrCode2",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        path(fill = SolidColor(Color.Black)) {
            moveTo(520f, 840f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(-80f)
            close()
            moveTo(440f, 760f)
            verticalLineToRelative(-200f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(200f)
            horizontalLineToRelative(-80f)
            close()
            moveTo(760f, 640f)
            verticalLineToRelative(-160f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(160f)
            horizontalLineToRelative(-80f)
            close()
            moveTo(680f, 480f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(-80f)
            close()
            moveTo(200f, 560f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(-80f)
            close()
            moveTo(120f, 480f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(-80f)
            close()
            moveTo(480f, 200f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(-80f)
            close()
            moveTo(180f, 300f)
            horizontalLineToRelative(120f)
            verticalLineToRelative(-120f)
            lineTo(180f, 180f)
            verticalLineToRelative(120f)
            close()
            moveTo(120f, 320f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(160f, 120f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(360f, 160f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(320f, 360f)
            lineTo(160f, 360f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(120f, 320f)
            close()
            moveTo(180f, 780f)
            horizontalLineToRelative(120f)
            verticalLineToRelative(-120f)
            lineTo(180f, 660f)
            verticalLineToRelative(120f)
            close()
            moveTo(120f, 800f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(160f, 600f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(360f, 640f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(320f, 840f)
            lineTo(160f, 840f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(120f, 800f)
            close()
            moveTo(660f, 300f)
            horizontalLineToRelative(120f)
            verticalLineToRelative(-120f)
            lineTo(660f, 180f)
            verticalLineToRelative(120f)
            close()
            moveTo(600f, 320f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(640f, 120f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(840f, 160f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(800f, 360f)
            lineTo(640f, 360f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(600f, 320f)
            close()
            moveTo(680f, 840f)
            verticalLineToRelative(-120f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(160f)
            verticalLineToRelative(120f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(80f)
            lineTo(680f, 840f)
            close()
            moveTo(520f, 560f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(160f)
            verticalLineToRelative(80f)
            lineTo(520f, 560f)
            close()
            moveTo(360f, 560f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(240f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(-80f)
            close()
            moveTo(400f, 360f)
            verticalLineToRelative(-160f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(80f)
            lineTo(400f, 360f)
            close()
            moveTo(210f, 270f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(210f, 750f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
            moveTo(690f, 270f)
            verticalLineToRelative(-60f)
            horizontalLineToRelative(60f)
            verticalLineToRelative(60f)
            horizontalLineToRelative(-60f)
            close()
        }
    }.build()
}
