package com.smarttoolfactory.colordetector.parser

import androidx.compose.ui.graphics.Color

data class ColorName(val color: Color, val name: String)

val colorNameArray by lazy {
    arrayOf(
        ColorName(Color(0xFF000000), "Black"),
        ColorName(Color(0xFF000080), "Navy Blue"),
        ColorName(Color(0xFF0000C8), "Dark Blue"),
        ColorName(Color(0xFF0000FF), "Blue"),
        ColorName(Color(0xFF000741), "Stratos"),
        ColorName(Color(0xFF001B1C), "Swamp"),
        ColorName(Color(0xFF002387), "Resolution Blue"),
        ColorName(Color(0xFF002900), "Deep Fir"),
        ColorName(Color(0xFF002E20), "Burnham"),
        ColorName(Color(0xFF002FA7), "Klein Blue"),
        ColorName(Color(0xFF003153), "Prussian Blue"),
        ColorName(Color(0xFF003366), "Midnight Blue"),
        ColorName(Color(0xFF003399), "Smalt"),
        ColorName(Color(0xFF003532), "Deep Teal"),
        ColorName(Color(0xFF003E40), "Cyprus"),
        ColorName(Color(0xFF004620), "Kaitoke Green"),
        ColorName(Color(0xFF0047AB), "Cobalt"),
        ColorName(Color(0xFF004816), "Crusoe"),
        ColorName(Color(0xFF004950), "Sherpa Blue"),
        ColorName(Color(0xFF0056A7), "Endeavour"),
        ColorName(Color(0xFF00581A), "Camarone"),
        ColorName(Color(0xFF0066CC), "Science Blue"),
        ColorName(Color(0xFF0066FF), "Blue Ribbon"),
        ColorName(Color(0xFF00755E), "Tropical Rain Forest"),
        ColorName(Color(0xFF0076A3), "Allports"),
        ColorName(Color(0xFF007BA7), "Deep Cerulean"),
        ColorName(Color(0xFF007EC7), "Lochmara"),
        ColorName(Color(0xFF007FFF), "Azure Radiance"),
        ColorName(Color(0xFF008080), "Teal"),
        ColorName(Color(0xFF0095B6), "Bondi Blue"),
        ColorName(Color(0xFF009DC4), "Pacific Blue"),
        ColorName(Color(0xFF00A693), "Persian Green"),
        ColorName(Color(0xFF00A86B), "Jade"),
        ColorName(Color(0xFF00CC99), "Caribbean Green"),
        ColorName(Color(0xFF00CCCC), "Robin's Egg Blue"),
        ColorName(Color(0xFF00FF00), "Green"),
        ColorName(Color(0xFF00FF7F), "Spring Green"),
        ColorName(Color(0xFF00FFFF), "Cyan Aqua"),
        ColorName(Color(0xFF010D1A), "Blue Charcoal"),
        ColorName(Color(0xFF011635), "Midnight"),
        ColorName(Color(0xFF011D13), "Holly"),
        ColorName(Color(0xFF012731), "Daintree"),
        ColorName(Color(0xFF01361C), "Cardin Green"),
        ColorName(Color(0xFF01371A), "County Green"),
        ColorName(Color(0xFF013E62), "Astronaut Blue"),
        ColorName(Color(0xFF013F6A), "Regal Blue"),
        ColorName(Color(0xFF014B43), "Aqua Deep"),
        ColorName(Color(0xFF015E85), "Orient"),
        ColorName(Color(0xFF016162), "Blue Stone"),
        ColorName(Color(0xFF016D39), "Fun Green"),
        ColorName(Color(0xFF01796F), "Pine Green"),
        ColorName(Color(0xFF017987), "Blue Lagoon"),
        ColorName(Color(0xFF01826B), "Deep Sea"),
        ColorName(Color(0xFF01A368), "Green Haze"),
        ColorName(Color(0xFF022D15), "English Holly"),
        ColorName(Color(0xFF02402C), "Sherwood Green"),
        ColorName(Color(0xFF02478E), "Congress Blue"),
        ColorName(Color(0xFF024E46), "Evening Sea"),
        ColorName(Color(0xFF026395), "Bahama Blue"),
        ColorName(Color(0xFF02866F), "Observatory"),
        ColorName(Color(0xFF02A4D3), "Cerulean"),
        ColorName(Color(0xFF03163C), "Tangaroa"),
        ColorName(Color(0xFF032B52), "Green Vogue"),
        ColorName(Color(0xFF036A6E), "Mosque"),
        ColorName(Color(0xFF041004), "Midnight Moss"),
        ColorName(Color(0xFF041322), "Black Pearl"),
        ColorName(Color(0xFF042E4C), "Blue Whale"),
        ColorName(Color(0xFF044022), "Zuccini"),
        ColorName(Color(0xFF044259), "Teal Blue"),
        ColorName(Color(0xFF051040), "Deep Cove"),
        ColorName(Color(0xFF051657), "Gulf Blue"),
        ColorName(Color(0xFF055989), "Venice Blue"),
        ColorName(Color(0xFF056F57), "Watercourse"),
        ColorName(Color(0xFF062A78), "Catalina Blue"),
        ColorName(Color(0xFF063537), "Tiber"),
        ColorName(Color(0xFF069B81), "Gossamer"),
        ColorName(Color(0xFF06A189), "Niagara"),
        ColorName(Color(0xFF073A50), "Tarawera"),
        ColorName(Color(0xFF080110), "Jaguar"),
        ColorName(Color(0xFF081910), "Black Bean"),
        ColorName(Color(0xFF082567), "Deep Sapphire"),
        ColorName(Color(0xFF088370), "Elf Green"),
        ColorName(Color(0xFF08E8DE), "Bright Turquoise"),
        ColorName(Color(0xFF092256), "Downriver"),
        ColorName(Color(0xFF09230F), "Palm Green"),
        ColorName(Color(0xFF09255D), "Madison"),
        ColorName(Color(0xFF093624), "Bottle Green"),
        ColorName(Color(0xFF095859), "Deep Sea Green"),
        ColorName(Color(0xFF097F4B), "Salem"),
        ColorName(Color(0xFF0A001C), "Black Russian"),
        ColorName(Color(0xFF0A480D), "Dark Fern"),
        ColorName(Color(0xFF0A6906), "Japanese Laurel"),
        ColorName(Color(0xFF0A6F75), "Atoll"),
        ColorName(Color(0xFF0B0B0B), "Cod Gray"),
        ColorName(Color(0xFF0B0F08), "Marshland"),
        ColorName(Color(0xFF0B1107), "Gordons Green"),
        ColorName(Color(0xFF0B1304), "Black Forest"),
        ColorName(Color(0xFF0B6207), "San Felix"),
        ColorName(Color(0xFF0BDA51), "Malachite"),
        ColorName(Color(0xFF0C0B1D), "Ebony"),
        ColorName(Color(0xFF0C0D0F), "Woodsmoke"),
        ColorName(Color(0xFF0C1911), "Racing Green"),
        ColorName(Color(0xFF0C7A79), "Surfie Green"),
        ColorName(Color(0xFF0C8990), "Blue Chill"),
        ColorName(Color(0xFF0D0332), "Black Rock"),
        ColorName(Color(0xFF0D1117), "Bunker"),
        ColorName(Color(0xFF0D1C19), "Aztec"),
        ColorName(Color(0xFF0D2E1C), "Bush"),
        ColorName(Color(0xFF0E0E18), "Cinder"),
        ColorName(Color(0xFF0E2A30), "Firefly"),
        ColorName(Color(0xFF0F2D9E), "Torea Bay"),
        ColorName(Color(0xFF10121D), "Vulcan"),
        ColorName(Color(0xFF101405), "Green Waterloo"),
        ColorName(Color(0xFF105852), "Eden"),
        ColorName(Color(0xFF110C6C), "Arapawa"),
        ColorName(Color(0xFF120A8F), "Ultramarine"),
        ColorName(Color(0xFF123447), "Elephant"),
        ColorName(Color(0xFF126B40), "Jewel"),
        ColorName(Color(0xFF130000), "Diesel"),
        ColorName(Color(0xFF130A06), "Asphalt"),
        ColorName(Color(0xFF13264D), "Blue Zodiac"),
        ColorName(Color(0xFF134F19), "Parsley"),
        ColorName(Color(0xFF140600), "Nero"),
        ColorName(Color(0xFF1450AA), "Tory Blue"),
        ColorName(Color(0xFF151F4C), "Bunting"),
        ColorName(Color(0xFF1560BD), "Denim"),
        ColorName(Color(0xFF15736B), "Genoa"),
        ColorName(Color(0xFF161928), "Mirage"),
        ColorName(Color(0xFF161D10), "Hunter Green"),
        ColorName(Color(0xFF162A40), "Big Stone"),
        ColorName(Color(0xFF163222), "Celtic"),
        ColorName(Color(0xFF16322C), "Timber Green"),
        ColorName(Color(0xFF163531), "Gable Green"),
        ColorName(Color(0xFF171F04), "Pine Tree"),
        ColorName(Color(0xFF175579), "Chathams Blue"),
        ColorName(Color(0xFF182D09), "Deep Forest Green"),
        ColorName(Color(0xFF18587A), "Blumine"),
        ColorName(Color(0xFF19330E), "Palm Leaf"),
        ColorName(Color(0xFF193751), "Nile Blue"),
        ColorName(Color(0xFF1959A8), "Fun Blue"),
        ColorName(Color(0xFF1A1A68), "Lucky Point"),
        ColorName(Color(0xFF1AB385), "Mountain Meadow"),
        ColorName(Color(0xFF1B0245), "Tolopea"),
        ColorName(Color(0xFF1B1035), "Haiti"),
        ColorName(Color(0xFF1B127B), "Deep Koamaru"),
        ColorName(Color(0xFF1B1404), "Acadia"),
        ColorName(Color(0xFF1B2F11), "Seaweed"),
        ColorName(Color(0xFF1B3162), "Biscay"),
        ColorName(Color(0xFF1B659D), "Matisse"),
        ColorName(Color(0xFF1C1208), "Crowshead"),
        ColorName(Color(0xFF1C1E13), "Rangoon Green"),
        ColorName(Color(0xFF1C39BB), "Persian Blue"),
        ColorName(Color(0xFF1C402E), "Everglade"),
        ColorName(Color(0xFF1C7C7D), "Elm"),
        ColorName(Color(0xFF1D6142), "Green Pea"),
        ColorName(Color(0xFF1E0F04), "Creole"),
        ColorName(Color(0xFF1E1609), "Karaka"),
        ColorName(Color(0xFF1E1708), "El Paso"),
        ColorName(Color(0xFF1E385B), "Cello"),
        ColorName(Color(0xFF1E433C), "Te Papa Green"),
        ColorName(Color(0xFF1E90FF), "Dodger Blue"),
        ColorName(Color(0xFF1E9AB0), "Eastern Blue"),
        ColorName(Color(0xFF1F120F), "Night Rider"),
        ColorName(Color(0xFF1FC2C2), "Java"),
        ColorName(Color(0xFF20208D), "Jacksons Purple"),
        ColorName(Color(0xFF202E54), "Cloud Burst"),
        ColorName(Color(0xFF204852), "Blue Dianne"),
        ColorName(Color(0xFF211A0E), "Eternity"),
        ColorName(Color(0xFF220878), "Deep Blue"),
        ColorName(Color(0xFF228B22), "Forest Green"),
        ColorName(Color(0xFF233418), "Mallard"),
        ColorName(Color(0xFF240A40), "Violet"),
        ColorName(Color(0xFF240C02), "Kilimanjaro"),
        ColorName(Color(0xFF242A1D), "Log Cabin"),
        ColorName(Color(0xFF242E16), "Black Olive"),
        ColorName(Color(0xFF24500F), "Green House"),
        ColorName(Color(0xFF251607), "Graphite"),
        ColorName(Color(0xFF251706), "Cannon Black"),
        ColorName(Color(0xFF251F4F), "Port Gore"),
        ColorName(Color(0xFF25272C), "Shark"),
        ColorName(Color(0xFF25311C), "Green Kelp"),
        ColorName(Color(0xFF2596D1), "Curious Blue"),
        ColorName(Color(0xFF260368), "Paua"),
        ColorName(Color(0xFF26056A), "Paris M"),
        ColorName(Color(0xFF261105), "Wood Bark"),
        ColorName(Color(0xFF261414), "Gondola"),
        ColorName(Color(0xFF262335), "Steel Gray"),
        ColorName(Color(0xFF26283B), "Ebony Clay"),
        ColorName(Color(0xFF273A81), "Bay of Many"),
        ColorName(Color(0xFF27504B), "Plantation"),
        ColorName(Color(0xFF278A5B), "Eucalyptus"),
        ColorName(Color(0xFF281E15), "Oil"),
        ColorName(Color(0xFF283A77), "Astronaut"),
        ColorName(Color(0xFF286ACD), "Mariner"),
        ColorName(Color(0xFF290C5E), "Violent Violet"),
        ColorName(Color(0xFF292130), "Bastille"),
        ColorName(Color(0xFF292319), "Zeus"),
        ColorName(Color(0xFF292937), "Charade"),
        ColorName(Color(0xFF297B9A), "Jelly Bean"),
        ColorName(Color(0xFF29AB87), "Jungle Green"),
        ColorName(Color(0xFF2A0359), "Cherry Pie"),
        ColorName(Color(0xFF2A140E), "Coffee Bean"),
        ColorName(Color(0xFF2A2630), "Baltic Sea"),
        ColorName(Color(0xFF2A380B), "Turtle Green"),
        ColorName(Color(0xFF2A52BE), "Cerulean Blue"),
        ColorName(Color(0xFF2B0202), "Sepia Black"),
        ColorName(Color(0xFF2B194F), "Valhalla"),
        ColorName(Color(0xFF2B3228), "Heavy Metal"),
        ColorName(Color(0xFF2C0E8C), "Blue Gem"),
        ColorName(Color(0xFF2C1632), "Revolver"),
        ColorName(Color(0xFF2C2133), "Bleached Cedar"),
        ColorName(Color(0xFF2C8C84), "Lochinvar"),
        ColorName(Color(0xFF2D2510), "Mikado"),
        ColorName(Color(0xFF2D383A), "Outer Space"),
        ColorName(Color(0xFF2D569B), "St Tropez"),
        ColorName(Color(0xFF2E0329), "Jacaranda"),
        ColorName(Color(0xFF2E1905), "Jacko Bean"),
        ColorName(Color(0xFF2E3222), "Rangitoto"),
        ColorName(Color(0xFF2E3F62), "Rhino"),
        ColorName(Color(0xFF2E8B57), "Sea Green"),
        ColorName(Color(0xFF2EBFD4), "Scooter"),
        ColorName(Color(0xFF2F270E), "Onion"),
        ColorName(Color(0xFF2F3CB3), "Governor Bay"),
        ColorName(Color(0xFF2F519E), "Sapphire"),
        ColorName(Color(0xFF2F5A57), "Spectra"),
        ColorName(Color(0xFF2F6168), "Casal"),
        ColorName(Color(0xFF300529), "Melanzane"),
        ColorName(Color(0xFF301F1E), "Cocoa Brown"),
        ColorName(Color(0xFF302A0F), "Woodrush"),
        ColorName(Color(0xFF304B6A), "San Juan"),
        ColorName(Color(0xFF30D5C8), "Turquoise"),
        ColorName(Color(0xFF311C17), "Eclipse"),
        ColorName(Color(0xFF314459), "Pickled Bluewood"),
        ColorName(Color(0xFF315BA1), "Azure"),
        ColorName(Color(0xFF31728D), "Calypso"),
        ColorName(Color(0xFF317D82), "Paradiso"),
        ColorName(Color(0xFF32127A), "Persian Indigo"),
        ColorName(Color(0xFF32293A), "Blackcurrant"),
        ColorName(Color(0xFF323232), "Mine Shaft"),
        ColorName(Color(0xFF325D52), "Stromboli"),
        ColorName(Color(0xFF327C14), "Bilbao"),
        ColorName(Color(0xFF327DA0), "Astral"),
        ColorName(Color(0xFF33036B), "Christalle"),
        ColorName(Color(0xFF33292F), "Thunder"),
        ColorName(Color(0xFF33CC99), "Shamrock"),
        ColorName(Color(0xFF341515), "Tamarind"),
        ColorName(Color(0xFF350036), "Mardi Gras"),
        ColorName(Color(0xFF350E42), "Valentino"),
        ColorName(Color(0xFF350E57), "Jagger"),
        ColorName(Color(0xFF353542), "Tuna"),
        ColorName(Color(0xFF354E8C), "Chambray"),
        ColorName(Color(0xFF363050), "Martinique"),
        ColorName(Color(0xFF363534), "Tuatara"),
        ColorName(Color(0xFF363C0D), "Waiouru"),
        ColorName(Color(0xFF36747D), "Ming"),
        ColorName(Color(0xFF368716), "La Palma"),
        ColorName(Color(0xFF370202), "Chocolate"),
        ColorName(Color(0xFF371D09), "Clinker"),
        ColorName(Color(0xFF37290E), "Brown Tumbleweed"),
        ColorName(Color(0xFF373021), "Birch"),
        ColorName(Color(0xFF377475), "Oracle"),
        ColorName(Color(0xFF380474), "Blue Diamond"),
        ColorName(Color(0xFF381A51), "Grape"),
        ColorName(Color(0xFF383533), "Dune"),
        ColorName(Color(0xFF384555), "Oxford Blue"),
        ColorName(Color(0xFF384910), "Clover"),
        ColorName(Color(0xFF394851), "Limed Spruce"),
        ColorName(Color(0xFF396413), "Dell"),
        ColorName(Color(0xFF3A0020), "Toledo"),
        ColorName(Color(0xFF3A2010), "Sambuca"),
        ColorName(Color(0xFF3A2A6A), "Jacarta"),
        ColorName(Color(0xFF3A686C), "William"),
        ColorName(Color(0xFF3A6A47), "Killarney"),
        ColorName(Color(0xFF3AB09E), "Keppel"),
        ColorName(Color(0xFF3B000B), "Temptress"),
        ColorName(Color(0xFF3B0910), "Aubergine"),
        ColorName(Color(0xFF3B1F1F), "Jon"),
        ColorName(Color(0xFF3B2820), "Treehouse"),
        ColorName(Color(0xFF3B7A57), "Amazon"),
        ColorName(Color(0xFF3B91B4), "Boston Blue"),
        ColorName(Color(0xFF3C0878), "Windsor"),
        ColorName(Color(0xFF3C1206), "Rebel"),
        ColorName(Color(0xFF3C1F76), "Meteorite"),
        ColorName(Color(0xFF3C2005), "Dark Ebony"),
        ColorName(Color(0xFF3C3910), "Camouflage"),
        ColorName(Color(0xFF3C4151), "Bright Gray"),
        ColorName(Color(0xFF3C4443), "Cape Cod"),
        ColorName(Color(0xFF3C493A), "Lunar Green"),
        ColorName(Color(0xFF3D0C02), "Bean  "),
        ColorName(Color(0xFF3D2B1F), "Bistre"),
        ColorName(Color(0xFF3D7D52), "Goblin"),
        ColorName(Color(0xFF3E0480), "Kingfisher Daisy"),
        ColorName(Color(0xFF3E1C14), "Cedar"),
        ColorName(Color(0xFF3E2B23), "English Walnut"),
        ColorName(Color(0xFF3E2C1C), "Black Marlin"),
        ColorName(Color(0xFF3E3A44), "Ship Gray"),
        ColorName(Color(0xFF3EABBF), "Pelorous"),
        ColorName(Color(0xFF3F2109), "Bronze"),
        ColorName(Color(0xFF3F2500), "Cola"),
        ColorName(Color(0xFF3F3002), "Madras"),
        ColorName(Color(0xFF3F307F), "Minsk"),
        ColorName(Color(0xFF3F4C3A), "Cabbage Pont"),
        ColorName(Color(0xFF3F583B), "Tom Thumb"),
        ColorName(Color(0xFF3F5D53), "Mineral Green"),
        ColorName(Color(0xFF3FC1AA), "Puerto Rico"),
        ColorName(Color(0xFF3FFF00), "Harlequin"),
        ColorName(Color(0xFF401801), "Brown Pod"),
        ColorName(Color(0xFF40291D), "Cork"),
        ColorName(Color(0xFF403B38), "Masala"),
        ColorName(Color(0xFF403D19), "Thatch Green"),
        ColorName(Color(0xFF405169), "Fjord"),
        ColorName(Color(0xFF40826D), "Viridian"),
        ColorName(Color(0xFF40A860), "Chateau Green"),
        ColorName(Color(0xFF410056), "Ripe Plum"),
        ColorName(Color(0xFF411E10), "Paco"),
        ColorName(Color(0xFF412010), "Deep Oak"),
        ColorName(Color(0xFF413C37), "Merlin"),
        ColorName(Color(0xFF414257), "Gun Powder"),
        ColorName(Color(0xFF414C7D), "East Bay"),
        ColorName(Color(0xFF4169E1), "Royal Blue"),
        ColorName(Color(0xFF41AA78), "Ocean Green"),
        ColorName(Color(0xFF420303), "Burnt Maroon"),
        ColorName(Color(0xFF423921), "Lisbon Brown"),
        ColorName(Color(0xFF427977), "Faded Jade"),
        ColorName(Color(0xFF431560), "Scarlet Gum"),
        ColorName(Color(0xFF433120), "Iroko"),
        ColorName(Color(0xFF433E37), "Armadillo"),
        ColorName(Color(0xFF434C59), "River Bed"),
        ColorName(Color(0xFF436A0D), "Green Leaf"),
        ColorName(Color(0xFF44012D), "Barossa"),
        ColorName(Color(0xFF441D00), "Morocco Brown"),
        ColorName(Color(0xFF444954), "Mako"),
        ColorName(Color(0xFF454936), "Kelp"),
        ColorName(Color(0xFF456CAC), "San Marino"),
        ColorName(Color(0xFF45B1E8), "Picton Blue"),
        ColorName(Color(0xFF460B41), "Loulou"),
        ColorName(Color(0xFF462425), "Crater Brown"),
        ColorName(Color(0xFF465945), "Gray Asparagus"),
        ColorName(Color(0xFF4682B4), "Steel Blue"),
        ColorName(Color(0xFF480404), "Rustic Red"),
        ColorName(Color(0xFF480607), "Bulgarian Rose"),
        ColorName(Color(0xFF480656), "Clairvoyant"),
        ColorName(Color(0xFF481C1C), "Cocoa Bean"),
        ColorName(Color(0xFF483131), "Woody Brown"),
        ColorName(Color(0xFF483C32), "Taupe"),
        ColorName(Color(0xFF49170C), "Van Cleef"),
        ColorName(Color(0xFF492615), "Brown Derby"),
        ColorName(Color(0xFF49371B), "Metallic Bronze"),
        ColorName(Color(0xFF495400), "Verdun Green"),
        ColorName(Color(0xFF496679), "Blue Bayoux"),
        ColorName(Color(0xFF497183), "Bismark"),
        ColorName(Color(0xFF4A2A04), "Bracken"),
        ColorName(Color(0xFF4A3004), "Deep Bronze"),
        ColorName(Color(0xFF4A3C30), "Mondo"),
        ColorName(Color(0xFF4A4244), "Tundora"),
        ColorName(Color(0xFF4A444B), "Gravel"),
        ColorName(Color(0xFF4A4E5A), "Trout"),
        ColorName(Color(0xFF4B0082), "Pigment Indigo"),
        ColorName(Color(0xFF4B5D52), "Nandor"),
        ColorName(Color(0xFF4C3024), "Saddle"),
        ColorName(Color(0xFF4C4F56), "Abbey"),
        ColorName(Color(0xFF4D0135), "Blackberry"),
        ColorName(Color(0xFF4D0A18), "Cab Sav"),
        ColorName(Color(0xFF4D1E01), "Indian Tan"),
        ColorName(Color(0xFF4D282D), "Cowboy"),
        ColorName(Color(0xFF4D282E), "Livid Brown"),
        ColorName(Color(0xFF4D3833), "Rock"),
        ColorName(Color(0xFF4D3D14), "Punga"),
        ColorName(Color(0xFF4D400F), "Bronzetone"),
        ColorName(Color(0xFF4D5328), "Woodland"),
        ColorName(Color(0xFF4E0606), "Mahogany"),
        ColorName(Color(0xFF4E2A5A), "Bossanova"),
        ColorName(Color(0xFF4E3B41), "Matterhorn"),
        ColorName(Color(0xFF4E420C), "Bronze Olive"),
        ColorName(Color(0xFF4E4562), "Mulled Wine"),
        ColorName(Color(0xFF4E6649), "Axolotl"),
        ColorName(Color(0xFF4E7F9E), "Wedgewood"),
        ColorName(Color(0xFF4EABD1), "Shakespeare"),
        ColorName(Color(0xFF4F1C70), "Honey Flower"),
        ColorName(Color(0xFF4F2398), "Daisy Bush"),
        ColorName(Color(0xFF4F69C6), "Indigo"),
        ColorName(Color(0xFF4F7942), "Fern Green"),
        ColorName(Color(0xFF4F9D5D), "Fruit Salad"),
        ColorName(Color(0xFF4FA83D), "Apple"),
        ColorName(Color(0xFF504351), "Mortar"),
        ColorName(Color(0xFF507096), "Kashmir Blue"),
        ColorName(Color(0xFF507672), "Cutty Sark"),
        ColorName(Color(0xFF50C878), "Emerald"),
        ColorName(Color(0xFF514649), "Emperor"),
        ColorName(Color(0xFF516E3D), "Chalet Green"),
        ColorName(Color(0xFF517C66), "Como"),
        ColorName(Color(0xFF51808F), "Smalt Blue"),
        ColorName(Color(0xFF52001F), "Castro"),
        ColorName(Color(0xFF520C17), "Maroon Oak"),
        ColorName(Color(0xFF523C94), "Gigas"),
        ColorName(Color(0xFF533455), "Voodoo"),
        ColorName(Color(0xFF534491), "Victoria"),
        ColorName(Color(0xFF53824B), "Hippie Green"),
        ColorName(Color(0xFF541012), "Heath"),
        ColorName(Color(0xFF544333), "Judge Gray"),
        ColorName(Color(0xFF54534D), "Fuscous Gray"),
        ColorName(Color(0xFF549019), "Vida Loca"),
        ColorName(Color(0xFF55280C), "Cioccolato"),
        ColorName(Color(0xFF555B10), "Saratoga"),
        ColorName(Color(0xFF556D56), "Finlandia"),
        ColorName(Color(0xFF5590D9), "Havelock Blue"),
        ColorName(Color(0xFF56B4BE), "Fountain Blue"),
        ColorName(Color(0xFF578363), "Spring Leaves"),
        ColorName(Color(0xFF583401), "Saddle Brown"),
        ColorName(Color(0xFF585562), "Scarpa Flow"),
        ColorName(Color(0xFF587156), "Cactus"),
        ColorName(Color(0xFF589AAF), "Hippie Blue"),
        ColorName(Color(0xFF591D35), "Wine Berry"),
        ColorName(Color(0xFF592804), "Brown Bramble"),
        ColorName(Color(0xFF593737), "Congo Brown"),
        ColorName(Color(0xFF594433), "Millbrook"),
        ColorName(Color(0xFF5A6E9C), "Waikawa Gray"),
        ColorName(Color(0xFF5A87A0), "Horizon"),
        ColorName(Color(0xFF5B3013), "Jambalaya"),
        ColorName(Color(0xFF5C0120), "Bordeaux"),
        ColorName(Color(0xFF5C0536), "Mulberry Wood"),
        ColorName(Color(0xFF5C2E01), "Carnaby Tan"),
        ColorName(Color(0xFF5C5D75), "Comet"),
        ColorName(Color(0xFF5D1E0F), "Redwood"),
        ColorName(Color(0xFF5D4C51), "Don Juan"),
        ColorName(Color(0xFF5D5C58), "Chicago"),
        ColorName(Color(0xFF5D5E37), "Verdigris"),
        ColorName(Color(0xFF5D7747), "Dingley"),
        ColorName(Color(0xFF5DA19F), "Breaker Bay"),
        ColorName(Color(0xFF5E483E), "Kabul"),
        ColorName(Color(0xFF5E5D3B), "Hemlock"),
        ColorName(Color(0xFF5F3D26), "Irish Coffee"),
        ColorName(Color(0xFF5F5F6E), "Mid Gray"),
        ColorName(Color(0xFF5F6672), "Shuttle Gray"),
        ColorName(Color(0xFF5FA777), "Aqua Forest"),
        ColorName(Color(0xFF5FB3AC), "Tradewind"),
        ColorName(Color(0xFF604913), "Horses Neck"),
        ColorName(Color(0xFF605B73), "Smoky"),
        ColorName(Color(0xFF606E68), "Corduroy"),
        ColorName(Color(0xFF6093D1), "Danube"),
        ColorName(Color(0xFF612718), "Espresso"),
        ColorName(Color(0xFF614051), "Eggplant"),
        ColorName(Color(0xFF615D30), "Costa Del Sol"),
        ColorName(Color(0xFF61845F), "Glade Green"),
        ColorName(Color(0xFF622F30), "Buccaneer"),
        ColorName(Color(0xFF623F2D), "Quincy"),
        ColorName(Color(0xFF624E9A), "Butterfly Bush"),
        ColorName(Color(0xFF625119), "West Coast"),
        ColorName(Color(0xFF626649), "Finch"),
        ColorName(Color(0xFF639A8F), "Patina"),
        ColorName(Color(0xFF63B76C), "Fern"),
        ColorName(Color(0xFF6456B7), "Blue Violet"),
        ColorName(Color(0xFF646077), "Dolphin"),
        ColorName(Color(0xFF646463), "Storm Dust"),
        ColorName(Color(0xFF646A54), "Siam"),
        ColorName(Color(0xFF646E75), "Nevada"),
        ColorName(Color(0xFF6495ED), "Cornflower Blue"),
        ColorName(Color(0xFF64CCDB), "Viking"),
        ColorName(Color(0xFF65000B), "Rosewood"),
        ColorName(Color(0xFF651A14), "Cherrywood"),
        ColorName(Color(0xFF652DC1), "Purple Heart"),
        ColorName(Color(0xFF657220), "Fern Frond"),
        ColorName(Color(0xFF65745D), "Willow Grove"),
        ColorName(Color(0xFF65869F), "Hoki"),
        ColorName(Color(0xFF660045), "Pompadour"),
        ColorName(Color(0xFF660099), "Purple"),
        ColorName(Color(0xFF66023C), "Tyrian Purple"),
        ColorName(Color(0xFF661010), "Dark Tan"),
        ColorName(Color(0xFF66B58F), "Silver Tree"),
        ColorName(Color(0xFF66FF00), "Bright Green"),
        ColorName(Color(0xFF66FF66), "Screamin Green"),
        ColorName(Color(0xFF67032D), "Black Rose"),
        ColorName(Color(0xFF675FA6), "Scampi"),
        ColorName(Color(0xFF676662), "Ironside Gray"),
        ColorName(Color(0xFF678975), "Viridian Green"),
        ColorName(Color(0xFF67A712), "Christi"),
        ColorName(Color(0xFF683600), "Nutmeg Wood Finish"),
        ColorName(Color(0xFF685558), "Zambezi"),
        ColorName(Color(0xFF685E6E), "Salt Box"),
        ColorName(Color(0xFF692545), "Tawny Port"),
        ColorName(Color(0xFF692D54), "Finn"),
        ColorName(Color(0xFF695F62), "Scorpion"),
        ColorName(Color(0xFF697E9A), "Lynch"),
        ColorName(Color(0xFF6A442E), "Spice"),
        ColorName(Color(0xFF6A5D1B), "Himalaya"),
        ColorName(Color(0xFF6A6051), "Soya Bean"),
        ColorName(Color(0xFF6B2A14), "Hairy Heath"),
        ColorName(Color(0xFF6B3FA0), "Royal Purple"),
        ColorName(Color(0xFF6B4E31), "Shingle Fawn"),
        ColorName(Color(0xFF6B5755), "Dorado"),
        ColorName(Color(0xFF6B8BA2), "Bermuda Gray"),
        ColorName(Color(0xFF6B8E23), "Olive Drab"),
        ColorName(Color(0xFF6C3082), "Eminence"),
        ColorName(Color(0xFF6CDAE7), "Turquoise Blue"),
        ColorName(Color(0xFF6D0101), "Lonestar"),
        ColorName(Color(0xFF6D5E54), "Pine Cone"),
        ColorName(Color(0xFF6D6C6C), "Dove Gray"),
        ColorName(Color(0xFF6D9292), "Juniper"),
        ColorName(Color(0xFF6D92A1), "Gothic"),
        ColorName(Color(0xFF6E0902), "Red Oxide"),
        ColorName(Color(0xFF6E1D14), "Moccaccino"),
        ColorName(Color(0xFF6E4826), "Pickled Bean"),
        ColorName(Color(0xFF6E4B26), "Dallas"),
        ColorName(Color(0xFF6E6D57), "Kokoda"),
        ColorName(Color(0xFF6E7783), "Pale Sky"),
        ColorName(Color(0xFF6F440C), "Cafe Royale"),
        ColorName(Color(0xFF6F6A61), "Flint"),
        ColorName(Color(0xFF6F8E63), "Highland"),
        ColorName(Color(0xFF6F9D02), "Limeade"),
        ColorName(Color(0xFF6FD0C5), "Downy"),
        ColorName(Color(0xFF701C1C), "Persian Plum"),
        ColorName(Color(0xFF704214), "Sepia"),
        ColorName(Color(0xFF704A07), "Antique Bronze"),
        ColorName(Color(0xFF704F50), "Ferra"),
        ColorName(Color(0xFF706555), "Coffee"),
        ColorName(Color(0xFF708090), "Slate Gray"),
        ColorName(Color(0xFF711A00), "Cedar Wood Finish"),
        ColorName(Color(0xFF71291D), "Metallic Copper"),
        ColorName(Color(0xFF714693), "Affair"),
        ColorName(Color(0xFF714AB2), "Studio"),
        ColorName(Color(0xFF715D47), "Tobacco Brown"),
        ColorName(Color(0xFF716338), "Yellow Metal"),
        ColorName(Color(0xFF716B56), "Peat"),
        ColorName(Color(0xFF716E10), "Olivetone"),
        ColorName(Color(0xFF717486), "Storm Gray"),
        ColorName(Color(0xFF718080), "Sirocco"),
        ColorName(Color(0xFF71D9E2), "Aquamarine Blue"),
        ColorName(Color(0xFF72010F), "Venetian Red"),
        ColorName(Color(0xFF724A2F), "Old Copper"),
        ColorName(Color(0xFF726D4E), "Go Ben"),
        ColorName(Color(0xFF727B89), "Raven"),
        ColorName(Color(0xFF731E8F), "Seance"),
        ColorName(Color(0xFF734A12), "Raw Umber"),
        ColorName(Color(0xFF736C9F), "Kimberly"),
        ColorName(Color(0xFF736D58), "Crocodile"),
        ColorName(Color(0xFF737829), "Crete"),
        ColorName(Color(0xFF738678), "Xanadu"),
        ColorName(Color(0xFF74640D), "Spicy Mustard"),
        ColorName(Color(0xFF747D63), "Limed Ash"),
        ColorName(Color(0xFF747D83), "Rolling Stone"),
        ColorName(Color(0xFF748881), "Blue Smoke"),
        ColorName(Color(0xFF749378), "Laurel"),
        ColorName(Color(0xFF74C365), "Mantis"),
        ColorName(Color(0xFF755A57), "Russett"),
        ColorName(Color(0xFF7563A8), "Deluge"),
        ColorName(Color(0xFF76395D), "Cosmic"),
        ColorName(Color(0xFF7666C6), "Blue Marguerite"),
        ColorName(Color(0xFF76BD17), "Lima"),
        ColorName(Color(0xFF76D7EA), "Sky Blue"),
        ColorName(Color(0xFF770F05), "Dark Burgundy"),
        ColorName(Color(0xFF771F1F), "Crown of Thorns"),
        ColorName(Color(0xFF773F1A), "Walnut"),
        ColorName(Color(0xFF776F61), "Pablo"),
        ColorName(Color(0xFF778120), "Pacifika"),
        ColorName(Color(0xFF779E86), "Oxley"),
        ColorName(Color(0xFF77DD77), "Pastel Green"),
        ColorName(Color(0xFF780109), "Japanese Maple"),
        ColorName(Color(0xFF782D19), "Mocha"),
        ColorName(Color(0xFF782F16), "Peanut"),
        ColorName(Color(0xFF78866B), "Camouflage Green"),
        ColorName(Color(0xFF788A25), "Wasabi"),
        ColorName(Color(0xFF788BBA), "Ship Cove"),
        ColorName(Color(0xFF78A39C), "Sea Nymph"),
        ColorName(Color(0xFF795D4C), "Roman Coffee"),
        ColorName(Color(0xFF796878), "Old Lavender"),
        ColorName(Color(0xFF796989), "Rum"),
        ColorName(Color(0xFF796A78), "Fedora"),
        ColorName(Color(0xFF796D62), "Sandstone"),
        ColorName(Color(0xFF79DEEC), "Spray"),
        ColorName(Color(0xFF7A013A), "Siren"),
        ColorName(Color(0xFF7A58C1), "Fuchsia Blue"),
        ColorName(Color(0xFF7A7A7A), "Boulder"),
        ColorName(Color(0xFF7A89B8), "Wild Blue Yonder"),
        ColorName(Color(0xFF7AC488), "De York"),
        ColorName(Color(0xFF7B3801), "Red Beech"),
        ColorName(Color(0xFF7B3F00), "Cinnamon"),
        ColorName(Color(0xFF7B6608), "Yukon Gold"),
        ColorName(Color(0xFF7B7874), "Tapa"),
        ColorName(Color(0xFF7B7C94), "Waterloo "),
        ColorName(Color(0xFF7B8265), "Flax Smoke"),
        ColorName(Color(0xFF7B9F80), "Amulet"),
        ColorName(Color(0xFF7BA05B), "Asparagus"),
        ColorName(Color(0xFF7C1C05), "Kenyan Copper"),
        ColorName(Color(0xFF7C7631), "Pesto"),
        ColorName(Color(0xFF7C778A), "Topaz"),
        ColorName(Color(0xFF7C7B7A), "Concord"),
        ColorName(Color(0xFF7C7B82), "Jumbo"),
        ColorName(Color(0xFF7C881A), "Trendy Green"),
        ColorName(Color(0xFF7CA1A6), "Gumbo"),
        ColorName(Color(0xFF7CB0A1), "Acapulco"),
        ColorName(Color(0xFF7CB7BB), "Neptune"),
        ColorName(Color(0xFF7D2C14), "Pueblo"),
        ColorName(Color(0xFF7DA98D), "Bay Leaf"),
        ColorName(Color(0xFF7DC8F7), "Malibu"),
        ColorName(Color(0xFF7DD8C6), "Bermuda"),
        ColorName(Color(0xFF7E3A15), "Copper Canyon"),
        ColorName(Color(0xFF7F1734), "Claret"),
        ColorName(Color(0xFF7F3A02), "Peru Tan"),
        ColorName(Color(0xFF7F626D), "Falcon"),
        ColorName(Color(0xFF7F7589), "Mobster"),
        ColorName(Color(0xFF7F76D3), "Moody Blue"),
        ColorName(Color(0xFF7FFF00), "Chartreuse"),
        ColorName(Color(0xFF7FFFD4), "Aquamarine"),
        ColorName(Color(0xFF800000), "Maroon"),
        ColorName(Color(0xFF800B47), "Rose Bud Cherry"),
        ColorName(Color(0xFF801818), "Falu Red"),
        ColorName(Color(0xFF80341F), "Red Robin"),
        ColorName(Color(0xFF803790), "Vivid Violet"),
        ColorName(Color(0xFF80461B), "Russet"),
        ColorName(Color(0xFF807E79), "Friar Gray"),
        ColorName(Color(0xFF808000), "Olive"),
        ColorName(Color(0xFF808080), "Gray"),
        ColorName(Color(0xFF80B3AE), "Gulf Stream"),
        ColorName(Color(0xFF80B3C4), "Glacier"),
        ColorName(Color(0xFF80CCEA), "Seagull"),
        ColorName(Color(0xFF81422C), "Nutmeg"),
        ColorName(Color(0xFF816E71), "Spicy Pink"),
        ColorName(Color(0xFF817377), "Empress"),
        ColorName(Color(0xFF819885), "Spanish Green"),
        ColorName(Color(0xFF826F65), "Sand Dune"),
        ColorName(Color(0xFF828685), "Gunsmoke"),
        ColorName(Color(0xFF828F72), "Battleship Gray"),
        ColorName(Color(0xFF831923), "Merlot"),
        ColorName(Color(0xFF837050), "Shadow"),
        ColorName(Color(0xFF83AA5D), "Chelsea Cucumber"),
        ColorName(Color(0xFF83D0C6), "Monte Carlo"),
        ColorName(Color(0xFF843179), "Plum"),
        ColorName(Color(0xFF84A0A0), "Granny Smith"),
        ColorName(Color(0xFF8581D9), "Chetwode Blue"),
        ColorName(Color(0xFF858470), "Bandicoot"),
        ColorName(Color(0xFF859FAF), "Bali Hai"),
        ColorName(Color(0xFF85C4CC), "Half Baked"),
        ColorName(Color(0xFF860111), "Red Devil"),
        ColorName(Color(0xFF863C3C), "Lotus"),
        ColorName(Color(0xFF86483C), "Ironstone"),
        ColorName(Color(0xFF864D1E), "Bull Shot"),
        ColorName(Color(0xFF86560A), "Rusty Nail"),
        ColorName(Color(0xFF868974), "Bitter"),
        ColorName(Color(0xFF86949F), "Regent Gray"),
        ColorName(Color(0xFF871550), "Disco"),
        ColorName(Color(0xFF87756E), "Americano"),
        ColorName(Color(0xFF877C7B), "Hurricane"),
        ColorName(Color(0xFF878D91), "Oslo Gray"),
        ColorName(Color(0xFF87AB39), "Sushi"),
        ColorName(Color(0xFF885342), "Spicy Mix"),
        ColorName(Color(0xFF886221), "Kumera"),
        ColorName(Color(0xFF888387), "Suva Gray"),
        ColorName(Color(0xFF888D65), "Avocado"),
        ColorName(Color(0xFF893456), "Camelot"),
        ColorName(Color(0xFF893843), "Solid Pink"),
        ColorName(Color(0xFF894367), "Cannon Pink"),
        ColorName(Color(0xFF897D6D), "Makara"),
        ColorName(Color(0xFF8A3324), "Burnt Umber"),
        ColorName(Color(0xFF8A73D6), "True V"),
        ColorName(Color(0xFF8A8360), "Clay Creek"),
        ColorName(Color(0xFF8A8389), "Monsoon"),
        ColorName(Color(0xFF8A8F8A), "Stack"),
        ColorName(Color(0xFF8AB9F1), "Jordy Blue"),
        ColorName(Color(0xFF8B00FF), "Electric Violet"),
        ColorName(Color(0xFF8B0723), "Monarch"),
        ColorName(Color(0xFF8B6B0B), "Corn Harvest"),
        ColorName(Color(0xFF8B8470), "Olive Haze"),
        ColorName(Color(0xFF8B847E), "Schooner"),
        ColorName(Color(0xFF8B8680), "Natural Gray"),
        ColorName(Color(0xFF8B9C90), "Mantle"),
        ColorName(Color(0xFF8B9FEE), "Portage"),
        ColorName(Color(0xFF8BA690), "Envy"),
        ColorName(Color(0xFF8BA9A5), "Cascade"),
        ColorName(Color(0xFF8BE6D8), "Riptide"),
        ColorName(Color(0xFF8C055E), "Cardinal Pink"),
        ColorName(Color(0xFF8C472F), "Mule Fawn"),
        ColorName(Color(0xFF8C5738), "Potters Clay"),
        ColorName(Color(0xFF8C6495), "Trendy Pink"),
        ColorName(Color(0xFF8D0226), "Paprika"),
        ColorName(Color(0xFF8D3D38), "Sanguine Brown"),
        ColorName(Color(0xFF8D3F3F), "Tosca"),
        ColorName(Color(0xFF8D7662), "Cement"),
        ColorName(Color(0xFF8D8974), "Granite Green"),
        ColorName(Color(0xFF8D90A1), "Manatee"),
        ColorName(Color(0xFF8DA8CC), "Polo Blue"),
        ColorName(Color(0xFF8E0000), "Red Berry"),
        ColorName(Color(0xFF8E4D1E), "Rope"),
        ColorName(Color(0xFF8E6F70), "Opium"),
        ColorName(Color(0xFF8E775E), "Domino"),
        ColorName(Color(0xFF8E8190), "Mamba"),
        ColorName(Color(0xFF8EABC1), "Nepal"),
        ColorName(Color(0xFF8F021C), "Pohutukawa"),
        ColorName(Color(0xFF8F3E33), "El Salva"),
        ColorName(Color(0xFF8F4B0E), "Korma"),
        ColorName(Color(0xFF8F8176), "Squirrel"),
        ColorName(Color(0xFF8FD6B4), "Vista Blue"),
        ColorName(Color(0xFF900020), "Burgundy"),
        ColorName(Color(0xFF901E1E), "Old Brick"),
        ColorName(Color(0xFF907874), "Hemp"),
        ColorName(Color(0xFF907B71), "Almond Frost"),
        ColorName(Color(0xFF908D39), "Sycamore"),
        ColorName(Color(0xFF92000A), "Sangria"),
        ColorName(Color(0xFF924321), "Cumin"),
        ColorName(Color(0xFF926F5B), "Beaver"),
        ColorName(Color(0xFF928573), "Stonewall"),
        ColorName(Color(0xFF928590), "Venus"),
        ColorName(Color(0xFF9370DB), "Medium Purple"),
        ColorName(Color(0xFF93CCEA), "Cornflower"),
        ColorName(Color(0xFF93DFB8), "Algae Green"),
        ColorName(Color(0xFF944747), "Copper Rust"),
        ColorName(Color(0xFF948771), "Arrowtown"),
        ColorName(Color(0xFF950015), "Scarlett"),
        ColorName(Color(0xFF956387), "Strikemaster"),
        ColorName(Color(0xFF959396), "Mountain Mist"),
        ColorName(Color(0xFF960018), "Carmine"),
        ColorName(Color(0xFF964B00), "Brown"),
        ColorName(Color(0xFF967059), "Leather"),
        ColorName(Color(0xFF9678B6), "Purple Mountain"),
        ColorName(Color(0xFF967BB6), "Lavender Purple"),
        ColorName(Color(0xFF96A8A1), "Pewter"),
        ColorName(Color(0xFF96BBAB), "Summer Green"),
        ColorName(Color(0xFF97605D), "Au Chico"),
        ColorName(Color(0xFF9771B5), "Wisteria"),
        ColorName(Color(0xFF97CD2D), "Atlantis"),
        ColorName(Color(0xFF983D61), "Vin Rouge"),
        ColorName(Color(0xFF9874D3), "Lilac Bush"),
        ColorName(Color(0xFF98777B), "Bazaar"),
        ColorName(Color(0xFF98811B), "Hacienda"),
        ColorName(Color(0xFF988D77), "Pale Oyster"),
        ColorName(Color(0xFF98FF98), "Mint Green"),
        ColorName(Color(0xFF990066), "Fresh Eggplant"),
        ColorName(Color(0xFF991199), "Violet Eggplant"),
        ColorName(Color(0xFF991613), "Tamarillo"),
        ColorName(Color(0xFF991B07), "Totem Pole"),
        ColorName(Color(0xFF996666), "Copper Rose"),
        ColorName(Color(0xFF9966CC), "Amethyst"),
        ColorName(Color(0xFF997A8D), "Mountbatten Pink"),
        ColorName(Color(0xFF9999CC), "Blue Bell"),
        ColorName(Color(0xFF9A3820), "Prairie Sand"),
        ColorName(Color(0xFF9A6E61), "Toast"),
        ColorName(Color(0xFF9A9577), "Gurkha"),
        ColorName(Color(0xFF9AB973), "Olivine"),
        ColorName(Color(0xFF9AC2B8), "Shadow Green"),
        ColorName(Color(0xFF9B4703), "Oregon"),
        ColorName(Color(0xFF9B9E8F), "Lemon Grass"),
        ColorName(Color(0xFF9C3336), "Stiletto"),
        ColorName(Color(0xFF9D5616), "Hawaiian Tan"),
        ColorName(Color(0xFF9DACB7), "Gull Gray"),
        ColorName(Color(0xFF9DC209), "Pistachio"),
        ColorName(Color(0xFF9DE093), "Granny Smith Apple"),
        ColorName(Color(0xFF9DE5FF), "Anakiwa"),
        ColorName(Color(0xFF9E5302), "Chelsea Gem"),
        ColorName(Color(0xFF9E5B40), "Sepia Skin"),
        ColorName(Color(0xFF9EA587), "Sage"),
        ColorName(Color(0xFF9EA91F), "Citron"),
        ColorName(Color(0xFF9EB1CD), "Rock Blue"),
        ColorName(Color(0xFF9EDEE0), "Morning Glory"),
        ColorName(Color(0xFF9F381D), "Cognac"),
        ColorName(Color(0xFF9F821C), "Reef Gold"),
        ColorName(Color(0xFF9F9F9C), "Star Dust"),
        ColorName(Color(0xFF9FA0B1), "Santas Gray"),
        ColorName(Color(0xFF9FD7D3), "Sinbad"),
        ColorName(Color(0xFF9FDD8C), "Feijoa"),
        ColorName(Color(0xFFA02712), "Tabasco"),
        ColorName(Color(0xFFA1750D), "Buttered Rum"),
        ColorName(Color(0xFFA1ADB5), "Hit Gray"),
        ColorName(Color(0xFFA1C50A), "Citrus"),
        ColorName(Color(0xFFA1DAD7), "Aqua Island"),
        ColorName(Color(0xFFA1E9DE), "Water Leaf"),
        ColorName(Color(0xFFA2006D), "Flirt"),
        ColorName(Color(0xFFA23B6C), "Rouge"),
        ColorName(Color(0xFFA26645), "Cape Palliser"),
        ColorName(Color(0xFFA2AAB3), "Gray Chateau"),
        ColorName(Color(0xFFA2AEAB), "Edward"),
        ColorName(Color(0xFFA3807B), "Pharlap"),
        ColorName(Color(0xFFA397B4), "Amethyst Smoke"),
        ColorName(Color(0xFFA3E3ED), "Blizzard Blue"),
        ColorName(Color(0xFFA4A49D), "Delta"),
        ColorName(Color(0xFFA4A6D3), "Wistful"),
        ColorName(Color(0xFFA4AF6E), "Green Smoke"),
        ColorName(Color(0xFFA50B5E), "Jazzberry Jam"),
        ColorName(Color(0xFFA59B91), "Zorba"),
        ColorName(Color(0xFFA5CB0C), "Bahia"),
        ColorName(Color(0xFFA62F20), "Roof Terracotta"),
        ColorName(Color(0xFFA65529), "Paarl"),
        ColorName(Color(0xFFA68B5B), "Barley Corn"),
        ColorName(Color(0xFFA69279), "Donkey Brown"),
        ColorName(Color(0xFFA6A29A), "Dawn"),
        ColorName(Color(0xFFA72525), "Mexican Red"),
        ColorName(Color(0xFFA7882C), "Luxor Gold"),
        ColorName(Color(0xFFA85307), "Rich Gold"),
        ColorName(Color(0xFFA86515), "Reno Sand"),
        ColorName(Color(0xFFA86B6B), "Coral Tree"),
        ColorName(Color(0xFFA8989B), "Dusty Gray"),
        ColorName(Color(0xFFA899E6), "Dull Lavender"),
        ColorName(Color(0xFFA8A589), "Tallow"),
        ColorName(Color(0xFFA8AE9C), "Bud"),
        ColorName(Color(0xFFA8AF8E), "Locust"),
        ColorName(Color(0xFFA8BD9F), "Norway"),
        ColorName(Color(0xFFA8E3BD), "Chinook"),
        ColorName(Color(0xFFA9A491), "Gray Olive"),
        ColorName(Color(0xFFA9ACB6), "Aluminium"),
        ColorName(Color(0xFFA9B2C3), "Cadet Blue"),
        ColorName(Color(0xFFA9B497), "Schist"),
        ColorName(Color(0xFFA9BDBF), "Tower Gray"),
        ColorName(Color(0xFFA9BEF2), "Perano"),
        ColorName(Color(0xFFA9C6C2), "Opal"),
        ColorName(Color(0xFFAA375A), "Night Shadz"),
        ColorName(Color(0xFFAA4203), "Fire"),
        ColorName(Color(0xFFAA8B5B), "Muesli"),
        ColorName(Color(0xFFAA8D6F), "Sandal"),
        ColorName(Color(0xFFAAA5A9), "Shady Lady"),
        ColorName(Color(0xFFAAA9CD), "Logan"),
        ColorName(Color(0xFFAAABB7), "Spun Pearl"),
        ColorName(Color(0xFFAAD6E6), "Regent St Blue"),
        ColorName(Color(0xFFAAF0D1), "Magic Mint"),
        ColorName(Color(0xFFAB0563), "Lipstick"),
        ColorName(Color(0xFFAB3472), "Royal Heath"),
        ColorName(Color(0xFFAB917A), "Sandrift"),
        ColorName(Color(0xFFABA0D9), "Cold Purple"),
        ColorName(Color(0xFFABA196), "Bronco"),
        ColorName(Color(0xFFAC8A56), "Limed Oak"),
        ColorName(Color(0xFFAC91CE), "East Side"),
        ColorName(Color(0xFFAC9E22), "Lemon Ginger"),
        ColorName(Color(0xFFACA494), "Napa"),
        ColorName(Color(0xFFACA586), "Hillary"),
        ColorName(Color(0xFFACA59F), "Cloudy"),
        ColorName(Color(0xFFACACAC), "Silver Chalice"),
        ColorName(Color(0xFFACB78E), "Swamp Green"),
        ColorName(Color(0xFFACCBB1), "Spring Rain"),
        ColorName(Color(0xFFACDD4D), "Conifer"),
        ColorName(Color(0xFFACE1AF), "Celadon"),
        ColorName(Color(0xFFAD781B), "Mandalay"),
        ColorName(Color(0xFFADBED1), "Casper"),
        ColorName(Color(0xFFADDFAD), "Moss Green"),
        ColorName(Color(0xFFADE6C4), "Padua"),
        ColorName(Color(0xFFADFF2F), "Green Yellow"),
        ColorName(Color(0xFFAE4560), "Hippie Pink"),
        ColorName(Color(0xFFAE6020), "Desert"),
        ColorName(Color(0xFFAE809E), "Bouquet"),
        ColorName(Color(0xFFAF4035), "Medium Carmine"),
        ColorName(Color(0xFFAF4D43), "Apple Blossom"),
        ColorName(Color(0xFFAF593E), "Brown Rust"),
        ColorName(Color(0xFFAF8751), "Driftwood"),
        ColorName(Color(0xFFAF8F2C), "Alpine"),
        ColorName(Color(0xFFAF9F1C), "Lucky"),
        ColorName(Color(0xFFAFA09E), "Martini"),
        ColorName(Color(0xFFAFB1B8), "Bombay"),
        ColorName(Color(0xFFAFBDD9), "Pigeon Post"),
        ColorName(Color(0xFFB04C6A), "Cadillac"),
        ColorName(Color(0xFFB05D54), "Matrix"),
        ColorName(Color(0xFFB05E81), "Tapestry"),
        ColorName(Color(0xFFB06608), "Mai Tai"),
        ColorName(Color(0xFFB09A95), "Del Rio"),
        ColorName(Color(0xFFB0E0E6), "Powder Blue"),
        ColorName(Color(0xFFB0E313), "Inch Worm"),
        ColorName(Color(0xFFB10000), "Bright Red"),
        ColorName(Color(0xFFB14A0B), "Vesuvius"),
        ColorName(Color(0xFFB1610B), "Pumpkin Skin"),
        ColorName(Color(0xFFB16D52), "Santa Fe"),
        ColorName(Color(0xFFB19461), "Teak"),
        ColorName(Color(0xFFB1E2C1), "Fringy Flower"),
        ColorName(Color(0xFFB1F4E7), "Ice Cold"),
        ColorName(Color(0xFFB20931), "Shiraz"),
        ColorName(Color(0xFFB2A1EA), "Biloba Flower"),
        ColorName(Color(0xFFB32D29), "Tall Poppy"),
        ColorName(Color(0xFFB35213), "Fiery Orange"),
        ColorName(Color(0xFFB38007), "Hot Toddy"),
        ColorName(Color(0xFFB3AF95), "Taupe Gray"),
        ColorName(Color(0xFFB3C110), "La Rioja"),
        ColorName(Color(0xFFB43332), "Well Read"),
        ColorName(Color(0xFFB44668), "Blush"),
        ColorName(Color(0xFFB4CFD3), "Jungle Mist"),
        ColorName(Color(0xFFB57281), "Turkish Rose"),
        ColorName(Color(0xFFB57EDC), "Lavender"),
        ColorName(Color(0xFFB5A27F), "Mongoose"),
        ColorName(Color(0xFFB5B35C), "Olive Green"),
        ColorName(Color(0xFFB5D2CE), "Jet Stream"),
        ColorName(Color(0xFFB5ECDF), "Cruise"),
        ColorName(Color(0xFFB6316C), "Hibiscus"),
        ColorName(Color(0xFFB69D98), "Thatch"),
        ColorName(Color(0xFFB6B095), "Heathered Gray"),
        ColorName(Color(0xFFB6BAA4), "Eagle"),
        ColorName(Color(0xFFB6D1EA), "Spindle"),
        ColorName(Color(0xFFB6D3BF), "Gum Leaf"),
        ColorName(Color(0xFFB7410E), "Rust"),
        ColorName(Color(0xFFB78E5C), "Muddy Waters"),
        ColorName(Color(0xFFB7A214), "Sahara"),
        ColorName(Color(0xFFB7A458), "Husk"),
        ColorName(Color(0xFFB7B1B1), "Nobel"),
        ColorName(Color(0xFFB7C3D0), "Heather"),
        ColorName(Color(0xFFB7F0BE), "Madang"),
        ColorName(Color(0xFFB81104), "Milano Red"),
        ColorName(Color(0xFFB87333), "Copper"),
        ColorName(Color(0xFFB8B56A), "Gimblet"),
        ColorName(Color(0xFFB8C1B1), "Green Spring"),
        ColorName(Color(0xFFB8C25D), "Celery"),
        ColorName(Color(0xFFB8E0F9), "Sail"),
        ColorName(Color(0xFFB94E48), "Chestnut"),
        ColorName(Color(0xFFB95140), "Crail"),
        ColorName(Color(0xFFB98D28), "Marigold"),
        ColorName(Color(0xFFB9C46A), "Wild Willow"),
        ColorName(Color(0xFFB9C8AC), "Rainee"),
        ColorName(Color(0xFFBA0101), "Guardsman Red"),
        ColorName(Color(0xFFBA450C), "Rock Spray"),
        ColorName(Color(0xFFBA6F1E), "Bourbon"),
        ColorName(Color(0xFFBA7F03), "Pirate Gold"),
        ColorName(Color(0xFFBAB1A2), "Nomad"),
        ColorName(Color(0xFFBAC7C9), "Submarine"),
        ColorName(Color(0xFFBAEEF9), "Charlotte"),
        ColorName(Color(0xFFBB3385), "Medium Red Violet"),
        ColorName(Color(0xFFBB8983), "Brandy Rose"),
        ColorName(Color(0xFFBBD009), "Rio Grande"),
        ColorName(Color(0xFFBBD7C1), "Surf"),
        ColorName(Color(0xFFBCC9C2), "Powder Ash"),
        ColorName(Color(0xFFBD5E2E), "Tuscany"),
        ColorName(Color(0xFFBD978E), "Quicksand"),
        ColorName(Color(0xFFBDB1A8), "Silk"),
        ColorName(Color(0xFFBDB2A1), "Malta"),
        ColorName(Color(0xFFBDB3C7), "Chatelle"),
        ColorName(Color(0xFFBDBBD7), "Lavender Gray"),
        ColorName(Color(0xFFBDBDC6), "French Gray"),
        ColorName(Color(0xFFBDC8B3), "Clay Ash"),
        ColorName(Color(0xFFBDC9CE), "Loblolly"),
        ColorName(Color(0xFFBDEDFD), "French Pass"),
        ColorName(Color(0xFFBEA6C3), "London Hue"),
        ColorName(Color(0xFFBEB5B7), "Pink Swan"),
        ColorName(Color(0xFFBEDE0D), "Fuego"),
        ColorName(Color(0xFFBF5500), "Rose of Sharon"),
        ColorName(Color(0xFFBFB8B0), "Tide"),
        ColorName(Color(0xFFBFBED8), "Blue Haze"),
        ColorName(Color(0xFFBFC1C2), "Silver Sand"),
        ColorName(Color(0xFFBFC921), "Key Lime Pie"),
        ColorName(Color(0xFFBFDBE2), "Ziggurat"),
        ColorName(Color(0xFFBFFF00), "Lime"),
        ColorName(Color(0xFFC02B18), "Thunderbird"),
        ColorName(Color(0xFFC04737), "Mojo"),
        ColorName(Color(0xFFC08081), "Old Rose"),
        ColorName(Color(0xFFC0C0C0), "Silver"),
        ColorName(Color(0xFFC0D3B9), "Pale Leaf"),
        ColorName(Color(0xFFC0D8B6), "Pixie Green"),
        ColorName(Color(0xFFC1440E), "Tia Maria"),
        ColorName(Color(0xFFC154C1), "Fuchsia Pink"),
        ColorName(Color(0xFFC1A004), "Buddha Gold"),
        ColorName(Color(0xFFC1B7A4), "Bison Hide"),
        ColorName(Color(0xFFC1BAB0), "Tea"),
        ColorName(Color(0xFFC1BECD), "Gray Suit"),
        ColorName(Color(0xFFC1D7B0), "Sprout"),
        ColorName(Color(0xFFC1F07C), "Sulu"),
        ColorName(Color(0xFFC26B03), "Indochine"),
        ColorName(Color(0xFFC2955D), "Twine"),
        ColorName(Color(0xFFC2BDB6), "Cotton Seed"),
        ColorName(Color(0xFFC2CAC4), "Pumice"),
        ColorName(Color(0xFFC2E8E5), "Jagged Ice"),
        ColorName(Color(0xFFC32148), "Maroon Flush"),
        ColorName(Color(0xFFC3B091), "Indian Khaki"),
        ColorName(Color(0xFFC3BFC1), "Pale Slate"),
        ColorName(Color(0xFFC3C3BD), "Gray Nickel"),
        ColorName(Color(0xFFC3CDE6), "Periwinkle Gray"),
        ColorName(Color(0xFFC3D1D1), "Tiara"),
        ColorName(Color(0xFFC3DDF9), "Tropical Blue"),
        ColorName(Color(0xFFC41E3A), "Cardinal"),
        ColorName(Color(0xFFC45655), "Fuzzy Wuzzy Brown"),
        ColorName(Color(0xFFC45719), "Orange Roughy"),
        ColorName(Color(0xFFC4C4BC), "Mist Gray"),
        ColorName(Color(0xFFC4D0B0), "Coriander"),
        ColorName(Color(0xFFC4F4EB), "Mint Tulip"),
        ColorName(Color(0xFFC54B8C), "Mulberry"),
        ColorName(Color(0xFFC59922), "Nugget"),
        ColorName(Color(0xFFC5994B), "Tussock"),
        ColorName(Color(0xFFC5DBCA), "Sea Mist"),
        ColorName(Color(0xFFC5E17A), "Yellow Green"),
        ColorName(Color(0xFFC62D42), "Brick Red"),
        ColorName(Color(0xFFC6726B), "Contessa"),
        ColorName(Color(0xFFC69191), "Oriental Pink"),
        ColorName(Color(0xFFC6A84B), "Roti"),
        ColorName(Color(0xFFC6C3B5), "Ash"),
        ColorName(Color(0xFFC6C8BD), "Kangaroo"),
        ColorName(Color(0xFFC6E610), "Las Palmas"),
        ColorName(Color(0xFFC7031E), "Monza"),
        ColorName(Color(0xFFC71585), "Red Violet"),
        ColorName(Color(0xFFC7BCA2), "Coral Reef"),
        ColorName(Color(0xFFC7C1FF), "Melrose"),
        ColorName(Color(0xFFC7C4BF), "Cloud"),
        ColorName(Color(0xFFC7C9D5), "Ghost"),
        ColorName(Color(0xFFC7CD90), "Pine Glade"),
        ColorName(Color(0xFFC7DDE5), "Botticelli"),
        ColorName(Color(0xFFC88A65), "Antique Brass"),
        ColorName(Color(0xFFC8A2C8), "Lilac"),
        ColorName(Color(0xFFC8A528), "Hokey Pokey"),
        ColorName(Color(0xFFC8AABF), "Lily"),
        ColorName(Color(0xFFC8B568), "Laser"),
        ColorName(Color(0xFFC8E3D7), "Edgewater"),
        ColorName(Color(0xFFC96323), "Piper"),
        ColorName(Color(0xFFC99415), "Pizza"),
        ColorName(Color(0xFFC9A0DC), "Light Wisteria"),
        ColorName(Color(0xFFC9B29B), "Rodeo Dust"),
        ColorName(Color(0xFFC9B35B), "Sundance"),
        ColorName(Color(0xFFC9B93B), "Earls Green"),
        ColorName(Color(0xFFC9C0BB), "Silver Rust"),
        ColorName(Color(0xFFC9D9D2), "Conch"),
        ColorName(Color(0xFFC9FFA2), "Reef"),
        ColorName(Color(0xFFC9FFE5), "Aero Blue"),
        ColorName(Color(0xFFCA3435), "Flush Mahogany"),
        ColorName(Color(0xFFCABB48), "Turmeric"),
        ColorName(Color(0xFFCADCD4), "Paris White"),
        ColorName(Color(0xFFCAE00D), "Bitter Lemon"),
        ColorName(Color(0xFFCAE6DA), "Skeptic"),
        ColorName(Color(0xFFCB8FA9), "Viola"),
        ColorName(Color(0xFFCBCAB6), "Foggy Gray"),
        ColorName(Color(0xFFCBD3B0), "Green Mist"),
        ColorName(Color(0xFFCBDBD6), "Nebula"),
        ColorName(Color(0xFFCC3333), "Persian Red"),
        ColorName(Color(0xFFCC5501), "Burnt Orange"),
        ColorName(Color(0xFFCC7722), "Ochre"),
        ColorName(Color(0xFFCC8899), "Puce"),
        ColorName(Color(0xFFCCCAA8), "Thistle Green"),
        ColorName(Color(0xFFCCCCFF), "Periwinkle"),
        ColorName(Color(0xFFCCFF00), "Electric Lime"),
        ColorName(Color(0xFFCD5700), "Tenn"),
        ColorName(Color(0xFFCD5C5C), "Chestnut Rose"),
        ColorName(Color(0xFFCD8429), "Brandy Punch"),
        ColorName(Color(0xFFCDF4FF), "Onahau"),
        ColorName(Color(0xFFCEB98F), "Sorrell Brown"),
        ColorName(Color(0xFFCEBABA), "Cold Turkey"),
        ColorName(Color(0xFFCEC291), "Yuma"),
        ColorName(Color(0xFFCEC7A7), "Chino"),
        ColorName(Color(0xFFCFA39D), "Eunry"),
        ColorName(Color(0xFFCFB53B), "Old Gold"),
        ColorName(Color(0xFFCFDCCF), "Tasman"),
        ColorName(Color(0xFFCFE5D2), "Surf Crest"),
        ColorName(Color(0xFFCFF9F3), "Humming Bird"),
        ColorName(Color(0xFFCFFAF4), "Scandal"),
        ColorName(Color(0xFFD05F04), "Red Stage"),
        ColorName(Color(0xFFD06DA1), "Hopbush"),
        ColorName(Color(0xFFD07D12), "Meteor"),
        ColorName(Color(0xFFD0BEF8), "Perfume"),
        ColorName(Color(0xFFD0C0E5), "Prelude"),
        ColorName(Color(0xFFD0F0C0), "Tea Green"),
        ColorName(Color(0xFFD18F1B), "Geebung"),
        ColorName(Color(0xFFD1BEA8), "Vanilla"),
        ColorName(Color(0xFFD1C6B4), "Soft Amber"),
        ColorName(Color(0xFFD1D2CA), "Celeste"),
        ColorName(Color(0xFFD1D2DD), "Mischka"),
        ColorName(Color(0xFFD1E231), "Pear"),
        ColorName(Color(0xFFD2691E), "Hot Cinnamon"),
        ColorName(Color(0xFFD27D46), "Raw Sienna"),
        ColorName(Color(0xFFD29EAA), "Careys Pink"),
        ColorName(Color(0xFFD2B48C), "Tan"),
        ColorName(Color(0xFFD2DA97), "Deco"),
        ColorName(Color(0xFFD2F6DE), "Blue Romance"),
        ColorName(Color(0xFFD2F8B0), "Gossip"),
        ColorName(Color(0xFFD3CBBA), "Sisal"),
        ColorName(Color(0xFFD3CDC5), "Swirl"),
        ColorName(Color(0xFFD47494), "Charm"),
        ColorName(Color(0xFFD4B6AF), "Clam Shell"),
        ColorName(Color(0xFFD4BF8D), "Straw"),
        ColorName(Color(0xFFD4C4A8), "Akaroa"),
        ColorName(Color(0xFFD4CD16), "Bird Flower"),
        ColorName(Color(0xFFD4D7D9), "Iron"),
        ColorName(Color(0xFFD4DFE2), "Geyser"),
        ColorName(Color(0xFFD4E2FC), "Hawkes Blue"),
        ColorName(Color(0xFFD54600), "Grenadier"),
        ColorName(Color(0xFFD591A4), "Can Can"),
        ColorName(Color(0xFFD59A6F), "Whiskey"),
        ColorName(Color(0xFFD5D195), "Winter Hazel"),
        ColorName(Color(0xFFD5F6E3), "Granny Apple"),
        ColorName(Color(0xFFD69188), "My Pink"),
        ColorName(Color(0xFFD6C562), "Tacha"),
        ColorName(Color(0xFFD6CEF6), "Moon Raker"),
        ColorName(Color(0xFFD6D6D1), "Quill Gray"),
        ColorName(Color(0xFFD6FFDB), "Snowy Mint"),
        ColorName(Color(0xFFD7837F), "New York Pink"),
        ColorName(Color(0xFFD7C498), "Pavlova"),
        ColorName(Color(0xFFD7D0FF), "Fog"),
        ColorName(Color(0xFFD84437), "Valencia"),
        ColorName(Color(0xFFD87C63), "Japonica"),
        ColorName(Color(0xFFD8BFD8), "Thistle"),
        ColorName(Color(0xFFD8C2D5), "Maverick"),
        ColorName(Color(0xFFD8FCFA), "Foam"),
        ColorName(Color(0xFFD94972), "Cabaret"),
        ColorName(Color(0xFFD99376), "Burning Sand"),
        ColorName(Color(0xFFD9B99B), "Cameo"),
        ColorName(Color(0xFFD9D6CF), "Timberwolf"),
        ColorName(Color(0xFFD9DCC1), "Tana"),
        ColorName(Color(0xFFD9E4F5), "Link Water"),
        ColorName(Color(0xFFD9F7FF), "Mabel"),
        ColorName(Color(0xFFDA3287), "Cerise"),
        ColorName(Color(0xFFDA5B38), "Flame Pea"),
        ColorName(Color(0xFFDA6304), "Bamboo"),
        ColorName(Color(0xFFDA6A41), "Red Damask"),
        ColorName(Color(0xFFDA70D6), "Orchid"),
        ColorName(Color(0xFFDA8A67), "Copperfield"),
        ColorName(Color(0xFFDAA520), "Golden Grass"),
        ColorName(Color(0xFFDAECD6), "Zanah"),
        ColorName(Color(0xFFDAF4F0), "Iceberg"),
        ColorName(Color(0xFFDAFAFF), "Oyster Bay"),
        ColorName(Color(0xFFDB5079), "Cranberry"),
        ColorName(Color(0xFFDB9690), "Petite Orchid"),
        ColorName(Color(0xFFDB995E), "Di Serria"),
        ColorName(Color(0xFFDBDBDB), "Alto"),
        ColorName(Color(0xFFDBFFF8), "Frosted Mint"),
        ColorName(Color(0xFFDC143C), "Crimson"),
        ColorName(Color(0xFFDC4333), "Punch"),
        ColorName(Color(0xFFDCB20C), "Galliano"),
        ColorName(Color(0xFFDCB4BC), "Blossom"),
        ColorName(Color(0xFFDCD747), "Wattle"),
        ColorName(Color(0xFFDCD9D2), "Westar"),
        ColorName(Color(0xFFDCDDCC), "Moon Mist"),
        ColorName(Color(0xFFDCEDB4), "Caper"),
        ColorName(Color(0xFFDCF0EA), "Swans Down"),
        ColorName(Color(0xFFDDD6D5), "Swiss Coffee"),
        ColorName(Color(0xFFDDF9F1), "White Ice"),
        ColorName(Color(0xFFDE3163), "Cerise Red"),
        ColorName(Color(0xFFDE6360), "Roman"),
        ColorName(Color(0xFFDEA681), "Tumbleweed"),
        ColorName(Color(0xFFDEBA13), "Gold Tips"),
        ColorName(Color(0xFFDEC196), "Brandy"),
        ColorName(Color(0xFFDECBC6), "Wafer"),
        ColorName(Color(0xFFDED4A4), "Sapling"),
        ColorName(Color(0xFFDED717), "Barberry"),
        ColorName(Color(0xFFDEE5C0), "Beryl Green"),
        ColorName(Color(0xFFDEF5FF), "Pattens Blue"),
        ColorName(Color(0xFFDF73FF), "Heliotrope"),
        ColorName(Color(0xFFDFBE6F), "Apache"),
        ColorName(Color(0xFFDFCD6F), "Chenin"),
        ColorName(Color(0xFFDFCFDB), "Lola"),
        ColorName(Color(0xFFDFECDA), "Willow Brook"),
        ColorName(Color(0xFFDFFF00), "Chartreuse Yellow"),
        ColorName(Color(0xFFE0B0FF), "Mauve"),
        ColorName(Color(0xFFE0B646), "Anzac"),
        ColorName(Color(0xFFE0B974), "Harvest Gold"),
        ColorName(Color(0xFFE0C095), "Calico"),
        ColorName(Color(0xFFE0FFFF), "Baby Blue"),
        ColorName(Color(0xFFE16865), "Sunglo"),
        ColorName(Color(0xFFE1BC64), "Equator"),
        ColorName(Color(0xFFE1C0C8), "Pink Flare"),
        ColorName(Color(0xFFE1E6D6), "Periglacial Blue"),
        ColorName(Color(0xFFE1EAD4), "Kidnapper"),
        ColorName(Color(0xFFE1F6E8), "Tara"),
        ColorName(Color(0xFFE25465), "Mandy"),
        ColorName(Color(0xFFE2725B), "Terracotta"),
        ColorName(Color(0xFFE28913), "Golden Bell"),
        ColorName(Color(0xFFE292C0), "Shocking"),
        ColorName(Color(0xFFE29418), "Dixie"),
        ColorName(Color(0xFFE29CD2), "Light Orchid"),
        ColorName(Color(0xFFE2D8ED), "Snuff"),
        ColorName(Color(0xFFE2EBED), "Mystic"),
        ColorName(Color(0xFFE2F3EC), "Apple Green"),
        ColorName(Color(0xFFE30B5C), "Razzmatazz"),
        ColorName(Color(0xFFE32636), "Alizarin Crimson"),
        ColorName(Color(0xFFE34234), "Cinnabar"),
        ColorName(Color(0xFFE3BEBE), "Cavern Pink"),
        ColorName(Color(0xFFE3F5E1), "Peppermint"),
        ColorName(Color(0xFFE3F988), "Mindaro"),
        ColorName(Color(0xFFE47698), "Deep Blush"),
        ColorName(Color(0xFFE49B0F), "Gamboge"),
        ColorName(Color(0xFFE4C2D5), "Melanie"),
        ColorName(Color(0xFFE4CFDE), "Twilight"),
        ColorName(Color(0xFFE4D1C0), "Bone"),
        ColorName(Color(0xFFE4D422), "Sunflower"),
        ColorName(Color(0xFFE4D5B7), "Grain Brown"),
        ColorName(Color(0xFFE4D69B), "Zombie"),
        ColorName(Color(0xFFE4F6E7), "Frostee"),
        ColorName(Color(0xFFE4FFD1), "Snow Flurry"),
        ColorName(Color(0xFFE52B50), "Amaranth"),
        ColorName(Color(0xFFE5841B), "Zest"),
        ColorName(Color(0xFFE5CCC9), "Dust Storm"),
        ColorName(Color(0xFFE5D7BD), "Stark White"),
        ColorName(Color(0xFFE5D8AF), "Hampton"),
        ColorName(Color(0xFFE5E0E1), "Bon Jour"),
        ColorName(Color(0xFFE5E5E5), "Mercury"),
        ColorName(Color(0xFFE5F9F6), "Polar"),
        ColorName(Color(0xFFE64E03), "Trinidad"),
        ColorName(Color(0xFFE6BE8A), "Gold Sand"),
        ColorName(Color(0xFFE6BEA5), "Cashmere"),
        ColorName(Color(0xFFE6D7B9), "Double Spanish White"),
        ColorName(Color(0xFFE6E4D4), "Satin Linen"),
        ColorName(Color(0xFFE6F2EA), "Harp"),
        ColorName(Color(0xFFE6F8F3), "Off Green"),
        ColorName(Color(0xFFE6FFE9), "Hint of Green"),
        ColorName(Color(0xFFE6FFFF), "Tranquil"),
        ColorName(Color(0xFFE77200), "Mango Tango"),
        ColorName(Color(0xFFE7730A), "Christine"),
        ColorName(Color(0xFFE79F8C), "Tony's Pink"),
        ColorName(Color(0xFFE79FC4), "Kobi"),
        ColorName(Color(0xFFE7BCB4), "Rose Fog"),
        ColorName(Color(0xFFE7BF05), "Corn"),
        ColorName(Color(0xFFE7CD8C), "Putty"),
        ColorName(Color(0xFFE7ECE6), "Gray Nurse"),
        ColorName(Color(0xFFE7F8FF), "Lily White"),
        ColorName(Color(0xFFE7FEFF), "Bubbles"),
        ColorName(Color(0xFFE89928), "Fire Bush"),
        ColorName(Color(0xFFE8B9B3), "Shilo"),
        ColorName(Color(0xFFE8E0D5), "Pearl Bush"),
        ColorName(Color(0xFFE8EBE0), "Green White"),
        ColorName(Color(0xFFE8F1D4), "Chrome White"),
        ColorName(Color(0xFFE8F2EB), "Gin"),
        ColorName(Color(0xFFE8F5F2), "Aqua Squeeze"),
        ColorName(Color(0xFFE96E00), "Clementine"),
        ColorName(Color(0xFFE97451), "Burnt Sienna"),
        ColorName(Color(0xFFE97C07), "Tahiti Gold"),
        ColorName(Color(0xFFE9CECD), "Oyster Pink"),
        ColorName(Color(0xFFE9D75A), "Confetti"),
        ColorName(Color(0xFFE9E3E3), "Ebb"),
        ColorName(Color(0xFFE9F8ED), "Ottoman"),
        ColorName(Color(0xFFE9FFFD), "Clear Day"),
        ColorName(Color(0xFFEA88A8), "Carissma"),
        ColorName(Color(0xFFEAAE69), "Porsche"),
        ColorName(Color(0xFFEAB33B), "Tulip Tree"),
        ColorName(Color(0xFFEAC674), "Rob Roy"),
        ColorName(Color(0xFFEADAB8), "Raffia"),
        ColorName(Color(0xFFEAE8D4), "White Rock"),
        ColorName(Color(0xFFEAF6EE), "Panache"),
        ColorName(Color(0xFFEAF6FF), "Solitude"),
        ColorName(Color(0xFFEAF9F5), "Aqua Spring"),
        ColorName(Color(0xFFEAFFFE), "Dew"),
        ColorName(Color(0xFFEB9373), "Apricot"),
        ColorName(Color(0xFFEBC2AF), "Zinnwaldite"),
        ColorName(Color(0xFFECA927), "Fuel Yellow"),
        ColorName(Color(0xFFECC54E), "Ronchi"),
        ColorName(Color(0xFFECC7EE), "French Lilac"),
        ColorName(Color(0xFFECCDB9), "Just Right"),
        ColorName(Color(0xFFECE090), "Wild Rice"),
        ColorName(Color(0xFFECEBBD), "Fall Green"),
        ColorName(Color(0xFFECEBCE), "Aths Special"),
        ColorName(Color(0xFFECF245), "Starship"),
        ColorName(Color(0xFFED0A3F), "Red Ribbon"),
        ColorName(Color(0xFFED7A1C), "Tango"),
        ColorName(Color(0xFFED9121), "Carrot Orange"),
        ColorName(Color(0xFFED989E), "Sea Pink"),
        ColorName(Color(0xFFEDB381), "Tacao"),
        ColorName(Color(0xFFEDC9AF), "Desert Sand"),
        ColorName(Color(0xFFEDCDAB), "Pancho"),
        ColorName(Color(0xFFEDDCB1), "Chamois"),
        ColorName(Color(0xFFEDEA99), "Primrose"),
        ColorName(Color(0xFFEDF5DD), "Frost"),
        ColorName(Color(0xFFEDF5F5), "Aqua Haze"),
        ColorName(Color(0xFFEDF6FF), "Zumthor"),
        ColorName(Color(0xFFEDF9F1), "Narvik"),
        ColorName(Color(0xFFEDFC84), "Honeysuckle"),
        ColorName(Color(0xFFEE82EE), "Lavender Magenta"),
        ColorName(Color(0xFFEEC1BE), "Beauty Bush"),
        ColorName(Color(0xFFEED794), "Chalky"),
        ColorName(Color(0xFFEED9C4), "Almond"),
        ColorName(Color(0xFFEEDC82), "Flax"),
        ColorName(Color(0xFFEEDEDA), "Bizarre"),
        ColorName(Color(0xFFEEE3AD), "Double Colonial White"),
        ColorName(Color(0xFFEEEEE8), "Cararra"),
        ColorName(Color(0xFFEEEF78), "Manz"),
        ColorName(Color(0xFFEEF0C8), "Tahuna Sands"),
        ColorName(Color(0xFFEEF0F3), "Athens Gray"),
        ColorName(Color(0xFFEEF3C3), "Tusk"),
        ColorName(Color(0xFFEEF4DE), "Loafer"),
        ColorName(Color(0xFFEEF6F7), "Catskill White"),
        ColorName(Color(0xFFEEFDFF), "Twilight Blue"),
        ColorName(Color(0xFFEEFF9A), "Jonquil"),
        ColorName(Color(0xFFEEFFE2), "Rice Flower"),
        ColorName(Color(0xFFEF863F), "Jaffa"),
        ColorName(Color(0xFFEFEFEF), "Gallery"),
        ColorName(Color(0xFFEFF2F3), "Porcelain"),
        ColorName(Color(0xFFF091A9), "Mauvelous"),
        ColorName(Color(0xFFF0D52D), "Golden Dream"),
        ColorName(Color(0xFFF0DB7D), "Golden Sand"),
        ColorName(Color(0xFFF0DC82), "Buff"),
        ColorName(Color(0xFFF0E2EC), "Prim"),
        ColorName(Color(0xFFF0E68C), "Khaki"),
        ColorName(Color(0xFFF0EEFD), "Selago"),
        ColorName(Color(0xFFF0EEFF), "Titan White"),
        ColorName(Color(0xFFF0F8FF), "Alice Blue"),
        ColorName(Color(0xFFF0FCEA), "Feta"),
        ColorName(Color(0xFFF18200), "Gold Drop"),
        ColorName(Color(0xFFF19BAB), "Wewak"),
        ColorName(Color(0xFFF1E788), "Sahara Sand"),
        ColorName(Color(0xFFF1E9D2), "Parchment"),
        ColorName(Color(0xFFF1E9FF), "Blue Chalk"),
        ColorName(Color(0xFFF1EEC1), "Mint Julep"),
        ColorName(Color(0xFFF1F1F1), "Seashell"),
        ColorName(Color(0xFFF1F7F2), "Saltpan"),
        ColorName(Color(0xFFF1FFAD), "Tidal"),
        ColorName(Color(0xFFF1FFC8), "Chiffon"),
        ColorName(Color(0xFFF2552A), "Flamingo"),
        ColorName(Color(0xFFF28500), "Tangerine"),
        ColorName(Color(0xFFF2C3B2), "Mandy's Pink"),
        ColorName(Color(0xFFF2F2F2), "Concrete"),
        ColorName(Color(0xFFF2FAFA), "Black Squeeze"),
        ColorName(Color(0xFFF34723), "Pomegranate"),
        ColorName(Color(0xFFF3AD16), "Buttercup"),
        ColorName(Color(0xFFF3D69D), "New Orleans"),
        ColorName(Color(0xFFF3D9DF), "Vanilla Ice"),
        ColorName(Color(0xFFF3E7BB), "Sidecar"),
        ColorName(Color(0xFFF3E9E5), "Dawn Pink"),
        ColorName(Color(0xFFF3EDCF), "Wheatfield"),
        ColorName(Color(0xFFF3FB62), "Canary"),
        ColorName(Color(0xFFF3FBD4), "Orinoco"),
        ColorName(Color(0xFFF3FFD8), "Carla"),
        ColorName(Color(0xFFF400A1), "Hollywood Cerise"),
        ColorName(Color(0xFFF4A460), "Sandy brown"),
        ColorName(Color(0xFFF4C430), "Saffron"),
        ColorName(Color(0xFFF4D81C), "Ripe Lemon"),
        ColorName(Color(0xFFF4EBD3), "Janna"),
        ColorName(Color(0xFFF4F2EE), "Pampas"),
        ColorName(Color(0xFFF4F4F4), "Wild Sand"),
        ColorName(Color(0xFFF4F8FF), "Zircon"),
        ColorName(Color(0xFFF57584), "Froly"),
        ColorName(Color(0xFFF5C85C), "Cream Can"),
        ColorName(Color(0xFFF5C999), "Manhattan"),
        ColorName(Color(0xFFF5D5A0), "Maize"),
        ColorName(Color(0xFFF5DEB3), "Wheat"),
        ColorName(Color(0xFFF5E7A2), "Sandwisp"),
        ColorName(Color(0xFFF5E7E2), "Pot Pourri"),
        ColorName(Color(0xFFF5E9D3), "Albescent White"),
        ColorName(Color(0xFFF5EDEF), "Soft Peach"),
        ColorName(Color(0xFFF5F3E5), "Ecru White"),
        ColorName(Color(0xFFF5F5DC), "Beige"),
        ColorName(Color(0xFFF5FB3D), "Golden Fizz"),
        ColorName(Color(0xFFF5FFBE), "Australian Mint"),
        ColorName(Color(0xFFF64A8A), "French Rose"),
        ColorName(Color(0xFFF653A6), "Brilliant Rose"),
        ColorName(Color(0xFFF6A4C9), "Illusion"),
        ColorName(Color(0xFFF6F0E6), "Merino"),
        ColorName(Color(0xFFF6F7F7), "Black Haze"),
        ColorName(Color(0xFFF6FFDC), "Spring Sun"),
        ColorName(Color(0xFFF7468A), "Violet Red"),
        ColorName(Color(0xFFF77703), "Chilean Fire"),
        ColorName(Color(0xFFF77FBE), "Persian Pink"),
        ColorName(Color(0xFFF7B668), "Rajah"),
        ColorName(Color(0xFFF7C8DA), "Azalea"),
        ColorName(Color(0xFFF7DBE6), "We Peep"),
        ColorName(Color(0xFFF7F2E1), "Quarter Spanish White"),
        ColorName(Color(0xFFF7F5FA), "Whisper"),
        ColorName(Color(0xFFF7FAF7), "Snow Drift"),
        ColorName(Color(0xFFF8B853), "Casablanca"),
        ColorName(Color(0xFFF8C3DF), "Chantilly"),
        ColorName(Color(0xFFF8D9E9), "Cherub"),
        ColorName(Color(0xFFF8DB9D), "Marzipan"),
        ColorName(Color(0xFFF8DD5C), "Energy Yellow"),
        ColorName(Color(0xFFF8E4BF), "Givry"),
        ColorName(Color(0xFFF8F0E8), "White Linen"),
        ColorName(Color(0xFFF8F4FF), "Magnolia"),
        ColorName(Color(0xFFF8F6F1), "Spring Wood"),
        ColorName(Color(0xFFF8F7DC), "Coconut Cream"),
        ColorName(Color(0xFFF8F7FC), "White Lilac"),
        ColorName(Color(0xFFF8F8F7), "Desert Storm"),
        ColorName(Color(0xFFF8F99C), "Texas"),
        ColorName(Color(0xFFF8FACD), "Corn Field"),
        ColorName(Color(0xFFF8FDD3), "Mimosa"),
        ColorName(Color(0xFFF95A61), "Carnation"),
        ColorName(Color(0xFFF9BF58), "Saffron Mango"),
        ColorName(Color(0xFFF9E0ED), "Carousel Pink"),
        ColorName(Color(0xFFF9E4BC), "Dairy Cream"),
        ColorName(Color(0xFFF9E663), "Portica"),
        ColorName(Color(0xFFF9EAF3), "Amour"),
        ColorName(Color(0xFFF9F8E4), "Rum Swizzle"),
        ColorName(Color(0xFFF9FF8B), "Dolly"),
        ColorName(Color(0xFFF9FFF6), "Sugar Cane"),
        ColorName(Color(0xFFFA7814), "Ecstasy"),
        ColorName(Color(0xFFFA9D5A), "Tan Hide"),
        ColorName(Color(0xFFFAD3A2), "Corvette"),
        ColorName(Color(0xFFFADFAD), "Peach Yellow"),
        ColorName(Color(0xFFFAE600), "Turbo"),
        ColorName(Color(0xFFFAEAB9), "Astra"),
        ColorName(Color(0xFFFAECCC), "Champagne"),
        ColorName(Color(0xFFFAF0E6), "Linen"),
        ColorName(Color(0xFFFAF3F0), "Fantasy"),
        ColorName(Color(0xFFFAF7D6), "Citrine White"),
        ColorName(Color(0xFFFAFAFA), "Alabaster"),
        ColorName(Color(0xFFFAFDE4), "Hint of Yellow"),
        ColorName(Color(0xFFFAFFA4), "Milan"),
        ColorName(Color(0xFFFB607F), "Brink Pink"),
        ColorName(Color(0xFFFB8989), "Geraldine"),
        ColorName(Color(0xFFFBA0E3), "Lavender Rose"),
        ColorName(Color(0xFFFBA129), "Sea Buckthorn"),
        ColorName(Color(0xFFFBAC13), "Sun"),
        ColorName(Color(0xFFFBAED2), "Lavender Pink"),
        ColorName(Color(0xFFFBB2A3), "Rose Bud"),
        ColorName(Color(0xFFFBBEDA), "Cupid"),
        ColorName(Color(0xFFFBCCE7), "Classic Rose"),
        ColorName(Color(0xFFFBCEB1), "Apricot Peach"),
        ColorName(Color(0xFFFBE7B2), "Banana Mania"),
        ColorName(Color(0xFFFBE870), "Marigold Yellow"),
        ColorName(Color(0xFFFBE96C), "Festival"),
        ColorName(Color(0xFFFBEA8C), "Sweet Corn"),
        ColorName(Color(0xFFFBEC5D), "Candy Corn"),
        ColorName(Color(0xFFFBF9F9), "Hint of Red"),
        ColorName(Color(0xFFFBFFBA), "Shalimar"),
        ColorName(Color(0xFFFC0FC0), "Shocking Pink"),
        ColorName(Color(0xFFFC80A5), "Tickle Me Pink"),
        ColorName(Color(0xFFFC9C1D), "Tree Poppy"),
        ColorName(Color(0xFFFCC01E), "Lightning Yellow"),
        ColorName(Color(0xFFFCD667), "Goldenrod"),
        ColorName(Color(0xFFFCD917), "Candlelight"),
        ColorName(Color(0xFFFCDA98), "Cherokee"),
        ColorName(Color(0xFFFCF4D0), "Double Pearl Lusta"),
        ColorName(Color(0xFFFCF4DC), "Pearl Lusta"),
        ColorName(Color(0xFFFCF8F7), "Vista White"),
        ColorName(Color(0xFFFCFBF3), "Bianca"),
        ColorName(Color(0xFFFCFEDA), "Moon Glow"),
        ColorName(Color(0xFFFCFFE7), "China Ivory"),
        ColorName(Color(0xFFFCFFF9), "Ceramic"),
        ColorName(Color(0xFFFD0E35), "Torch Red"),
        ColorName(Color(0xFFFD5B78), "Wild Watermelon"),
        ColorName(Color(0xFFFD7B33), "Crusta"),
        ColorName(Color(0xFFFD7C07), "Sorbus"),
        ColorName(Color(0xFFFD9FA2), "Sweet Pink"),
        ColorName(Color(0xFFFDD5B1), "Light Apricot"),
        ColorName(Color(0xFFFDD7E4), "Pig Pink"),
        ColorName(Color(0xFFFDE1DC), "Cinderella"),
        ColorName(Color(0xFFFDE295), "Golden Glow"),
        ColorName(Color(0xFFFDE910), "Lemon"),
        ColorName(Color(0xFFFDF5E6), "Old Lace"),
        ColorName(Color(0xFFFDF6D3), "Half Colonial White"),
        ColorName(Color(0xFFFDF7AD), "Drover"),
        ColorName(Color(0xFFFDFEB8), "Pale Prim"),
        ColorName(Color(0xFFFDFFD5), "Cumulus"),
        ColorName(Color(0xFFFE28A2), "Persian Rose"),
        ColorName(Color(0xFFFE4C40), "Sunset Orange"),
        ColorName(Color(0xFFFE6F5E), "Bittersweet"),
        ColorName(Color(0xFFFE9D04), "California"),
        ColorName(Color(0xFFFEA904), "Yellow Sea"),
        ColorName(Color(0xFFFEBAAD), "Melon"),
        ColorName(Color(0xFFFED33C), "Bright Sun"),
        ColorName(Color(0xFFFED85D), "Dandelion"),
        ColorName(Color(0xFFFEDB8D), "Salomie"),
        ColorName(Color(0xFFFEE5AC), "Cape Honey"),
        ColorName(Color(0xFFFEEBF3), "Remy"),
        ColorName(Color(0xFFFEEFCE), "Oasis"),
        ColorName(Color(0xFFFEF0EC), "Bridesmaid"),
        ColorName(Color(0xFFFEF2C7), "Beeswax"),
        ColorName(Color(0xFFFEF3D8), "Bleach White"),
        ColorName(Color(0xFFFEF4CC), "Pipi"),
        ColorName(Color(0xFFFEF4DB), "Half Spanish White"),
        ColorName(Color(0xFFFEF4F8), "Wisp Pink"),
        ColorName(Color(0xFFFEF5F1), "Provincial Pink"),
        ColorName(Color(0xFFFEF7DE), "Half Dutch White"),
        ColorName(Color(0xFFFEF8E2), "Solitaire"),
        ColorName(Color(0xFFFEF8FF), "White Pointer"),
        ColorName(Color(0xFFFEF9E3), "Off Yellow"),
        ColorName(Color(0xFFFEFCED), "Orange White"),
        ColorName(Color(0xFFFF0000), "Red"),
        ColorName(Color(0xFFFF007F), "Rose"),
        ColorName(Color(0xFFFF00CC), "Purple Pizzazz"),
        ColorName(Color(0xFFFF00FF), "Magenta / Fuchsia"),
        ColorName(Color(0xFFFF2400), "Scarlet"),
        ColorName(Color(0xFFFF3399), "Wild Strawberry"),
        ColorName(Color(0xFFFF33CC), "Razzle Dazzle Rose"),
        ColorName(Color(0xFFFF355E), "Radical Red"),
        ColorName(Color(0xFFFF3F34), "Red Orange"),
        ColorName(Color(0xFFFF4040), "Coral Red"),
        ColorName(Color(0xFFFF4D00), "Vermilion"),
        ColorName(Color(0xFFFF4F00), "International Orange"),
        ColorName(Color(0xFFFF6037), "Outrageous Orange"),
        ColorName(Color(0xFFFF6600), "Blaze Orange"),
        ColorName(Color(0xFFFF66FF), "Pink Flamingo"),
        ColorName(Color(0xFFFF681F), "Orange"),
        ColorName(Color(0xFFFF69B4), "Hot Pink"),
        ColorName(Color(0xFFFF6B53), "Persimmon"),
        ColorName(Color(0xFFFF6FFF), "Blush Pink"),
        ColorName(Color(0xFFFF7034), "Burning Orange"),
        ColorName(Color(0xFFFF7518), "Pumpkin"),
        ColorName(Color(0xFFFF7D07), "Flamenco"),
        ColorName(Color(0xFFFF7F00), "Flush Orange"),
        ColorName(Color(0xFFFF7F50), "Coral"),
        ColorName(Color(0xFFFF8C69), "Salmon"),
        ColorName(Color(0xFFFF9000), "Pizazz"),
        ColorName(Color(0xFFFF910F), "West Side"),
        ColorName(Color(0xFFFF91A4), "Pink Salmon"),
        ColorName(Color(0xFFFF9933), "Neon Carrot"),
        ColorName(Color(0xFFFF9966), "Atomic Tangerine"),
        ColorName(Color(0xFFFF9980), "Vivid Tangerine"),
        ColorName(Color(0xFFFF9E2C), "Sunshade"),
        ColorName(Color(0xFFFFA000), "Orange Peel"),
        ColorName(Color(0xFFFFA194), "Mona Lisa"),
        ColorName(Color(0xFFFFA500), "Web Orange"),
        ColorName(Color(0xFFFFA6C9), "Carnation Pink"),
        ColorName(Color(0xFFFFAB81), "Hit Pink"),
        ColorName(Color(0xFFFFAE42), "Yellow Orange"),
        ColorName(Color(0xFFFFB0AC), "Cornflower Lilac"),
        ColorName(Color(0xFFFFB1B3), "Sundown"),
        ColorName(Color(0xFFFFB31F), "My Sin"),
        ColorName(Color(0xFFFFB555), "Texas Rose"),
        ColorName(Color(0xFFFFB7D5), "Cotton Candy"),
        ColorName(Color(0xFFFFB97B), "Macaroni and Cheese"),
        ColorName(Color(0xFFFFBA00), "Selective Yellow"),
        ColorName(Color(0xFFFFBD5F), "Koromiko"),
        ColorName(Color(0xFFFFBF00), "Amber"),
        ColorName(Color(0xFFFFC0A8), "Wax Flower"),
        ColorName(Color(0xFFFFC0CB), "Pink"),
        ColorName(Color(0xFFFFC3C0), "Your Pink"),
        ColorName(Color(0xFFFFC901), "Supernova"),
        ColorName(Color(0xFFFFCBA4), "Flesh"),
        ColorName(Color(0xFFFFCC33), "Sunglow"),
        ColorName(Color(0xFFFFCC5C), "Golden Tainoi"),
        ColorName(Color(0xFFFFCC99), "Peach Orange"),
        ColorName(Color(0xFFFFCD8C), "Chardonnay"),
        ColorName(Color(0xFFFFD1DC), "Pastel Pink"),
        ColorName(Color(0xFFFFD2B7), "Romantic"),
        ColorName(Color(0xFFFFD38C), "Grandis"),
        ColorName(Color(0xFFFFD700), "Gold"),
        ColorName(Color(0xFFFFD801), "School bus Yellow"),
        ColorName(Color(0xFFFFD8D9), "Cosmos"),
        ColorName(Color(0xFFFFDB58), "Mustard"),
        ColorName(Color(0xFFFFDCD6), "Peach Schnapps"),
        ColorName(Color(0xFFFFDDAF), "Caramel"),
        ColorName(Color(0xFFFFDDCD), "Tuft Bush"),
        ColorName(Color(0xFFFFDDCF), "Watusi"),
        ColorName(Color(0xFFFFDDF4), "Pink Lace"),
        ColorName(Color(0xFFFFDEAD), "Navajo White"),
        ColorName(Color(0xFFFFDEB3), "Frangipani"),
        ColorName(Color(0xFFFFE1DF), "Pippin"),
        ColorName(Color(0xFFFFE1F2), "Pale Rose"),
        ColorName(Color(0xFFFFE2C5), "Negroni"),
        ColorName(Color(0xFFFFE5A0), "Cream Brulee"),
        ColorName(Color(0xFFFFE5B4), "Peach"),
        ColorName(Color(0xFFFFE6C7), "Tequila"),
        ColorName(Color(0xFFFFE772), "Kournikova"),
        ColorName(Color(0xFFFFEAC8), "Sandy Beach"),
        ColorName(Color(0xFFFFEAD4), "Karry"),
        ColorName(Color(0xFFFFEC13), "Broom"),
        ColorName(Color(0xFFFFEDBC), "Colonial White"),
        ColorName(Color(0xFFFFEED8), "Derby"),
        ColorName(Color(0xFFFFEFA1), "Vis Vis"),
        ColorName(Color(0xFFFFEFC1), "Egg White"),
        ColorName(Color(0xFFFFEFD5), "Papaya Whip"),
        ColorName(Color(0xFFFFEFEC), "Fair Pink"),
        ColorName(Color(0xFFFFF0DB), "Peach Cream"),
        ColorName(Color(0xFFFFF0F5), "Lavender blush"),
        ColorName(Color(0xFFFFF14F), "Gorse"),
        ColorName(Color(0xFFFFF1B5), "Buttermilk"),
        ColorName(Color(0xFFFFF1D8), "Pink Lady"),
        ColorName(Color(0xFFFFF1EE), "Forget Me Not"),
        ColorName(Color(0xFFFFF1F9), "Tutu"),
        ColorName(Color(0xFFFFF39D), "Picasso"),
        ColorName(Color(0xFFFFF3F1), "Chardon"),
        ColorName(Color(0xFFFFF46E), "Paris Daisy"),
        ColorName(Color(0xFFFFF4CE), "Barley White"),
        ColorName(Color(0xFFFFF4DD), "Egg Sour"),
        ColorName(Color(0xFFFFF4E0), "Sazerac"),
        ColorName(Color(0xFFFFF4E8), "Serenade"),
        ColorName(Color(0xFFFFF4F3), "Chablis"),
        ColorName(Color(0xFFFFF5EE), "Seashell Peach"),
        ColorName(Color(0xFFFFF5F3), "Sauvignon"),
        ColorName(Color(0xFFFFF6D4), "Milk Punch"),
        ColorName(Color(0xFFFFF6DF), "Varden"),
        ColorName(Color(0xFFFFF6F5), "Rose White"),
        ColorName(Color(0xFFFFF8D1), "Baja White"),
        ColorName(Color(0xFFFFF9E2), "Gin Fizz"),
        ColorName(Color(0xFFFFF9E6), "Early Dawn"),
        ColorName(Color(0xFFFFFACD), "Lemon Chiffon"),
        ColorName(Color(0xFFFFFAF4), "Bridal Heath"),
        ColorName(Color(0xFFFFFBDC), "Scotch Mist"),
        ColorName(Color(0xFFFFFBF9), "Soapstone"),
        ColorName(Color(0xFFFFFC99), "Witch Haze"),
        ColorName(Color(0xFFFFFCEA), "Buttery White"),
        ColorName(Color(0xFFFFFCEE), "Island Spice"),
        ColorName(Color(0xFFFFFDD0), "Cream"),
        ColorName(Color(0xFFFFFDE6), "Chilean Heath"),
        ColorName(Color(0xFFFFFDE8), "Travertine"),
        ColorName(Color(0xFFFFFDF3), "Orchid White"),
        ColorName(Color(0xFFFFFDF4), "Quarter Pearl Lusta"),
        ColorName(Color(0xFFFFFEE1), "Half and Half"),
        ColorName(Color(0xFFFFFEEC), "Apricot White"),
        ColorName(Color(0xFFFFFEF0), "Rice Cake"),
        ColorName(Color(0xFFFFFEF6), "Black White"),
        ColorName(Color(0xFFFFFEFD), "Romance"),
        ColorName(Color(0xFFFFFF00), "Yellow"),
        ColorName(Color(0xFFFFFF66), "Laser Lemon"),
        ColorName(Color(0xFFFFFF99), "Pale Canary"),
        ColorName(Color(0xFFFFFFB4), "Portafino"),
        ColorName(Color(0xFFFFFFF0), "Ivory"),
        ColorName(Color(0xFFFFFFFF), "White")
    )
}
