package com.smarttoolfactory.colordetector.parser


val colorNameMap by lazy {
    mapOf(
        "#FF000000" to "Black",
        "#FF000080" to "Navy Blue",
        "#FF0000C8" to "Dark Blue",
        "#FF0000FF" to "Blue",
        "#FF000741" to "Stratos",
        "#FF001B1C" to "Swamp",
        "#FF002387" to "Resolution Blue",
        "#FF002900" to "Deep Fir",
        "#FF002E20" to "Burnham",
        "#FF002FA7" to "Klein Blue",
        "#FF003153" to "Prussian Blue",
        "#FF003366" to "Midnight Blue",
        "#FF003399" to "Smalt",
        "#FF003532" to "Deep Teal",
        "#FF003E40" to "Cyprus",
        "#FF004620" to "Kaitoke Green",
        "#FF0047AB" to "Cobalt",
        "#FF004816" to "Crusoe",
        "#FF004950" to "Sherpa Blue",
        "#FF0056A7" to "Endeavour",
        "#FF00581A" to "Camarone",
        "#FF0066CC" to "Science Blue",
        "#FF0066FF" to "Blue Ribbon",
        "#FF00755E" to "Tropical Rain Forest",
        "#FF0076A3" to "Allports",
        "#FF007BA7" to "Deep Cerulean",
        "#FF007EC7" to "Lochmara",
        "#FF007FFF" to "Azure Radiance",
        "#FF008080" to "Teal",
        "#FF0095B6" to "Bondi Blue",
        "#FF009DC4" to "Pacific Blue",
        "#FF00A693" to "Persian Green",
        "#FF00A86B" to "Jade",
        "#FF00CC99" to "Caribbean Green",
        "#FF00CCCC" to "Robin's Egg Blue",
        "#FF00FF00" to "Green",
        "#FF00FF7F" to "Spring Green",
        "#FF00FFFF" to "Cyan Aqua",
        "#FF010D1A" to "Blue Charcoal",
        "#FF011635" to "Midnight",
        "#FF011D13" to "Holly",
        "#FF012731" to "Daintree",
        "#FF01361C" to "Cardin Green",
        "#FF01371A" to "County Green",
        "#FF013E62" to "Astronaut Blue",
        "#FF013F6A" to "Regal Blue",
        "#FF014B43" to "Aqua Deep",
        "#FF015E85" to "Orient",
        "#FF016162" to "Blue Stone",
        "#FF016D39" to "Fun Green",
        "#FF01796F" to "Pine Green",
        "#FF017987" to "Blue Lagoon",
        "#FF01826B" to "Deep Sea",
        "#FF01A368" to "Green Haze",
        "#FF022D15" to "English Holly",
        "#FF02402C" to "Sherwood Green",
        "#FF02478E" to "Congress Blue",
        "#FF024E46" to "Evening Sea",
        "#FF026395" to "Bahama Blue",
        "#FF02866F" to "Observatory",
        "#FF02A4D3" to "Cerulean",
        "#FF03163C" to "Tangaroa",
        "#FF032B52" to "Green Vogue",
        "#FF036A6E" to "Mosque",
        "#FF041004" to "Midnight Moss",
        "#FF041322" to "Black Pearl",
        "#FF042E4C" to "Blue Whale",
        "#FF044022" to "Zuccini",
        "#FF044259" to "Teal Blue",
        "#FF051040" to "Deep Cove",
        "#FF051657" to "Gulf Blue",
        "#FF055989" to "Venice Blue",
        "#FF056F57" to "Watercourse",
        "#FF062A78" to "Catalina Blue",
        "#FF063537" to "Tiber",
        "#FF069B81" to "Gossamer",
        "#FF06A189" to "Niagara",
        "#FF073A50" to "Tarawera",
        "#FF080110" to "Jaguar",
        "#FF081910" to "Black Bean",
        "#FF082567" to "Deep Sapphire",
        "#FF088370" to "Elf Green",
        "#FF08E8DE" to "Bright Turquoise",
        "#FF092256" to "Downriver",
        "#FF09230F" to "Palm Green",
        "#FF09255D" to "Madison",
        "#FF093624" to "Bottle Green",
        "#FF095859" to "Deep Sea Green",
        "#FF097F4B" to "Salem",
        "#FF0A001C" to "Black Russian",
        "#FF0A480D" to "Dark Fern",
        "#FF0A6906" to "Japanese Laurel",
        "#FF0A6F75" to "Atoll",
        "#FF0B0B0B" to "Cod Gray",
        "#FF0B0F08" to "Marshland",
        "#FF0B1107" to "Gordons Green",
        "#FF0B1304" to "Black Forest",
        "#FF0B6207" to "San Felix",
        "#FF0BDA51" to "Malachite",
        "#FF0C0B1D" to "Ebony",
        "#FF0C0D0F" to "Woodsmoke",
        "#FF0C1911" to "Racing Green",
        "#FF0C7A79" to "Surfie Green",
        "#FF0C8990" to "Blue Chill",
        "#FF0D0332" to "Black Rock",
        "#FF0D1117" to "Bunker",
        "#FF0D1C19" to "Aztec",
        "#FF0D2E1C" to "Bush",
        "#FF0E0E18" to "Cinder",
        "#FF0E2A30" to "Firefly",
        "#FF0F2D9E" to "Torea Bay",
        "#FF10121D" to "Vulcan",
        "#FF101405" to "Green Waterloo",
        "#FF105852" to "Eden",
        "#FF110C6C" to "Arapawa",
        "#FF120A8F" to "Ultramarine",
        "#FF123447" to "Elephant",
        "#FF126B40" to "Jewel",
        "#FF130000" to "Diesel",
        "#FF130A06" to "Asphalt",
        "#FF13264D" to "Blue Zodiac",
        "#FF134F19" to "Parsley",
        "#FF140600" to "Nero",
        "#FF1450AA" to "Tory Blue",
        "#FF151F4C" to "Bunting",
        "#FF1560BD" to "Denim",
        "#FF15736B" to "Genoa",
        "#FF161928" to "Mirage",
        "#FF161D10" to "Hunter Green",
        "#FF162A40" to "Big Stone",
        "#FF163222" to "Celtic",
        "#FF16322C" to "Timber Green",
        "#FF163531" to "Gable Green",
        "#FF171F04" to "Pine Tree",
        "#FF175579" to "Chathams Blue",
        "#FF182D09" to "Deep Forest Green",
        "#FF18587A" to "Blumine",
        "#FF19330E" to "Palm Leaf",
        "#FF193751" to "Nile Blue",
        "#FF1959A8" to "Fun Blue",
        "#FF1A1A68" to "Lucky Point",
        "#FF1AB385" to "Mountain Meadow",
        "#FF1B0245" to "Tolopea",
        "#FF1B1035" to "Haiti",
        "#FF1B127B" to "Deep Koamaru",
        "#FF1B1404" to "Acadia",
        "#FF1B2F11" to "Seaweed",
        "#FF1B3162" to "Biscay",
        "#FF1B659D" to "Matisse",
        "#FF1C1208" to "Crowshead",
        "#FF1C1E13" to "Rangoon Green",
        "#FF1C39BB" to "Persian Blue",
        "#FF1C402E" to "Everglade",
        "#FF1C7C7D" to "Elm",
        "#FF1D6142" to "Green Pea",
        "#FF1E0F04" to "Creole",
        "#FF1E1609" to "Karaka",
        "#FF1E1708" to "El Paso",
        "#FF1E385B" to "Cello",
        "#FF1E433C" to "Te Papa Green",
        "#FF1E90FF" to "Dodger Blue",
        "#FF1E9AB0" to "Eastern Blue",
        "#FF1F120F" to "Night Rider",
        "#FF1FC2C2" to "Java",
        "#FF20208D" to "Jacksons Purple",
        "#FF202E54" to "Cloud Burst",
        "#FF204852" to "Blue Dianne",
        "#FF211A0E" to "Eternity",
        "#FF220878" to "Deep Blue",
        "#FF228B22" to "Forest Green",
        "#FF233418" to "Mallard",
        "#FF240A40" to "Violet",
        "#FF240C02" to "Kilimanjaro",
        "#FF242A1D" to "Log Cabin",
        "#FF242E16" to "Black Olive",
        "#FF24500F" to "Green House",
        "#FF251607" to "Graphite",
        "#FF251706" to "Cannon Black",
        "#FF251F4F" to "Port Gore",
        "#FF25272C" to "Shark",
        "#FF25311C" to "Green Kelp",
        "#FF2596D1" to "Curious Blue",
        "#FF260368" to "Paua",
        "#FF26056A" to "Paris M",
        "#FF261105" to "Wood Bark",
        "#FF261414" to "Gondola",
        "#FF262335" to "Steel Gray",
        "#FF26283B" to "Ebony Clay",
        "#FF273A81" to "Bay of Many",
        "#FF27504B" to "Plantation",
        "#FF278A5B" to "Eucalyptus",
        "#FF281E15" to "Oil",
        "#FF283A77" to "Astronaut",
        "#FF286ACD" to "Mariner",
        "#FF290C5E" to "Violent Violet",
        "#FF292130" to "Bastille",
        "#FF292319" to "Zeus",
        "#FF292937" to "Charade",
        "#FF297B9A" to "Jelly Bean",
        "#FF29AB87" to "Jungle Green",
        "#FF2A0359" to "Cherry Pie",
        "#FF2A140E" to "Coffee Bean",
        "#FF2A2630" to "Baltic Sea",
        "#FF2A380B" to "Turtle Green",
        "#FF2A52BE" to "Cerulean Blue",
        "#FF2B0202" to "Sepia Black",
        "#FF2B194F" to "Valhalla",
        "#FF2B3228" to "Heavy Metal",
        "#FF2C0E8C" to "Blue Gem",
        "#FF2C1632" to "Revolver",
        "#FF2C2133" to "Bleached Cedar",
        "#FF2C8C84" to "Lochinvar",
        "#FF2D2510" to "Mikado",
        "#FF2D383A" to "Outer Space",
        "#FF2D569B" to "St Tropez",
        "#FF2E0329" to "Jacaranda",
        "#FF2E1905" to "Jacko Bean",
        "#FF2E3222" to "Rangitoto",
        "#FF2E3F62" to "Rhino",
        "#FF2E8B57" to "Sea Green",
        "#FF2EBFD4" to "Scooter",
        "#FF2F270E" to "Onion",
        "#FF2F3CB3" to "Governor Bay",
        "#FF2F519E" to "Sapphire",
        "#FF2F5A57" to "Spectra",
        "#FF2F6168" to "Casal",
        "#FF300529" to "Melanzane",
        "#FF301F1E" to "Cocoa Brown",
        "#FF302A0F" to "Woodrush",
        "#FF304B6A" to "San Juan",
        "#FF30D5C8" to "Turquoise",
        "#FF311C17" to "Eclipse",
        "#FF314459" to "Pickled Bluewood",
        "#FF315BA1" to "Azure",
        "#FF31728D" to "Calypso",
        "#FF317D82" to "Paradiso",
        "#FF32127A" to "Persian Indigo",
        "#FF32293A" to "Blackcurrant",
        "#FF323232" to "Mine Shaft",
        "#FF325D52" to "Stromboli",
        "#FF327C14" to "Bilbao",
        "#FF327DA0" to "Astral",
        "#FF33036B" to "Christalle",
        "#FF33292F" to "Thunder",
        "#FF33CC99" to "Shamrock",
        "#FF341515" to "Tamarind",
        "#FF350036" to "Mardi Gras",
        "#FF350E42" to "Valentino",
        "#FF350E57" to "Jagger",
        "#FF353542" to "Tuna",
        "#FF354E8C" to "Chambray",
        "#FF363050" to "Martinique",
        "#FF363534" to "Tuatara",
        "#FF363C0D" to "Waiouru",
        "#FF36747D" to "Ming",
        "#FF368716" to "La Palma",
        "#FF370202" to "Chocolate",
        "#FF371D09" to "Clinker",
        "#FF37290E" to "Brown Tumbleweed",
        "#FF373021" to "Birch",
        "#FF377475" to "Oracle",
        "#FF380474" to "Blue Diamond",
        "#FF381A51" to "Grape",
        "#FF383533" to "Dune",
        "#FF384555" to "Oxford Blue",
        "#FF384910" to "Clover",
        "#FF394851" to "Limed Spruce",
        "#FF396413" to "Dell",
        "#FF3A0020" to "Toledo",
        "#FF3A2010" to "Sambuca",
        "#FF3A2A6A" to "Jacarta",
        "#FF3A686C" to "William",
        "#FF3A6A47" to "Killarney",
        "#FF3AB09E" to "Keppel",
        "#FF3B000B" to "Temptress",
        "#FF3B0910" to "Aubergine",
        "#FF3B1F1F" to "Jon",
        "#FF3B2820" to "Treehouse",
        "#FF3B7A57" to "Amazon",
        "#FF3B91B4" to "Boston Blue",
        "#FF3C0878" to "Windsor",
        "#FF3C1206" to "Rebel",
        "#FF3C1F76" to "Meteorite",
        "#FF3C2005" to "Dark Ebony",
        "#FF3C3910" to "Camouflage",
        "#FF3C4151" to "Bright Gray",
        "#FF3C4443" to "Cape Cod",
        "#FF3C493A" to "Lunar Green",
        "#FF3D0C02" to "Bean  ",
        "#FF3D2B1F" to "Bistre",
        "#FF3D7D52" to "Goblin",
        "#FF3E0480" to "Kingfisher Daisy",
        "#FF3E1C14" to "Cedar",
        "#FF3E2B23" to "English Walnut",
        "#FF3E2C1C" to "Black Marlin",
        "#FF3E3A44" to "Ship Gray",
        "#FF3EABBF" to "Pelorous",
        "#FF3F2109" to "Bronze",
        "#FF3F2500" to "Cola",
        "#FF3F3002" to "Madras",
        "#FF3F307F" to "Minsk",
        "#FF3F4C3A" to "Cabbage Pont",
        "#FF3F583B" to "Tom Thumb",
        "#FF3F5D53" to "Mineral Green",
        "#FF3FC1AA" to "Puerto Rico",
        "#FF3FFF00" to "Harlequin",
        "#FF401801" to "Brown Pod",
        "#FF40291D" to "Cork",
        "#FF403B38" to "Masala",
        "#FF403D19" to "Thatch Green",
        "#FF405169" to "Fjord",
        "#FF40826D" to "Viridian",
        "#FF40A860" to "Chateau Green",
        "#FF410056" to "Ripe Plum",
        "#FF411E10" to "Paco",
        "#FF412010" to "Deep Oak",
        "#FF413C37" to "Merlin",
        "#FF414257" to "Gun Powder",
        "#FF414C7D" to "East Bay",
        "#FF4169E1" to "Royal Blue",
        "#FF41AA78" to "Ocean Green",
        "#FF420303" to "Burnt Maroon",
        "#FF423921" to "Lisbon Brown",
        "#FF427977" to "Faded Jade",
        "#FF431560" to "Scarlet Gum",
        "#FF433120" to "Iroko",
        "#FF433E37" to "Armadillo",
        "#FF434C59" to "River Bed",
        "#FF436A0D" to "Green Leaf",
        "#FF44012D" to "Barossa",
        "#FF441D00" to "Morocco Brown",
        "#FF444954" to "Mako",
        "#FF454936" to "Kelp",
        "#FF456CAC" to "San Marino",
        "#FF45B1E8" to "Picton Blue",
        "#FF460B41" to "Loulou",
        "#FF462425" to "Crater Brown",
        "#FF465945" to "Gray Asparagus",
        "#FF4682B4" to "Steel Blue",
        "#FF480404" to "Rustic Red",
        "#FF480607" to "Bulgarian Rose",
        "#FF480656" to "Clairvoyant",
        "#FF481C1C" to "Cocoa Bean",
        "#FF483131" to "Woody Brown",
        "#FF483C32" to "Taupe",
        "#FF49170C" to "Van Cleef",
        "#FF492615" to "Brown Derby",
        "#FF49371B" to "Metallic Bronze",
        "#FF495400" to "Verdun Green",
        "#FF496679" to "Blue Bayoux",
        "#FF497183" to "Bismark",
        "#FF4A2A04" to "Bracken",
        "#FF4A3004" to "Deep Bronze",
        "#FF4A3C30" to "Mondo",
        "#FF4A4244" to "Tundora",
        "#FF4A444B" to "Gravel",
        "#FF4A4E5A" to "Trout",
        "#FF4B0082" to "Pigment Indigo",
        "#FF4B5D52" to "Nandor",
        "#FF4C3024" to "Saddle",
        "#FF4C4F56" to "Abbey",
        "#FF4D0135" to "Blackberry",
        "#FF4D0A18" to "Cab Sav",
        "#FF4D1E01" to "Indian Tan",
        "#FF4D282D" to "Cowboy",
        "#FF4D282E" to "Livid Brown",
        "#FF4D3833" to "Rock",
        "#FF4D3D14" to "Punga",
        "#FF4D400F" to "Bronzetone",
        "#FF4D5328" to "Woodland",
        "#FF4E0606" to "Mahogany",
        "#FF4E2A5A" to "Bossanova",
        "#FF4E3B41" to "Matterhorn",
        "#FF4E420C" to "Bronze Olive",
        "#FF4E4562" to "Mulled Wine",
        "#FF4E6649" to "Axolotl",
        "#FF4E7F9E" to "Wedgewood",
        "#FF4EABD1" to "Shakespeare",
        "#FF4F1C70" to "Honey Flower",
        "#FF4F2398" to "Daisy Bush",
        "#FF4F69C6" to "Indigo",
        "#FF4F7942" to "Fern Green",
        "#FF4F9D5D" to "Fruit Salad",
        "#FF4FA83D" to "Apple",
        "#FF504351" to "Mortar",
        "#FF507096" to "Kashmir Blue",
        "#FF507672" to "Cutty Sark",
        "#FF50C878" to "Emerald",
        "#FF514649" to "Emperor",
        "#FF516E3D" to "Chalet Green",
        "#FF517C66" to "Como",
        "#FF51808F" to "Smalt Blue",
        "#FF52001F" to "Castro",
        "#FF520C17" to "Maroon Oak",
        "#FF523C94" to "Gigas",
        "#FF533455" to "Voodoo",
        "#FF534491" to "Victoria",
        "#FF53824B" to "Hippie Green",
        "#FF541012" to "Heath",
        "#FF544333" to "Judge Gray",
        "#FF54534D" to "Fuscous Gray",
        "#FF549019" to "Vida Loca",
        "#FF55280C" to "Cioccolato",
        "#FF555B10" to "Saratoga",
        "#FF556D56" to "Finlandia",
        "#FF5590D9" to "Havelock Blue",
        "#FF56B4BE" to "Fountain Blue",
        "#FF578363" to "Spring Leaves",
        "#FF583401" to "Saddle Brown",
        "#FF585562" to "Scarpa Flow",
        "#FF587156" to "Cactus",
        "#FF589AAF" to "Hippie Blue",
        "#FF591D35" to "Wine Berry",
        "#FF592804" to "Brown Bramble",
        "#FF593737" to "Congo Brown",
        "#FF594433" to "Millbrook",
        "#FF5A6E9C" to "Waikawa Gray",
        "#FF5A87A0" to "Horizon",
        "#FF5B3013" to "Jambalaya",
        "#FF5C0120" to "Bordeaux",
        "#FF5C0536" to "Mulberry Wood",
        "#FF5C2E01" to "Carnaby Tan",
        "#FF5C5D75" to "Comet",
        "#FF5D1E0F" to "Redwood",
        "#FF5D4C51" to "Don Juan",
        "#FF5D5C58" to "Chicago",
        "#FF5D5E37" to "Verdigris",
        "#FF5D7747" to "Dingley",
        "#FF5DA19F" to "Breaker Bay",
        "#FF5E483E" to "Kabul",
        "#FF5E5D3B" to "Hemlock",
        "#FF5F3D26" to "Irish Coffee",
        "#FF5F5F6E" to "Mid Gray",
        "#FF5F6672" to "Shuttle Gray",
        "#FF5FA777" to "Aqua Forest",
        "#FF5FB3AC" to "Tradewind",
        "#FF604913" to "Horses Neck",
        "#FF605B73" to "Smoky",
        "#FF606E68" to "Corduroy",
        "#FF6093D1" to "Danube",
        "#FF612718" to "Espresso",
        "#FF614051" to "Eggplant",
        "#FF615D30" to "Costa Del Sol",
        "#FF61845F" to "Glade Green",
        "#FF622F30" to "Buccaneer",
        "#FF623F2D" to "Quincy",
        "#FF624E9A" to "Butterfly Bush",
        "#FF625119" to "West Coast",
        "#FF626649" to "Finch",
        "#FF639A8F" to "Patina",
        "#FF63B76C" to "Fern",
        "#FF6456B7" to "Blue Violet",
        "#FF646077" to "Dolphin",
        "#FF646463" to "Storm Dust",
        "#FF646A54" to "Siam",
        "#FF646E75" to "Nevada",
        "#FF6495ED" to "Cornflower Blue",
        "#FF64CCDB" to "Viking",
        "#FF65000B" to "Rosewood",
        "#FF651A14" to "Cherrywood",
        "#FF652DC1" to "Purple Heart",
        "#FF657220" to "Fern Frond",
        "#FF65745D" to "Willow Grove",
        "#FF65869F" to "Hoki",
        "#FF660045" to "Pompadour",
        "#FF660099" to "Purple",
        "#FF66023C" to "Tyrian Purple",
        "#FF661010" to "Dark Tan",
        "#FF66B58F" to "Silver Tree",
        "#FF66FF00" to "Bright Green",
        "#FF66FF66" to "Screamin Green",
        "#FF67032D" to "Black Rose",
        "#FF675FA6" to "Scampi",
        "#FF676662" to "Ironside Gray",
        "#FF678975" to "Viridian Green",
        "#FF67A712" to "Christi",
        "#FF683600" to "Nutmeg Wood Finish",
        "#FF685558" to "Zambezi",
        "#FF685E6E" to "Salt Box",
        "#FF692545" to "Tawny Port",
        "#FF692D54" to "Finn",
        "#FF695F62" to "Scorpion",
        "#FF697E9A" to "Lynch",
        "#FF6A442E" to "Spice",
        "#FF6A5D1B" to "Himalaya",
        "#FF6A6051" to "Soya Bean",
        "#FF6B2A14" to "Hairy Heath",
        "#FF6B3FA0" to "Royal Purple",
        "#FF6B4E31" to "Shingle Fawn",
        "#FF6B5755" to "Dorado",
        "#FF6B8BA2" to "Bermuda Gray",
        "#FF6B8E23" to "Olive Drab",
        "#FF6C3082" to "Eminence",
        "#FF6CDAE7" to "Turquoise Blue",
        "#FF6D0101" to "Lonestar",
        "#FF6D5E54" to "Pine Cone",
        "#FF6D6C6C" to "Dove Gray",
        "#FF6D9292" to "Juniper",
        "#FF6D92A1" to "Gothic",
        "#FF6E0902" to "Red Oxide",
        "#FF6E1D14" to "Moccaccino",
        "#FF6E4826" to "Pickled Bean",
        "#FF6E4B26" to "Dallas",
        "#FF6E6D57" to "Kokoda",
        "#FF6E7783" to "Pale Sky",
        "#FF6F440C" to "Cafe Royale",
        "#FF6F6A61" to "Flint",
        "#FF6F8E63" to "Highland",
        "#FF6F9D02" to "Limeade",
        "#FF6FD0C5" to "Downy",
        "#FF701C1C" to "Persian Plum",
        "#FF704214" to "Sepia",
        "#FF704A07" to "Antique Bronze",
        "#FF704F50" to "Ferra",
        "#FF706555" to "Coffee",
        "#FF708090" to "Slate Gray",
        "#FF711A00" to "Cedar Wood Finish",
        "#FF71291D" to "Metallic Copper",
        "#FF714693" to "Affair",
        "#FF714AB2" to "Studio",
        "#FF715D47" to "Tobacco Brown",
        "#FF716338" to "Yellow Metal",
        "#FF716B56" to "Peat",
        "#FF716E10" to "Olivetone",
        "#FF717486" to "Storm Gray",
        "#FF718080" to "Sirocco",
        "#FF71D9E2" to "Aquamarine Blue",
        "#FF72010F" to "Venetian Red",
        "#FF724A2F" to "Old Copper",
        "#FF726D4E" to "Go Ben",
        "#FF727B89" to "Raven",
        "#FF731E8F" to "Seance",
        "#FF734A12" to "Raw Umber",
        "#FF736C9F" to "Kimberly",
        "#FF736D58" to "Crocodile",
        "#FF737829" to "Crete",
        "#FF738678" to "Xanadu",
        "#FF74640D" to "Spicy Mustard",
        "#FF747D63" to "Limed Ash",
        "#FF747D83" to "Rolling Stone",
        "#FF748881" to "Blue Smoke",
        "#FF749378" to "Laurel",
        "#FF74C365" to "Mantis",
        "#FF755A57" to "Russett",
        "#FF7563A8" to "Deluge",
        "#FF76395D" to "Cosmic",
        "#FF7666C6" to "Blue Marguerite",
        "#FF76BD17" to "Lima",
        "#FF76D7EA" to "Sky Blue",
        "#FF770F05" to "Dark Burgundy",
        "#FF771F1F" to "Crown of Thorns",
        "#FF773F1A" to "Walnut",
        "#FF776F61" to "Pablo",
        "#FF778120" to "Pacifika",
        "#FF779E86" to "Oxley",
        "#FF77DD77" to "Pastel Green",
        "#FF780109" to "Japanese Maple",
        "#FF782D19" to "Mocha",
        "#FF782F16" to "Peanut",
        "#FF78866B" to "Camouflage Green",
        "#FF788A25" to "Wasabi",
        "#FF788BBA" to "Ship Cove",
        "#FF78A39C" to "Sea Nymph",
        "#FF795D4C" to "Roman Coffee",
        "#FF796878" to "Old Lavender",
        "#FF796989" to "Rum",
        "#FF796A78" to "Fedora",
        "#FF796D62" to "Sandstone",
        "#FF79DEEC" to "Spray",
        "#FF7A013A" to "Siren",
        "#FF7A58C1" to "Fuchsia Blue",
        "#FF7A7A7A" to "Boulder",
        "#FF7A89B8" to "Wild Blue Yonder",
        "#FF7AC488" to "De York",
        "#FF7B3801" to "Red Beech",
        "#FF7B3F00" to "Cinnamon",
        "#FF7B6608" to "Yukon Gold",
        "#FF7B7874" to "Tapa",
        "#FF7B7C94" to "Waterloo ",
        "#FF7B8265" to "Flax Smoke",
        "#FF7B9F80" to "Amulet",
        "#FF7BA05B" to "Asparagus",
        "#FF7C1C05" to "Kenyan Copper",
        "#FF7C7631" to "Pesto",
        "#FF7C778A" to "Topaz",
        "#FF7C7B7A" to "Concord",
        "#FF7C7B82" to "Jumbo",
        "#FF7C881A" to "Trendy Green",
        "#FF7CA1A6" to "Gumbo",
        "#FF7CB0A1" to "Acapulco",
        "#FF7CB7BB" to "Neptune",
        "#FF7D2C14" to "Pueblo",
        "#FF7DA98D" to "Bay Leaf",
        "#FF7DC8F7" to "Malibu",
        "#FF7DD8C6" to "Bermuda",
        "#FF7E3A15" to "Copper Canyon",
        "#FF7F1734" to "Claret",
        "#FF7F3A02" to "Peru Tan",
        "#FF7F626D" to "Falcon",
        "#FF7F7589" to "Mobster",
        "#FF7F76D3" to "Moody Blue",
        "#FF7FFF00" to "Chartreuse",
        "#FF7FFFD4" to "Aquamarine",
        "#FF800000" to "Maroon",
        "#FF800B47" to "Rose Bud Cherry",
        "#FF801818" to "Falu Red",
        "#FF80341F" to "Red Robin",
        "#FF803790" to "Vivid Violet",
        "#FF80461B" to "Russet",
        "#FF807E79" to "Friar Gray",
        "#FF808000" to "Olive",
        "#FF808080" to "Gray",
        "#FF80B3AE" to "Gulf Stream",
        "#FF80B3C4" to "Glacier",
        "#FF80CCEA" to "Seagull",
        "#FF81422C" to "Nutmeg",
        "#FF816E71" to "Spicy Pink",
        "#FF817377" to "Empress",
        "#FF819885" to "Spanish Green",
        "#FF826F65" to "Sand Dune",
        "#FF828685" to "Gunsmoke",
        "#FF828F72" to "Battleship Gray",
        "#FF831923" to "Merlot",
        "#FF837050" to "Shadow",
        "#FF83AA5D" to "Chelsea Cucumber",
        "#FF83D0C6" to "Monte Carlo",
        "#FF843179" to "Plum",
        "#FF84A0A0" to "Granny Smith",
        "#FF8581D9" to "Chetwode Blue",
        "#FF858470" to "Bandicoot",
        "#FF859FAF" to "Bali Hai",
        "#FF85C4CC" to "Half Baked",
        "#FF860111" to "Red Devil",
        "#FF863C3C" to "Lotus",
        "#FF86483C" to "Ironstone",
        "#FF864D1E" to "Bull Shot",
        "#FF86560A" to "Rusty Nail",
        "#FF868974" to "Bitter",
        "#FF86949F" to "Regent Gray",
        "#FF871550" to "Disco",
        "#FF87756E" to "Americano",
        "#FF877C7B" to "Hurricane",
        "#FF878D91" to "Oslo Gray",
        "#FF87AB39" to "Sushi",
        "#FF885342" to "Spicy Mix",
        "#FF886221" to "Kumera",
        "#FF888387" to "Suva Gray",
        "#FF888D65" to "Avocado",
        "#FF893456" to "Camelot",
        "#FF893843" to "Solid Pink",
        "#FF894367" to "Cannon Pink",
        "#FF897D6D" to "Makara",
        "#FF8A3324" to "Burnt Umber",
        "#FF8A73D6" to "True V",
        "#FF8A8360" to "Clay Creek",
        "#FF8A8389" to "Monsoon",
        "#FF8A8F8A" to "Stack",
        "#FF8AB9F1" to "Jordy Blue",
        "#FF8B00FF" to "Electric Violet",
        "#FF8B0723" to "Monarch",
        "#FF8B6B0B" to "Corn Harvest",
        "#FF8B8470" to "Olive Haze",
        "#FF8B847E" to "Schooner",
        "#FF8B8680" to "Natural Gray",
        "#FF8B9C90" to "Mantle",
        "#FF8B9FEE" to "Portage",
        "#FF8BA690" to "Envy",
        "#FF8BA9A5" to "Cascade",
        "#FF8BE6D8" to "Riptide",
        "#FF8C055E" to "Cardinal Pink",
        "#FF8C472F" to "Mule Fawn",
        "#FF8C5738" to "Potters Clay",
        "#FF8C6495" to "Trendy Pink",
        "#FF8D0226" to "Paprika",
        "#FF8D3D38" to "Sanguine Brown",
        "#FF8D3F3F" to "Tosca",
        "#FF8D7662" to "Cement",
        "#FF8D8974" to "Granite Green",
        "#FF8D90A1" to "Manatee",
        "#FF8DA8CC" to "Polo Blue",
        "#FF8E0000" to "Red Berry",
        "#FF8E4D1E" to "Rope",
        "#FF8E6F70" to "Opium",
        "#FF8E775E" to "Domino",
        "#FF8E8190" to "Mamba",
        "#FF8EABC1" to "Nepal",
        "#FF8F021C" to "Pohutukawa",
        "#FF8F3E33" to "El Salva",
        "#FF8F4B0E" to "Korma",
        "#FF8F8176" to "Squirrel",
        "#FF8FD6B4" to "Vista Blue",
        "#FF900020" to "Burgundy",
        "#FF901E1E" to "Old Brick",
        "#FF907874" to "Hemp",
        "#FF907B71" to "Almond Frost",
        "#FF908D39" to "Sycamore",
        "#FF92000A" to "Sangria",
        "#FF924321" to "Cumin",
        "#FF926F5B" to "Beaver",
        "#FF928573" to "Stonewall",
        "#FF928590" to "Venus",
        "#FF9370DB" to "Medium Purple",
        "#FF93CCEA" to "Cornflower",
        "#FF93DFB8" to "Algae Green",
        "#FF944747" to "Copper Rust",
        "#FF948771" to "Arrowtown",
        "#FF950015" to "Scarlett",
        "#FF956387" to "Strikemaster",
        "#FF959396" to "Mountain Mist",
        "#FF960018" to "Carmine",
        "#FF964B00" to "Brown",
        "#FF967059" to "Leather",
        "#FF9678B6" to "Purple Mountain",
        "#FF967BB6" to "Lavender Purple",
        "#FF96A8A1" to "Pewter",
        "#FF96BBAB" to "Summer Green",
        "#FF97605D" to "Au Chico",
        "#FF9771B5" to "Wisteria",
        "#FF97CD2D" to "Atlantis",
        "#FF983D61" to "Vin Rouge",
        "#FF9874D3" to "Lilac Bush",
        "#FF98777B" to "Bazaar",
        "#FF98811B" to "Hacienda",
        "#FF988D77" to "Pale Oyster",
        "#FF98FF98" to "Mint Green",
        "#FF990066" to "Fresh Eggplant",
        "#FF991199" to "Violet Eggplant",
        "#FF991613" to "Tamarillo",
        "#FF991B07" to "Totem Pole",
        "#FF996666" to "Copper Rose",
        "#FF9966CC" to "Amethyst",
        "#FF997A8D" to "Mountbatten Pink",
        "#FF9999CC" to "Blue Bell",
        "#FF9A3820" to "Prairie Sand",
        "#FF9A6E61" to "Toast",
        "#FF9A9577" to "Gurkha",
        "#FF9AB973" to "Olivine",
        "#FF9AC2B8" to "Shadow Green",
        "#FF9B4703" to "Oregon",
        "#FF9B9E8F" to "Lemon Grass",
        "#FF9C3336" to "Stiletto",
        "#FF9D5616" to "Hawaiian Tan",
        "#FF9DACB7" to "Gull Gray",
        "#FF9DC209" to "Pistachio",
        "#FF9DE093" to "Granny Smith Apple",
        "#FF9DE5FF" to "Anakiwa",
        "#FF9E5302" to "Chelsea Gem",
        "#FF9E5B40" to "Sepia Skin",
        "#FF9EA587" to "Sage",
        "#FF9EA91F" to "Citron",
        "#FF9EB1CD" to "Rock Blue",
        "#FF9EDEE0" to "Morning Glory",
        "#FF9F381D" to "Cognac",
        "#FF9F821C" to "Reef Gold",
        "#FF9F9F9C" to "Star Dust",
        "#FF9FA0B1" to "Santas Gray",
        "#FF9FD7D3" to "Sinbad",
        "#FF9FDD8C" to "Feijoa",
        "#FFA02712" to "Tabasco",
        "#FFA1750D" to "Buttered Rum",
        "#FFA1ADB5" to "Hit Gray",
        "#FFA1C50A" to "Citrus",
        "#FFA1DAD7" to "Aqua Island",
        "#FFA1E9DE" to "Water Leaf",
        "#FFA2006D" to "Flirt",
        "#FFA23B6C" to "Rouge",
        "#FFA26645" to "Cape Palliser",
        "#FFA2AAB3" to "Gray Chateau",
        "#FFA2AEAB" to "Edward",
        "#FFA3807B" to "Pharlap",
        "#FFA397B4" to "Amethyst Smoke",
        "#FFA3E3ED" to "Blizzard Blue",
        "#FFA4A49D" to "Delta",
        "#FFA4A6D3" to "Wistful",
        "#FFA4AF6E" to "Green Smoke",
        "#FFA50B5E" to "Jazzberry Jam",
        "#FFA59B91" to "Zorba",
        "#FFA5CB0C" to "Bahia",
        "#FFA62F20" to "Roof Terracotta",
        "#FFA65529" to "Paarl",
        "#FFA68B5B" to "Barley Corn",
        "#FFA69279" to "Donkey Brown",
        "#FFA6A29A" to "Dawn",
        "#FFA72525" to "Mexican Red",
        "#FFA7882C" to "Luxor Gold",
        "#FFA85307" to "Rich Gold",
        "#FFA86515" to "Reno Sand",
        "#FFA86B6B" to "Coral Tree",
        "#FFA8989B" to "Dusty Gray",
        "#FFA899E6" to "Dull Lavender",
        "#FFA8A589" to "Tallow",
        "#FFA8AE9C" to "Bud",
        "#FFA8AF8E" to "Locust",
        "#FFA8BD9F" to "Norway",
        "#FFA8E3BD" to "Chinook",
        "#FFA9A491" to "Gray Olive",
        "#FFA9ACB6" to "Aluminium",
        "#FFA9B2C3" to "Cadet Blue",
        "#FFA9B497" to "Schist",
        "#FFA9BDBF" to "Tower Gray",
        "#FFA9BEF2" to "Perano",
        "#FFA9C6C2" to "Opal",
        "#FFAA375A" to "Night Shadz",
        "#FFAA4203" to "Fire",
        "#FFAA8B5B" to "Muesli",
        "#FFAA8D6F" to "Sandal",
        "#FFAAA5A9" to "Shady Lady",
        "#FFAAA9CD" to "Logan",
        "#FFAAABB7" to "Spun Pearl",
        "#FFAAD6E6" to "Regent St Blue",
        "#FFAAF0D1" to "Magic Mint",
        "#FFAB0563" to "Lipstick",
        "#FFAB3472" to "Royal Heath",
        "#FFAB917A" to "Sandrift",
        "#FFABA0D9" to "Cold Purple",
        "#FFABA196" to "Bronco",
        "#FFAC8A56" to "Limed Oak",
        "#FFAC91CE" to "East Side",
        "#FFAC9E22" to "Lemon Ginger",
        "#FFACA494" to "Napa",
        "#FFACA586" to "Hillary",
        "#FFACA59F" to "Cloudy",
        "#FFACACAC" to "Silver Chalice",
        "#FFACB78E" to "Swamp Green",
        "#FFACCBB1" to "Spring Rain",
        "#FFACDD4D" to "Conifer",
        "#FFACE1AF" to "Celadon",
        "#FFAD781B" to "Mandalay",
        "#FFADBED1" to "Casper",
        "#FFADDFAD" to "Moss Green",
        "#FFADE6C4" to "Padua",
        "#FFADFF2F" to "Green Yellow",
        "#FFAE4560" to "Hippie Pink",
        "#FFAE6020" to "Desert",
        "#FFAE809E" to "Bouquet",
        "#FFAF4035" to "Medium Carmine",
        "#FFAF4D43" to "Apple Blossom",
        "#FFAF593E" to "Brown Rust",
        "#FFAF8751" to "Driftwood",
        "#FFAF8F2C" to "Alpine",
        "#FFAF9F1C" to "Lucky",
        "#FFAFA09E" to "Martini",
        "#FFAFB1B8" to "Bombay",
        "#FFAFBDD9" to "Pigeon Post",
        "#FFB04C6A" to "Cadillac",
        "#FFB05D54" to "Matrix",
        "#FFB05E81" to "Tapestry",
        "#FFB06608" to "Mai Tai",
        "#FFB09A95" to "Del Rio",
        "#FFB0E0E6" to "Powder Blue",
        "#FFB0E313" to "Inch Worm",
        "#FFB10000" to "Bright Red",
        "#FFB14A0B" to "Vesuvius",
        "#FFB1610B" to "Pumpkin Skin",
        "#FFB16D52" to "Santa Fe",
        "#FFB19461" to "Teak",
        "#FFB1E2C1" to "Fringy Flower",
        "#FFB1F4E7" to "Ice Cold",
        "#FFB20931" to "Shiraz",
        "#FFB2A1EA" to "Biloba Flower",
        "#FFB32D29" to "Tall Poppy",
        "#FFB35213" to "Fiery Orange",
        "#FFB38007" to "Hot Toddy",
        "#FFB3AF95" to "Taupe Gray",
        "#FFB3C110" to "La Rioja",
        "#FFB43332" to "Well Read",
        "#FFB44668" to "Blush",
        "#FFB4CFD3" to "Jungle Mist",
        "#FFB57281" to "Turkish Rose",
        "#FFB57EDC" to "Lavender",
        "#FFB5A27F" to "Mongoose",
        "#FFB5B35C" to "Olive Green",
        "#FFB5D2CE" to "Jet Stream",
        "#FFB5ECDF" to "Cruise",
        "#FFB6316C" to "Hibiscus",
        "#FFB69D98" to "Thatch",
        "#FFB6B095" to "Heathered Gray",
        "#FFB6BAA4" to "Eagle",
        "#FFB6D1EA" to "Spindle",
        "#FFB6D3BF" to "Gum Leaf",
        "#FFB7410E" to "Rust",
        "#FFB78E5C" to "Muddy Waters",
        "#FFB7A214" to "Sahara",
        "#FFB7A458" to "Husk",
        "#FFB7B1B1" to "Nobel",
        "#FFB7C3D0" to "Heather",
        "#FFB7F0BE" to "Madang",
        "#FFB81104" to "Milano Red",
        "#FFB87333" to "Copper",
        "#FFB8B56A" to "Gimblet",
        "#FFB8C1B1" to "Green Spring",
        "#FFB8C25D" to "Celery",
        "#FFB8E0F9" to "Sail",
        "#FFB94E48" to "Chestnut",
        "#FFB95140" to "Crail",
        "#FFB98D28" to "Marigold",
        "#FFB9C46A" to "Wild Willow",
        "#FFB9C8AC" to "Rainee",
        "#FFBA0101" to "Guardsman Red",
        "#FFBA450C" to "Rock Spray",
        "#FFBA6F1E" to "Bourbon",
        "#FFBA7F03" to "Pirate Gold",
        "#FFBAB1A2" to "Nomad",
        "#FFBAC7C9" to "Submarine",
        "#FFBAEEF9" to "Charlotte",
        "#FFBB3385" to "Medium Red Violet",
        "#FFBB8983" to "Brandy Rose",
        "#FFBBD009" to "Rio Grande",
        "#FFBBD7C1" to "Surf",
        "#FFBCC9C2" to "Powder Ash",
        "#FFBD5E2E" to "Tuscany",
        "#FFBD978E" to "Quicksand",
        "#FFBDB1A8" to "Silk",
        "#FFBDB2A1" to "Malta",
        "#FFBDB3C7" to "Chatelle",
        "#FFBDBBD7" to "Lavender Gray",
        "#FFBDBDC6" to "French Gray",
        "#FFBDC8B3" to "Clay Ash",
        "#FFBDC9CE" to "Loblolly",
        "#FFBDEDFD" to "French Pass",
        "#FFBEA6C3" to "London Hue",
        "#FFBEB5B7" to "Pink Swan",
        "#FFBEDE0D" to "Fuego",
        "#FFBF5500" to "Rose of Sharon",
        "#FFBFB8B0" to "Tide",
        "#FFBFBED8" to "Blue Haze",
        "#FFBFC1C2" to "Silver Sand",
        "#FFBFC921" to "Key Lime Pie",
        "#FFBFDBE2" to "Ziggurat",
        "#FFBFFF00" to "Lime",
        "#FFC02B18" to "Thunderbird",
        "#FFC04737" to "Mojo",
        "#FFC08081" to "Old Rose",
        "#FFC0C0C0" to "Silver",
        "#FFC0D3B9" to "Pale Leaf",
        "#FFC0D8B6" to "Pixie Green",
        "#FFC1440E" to "Tia Maria",
        "#FFC154C1" to "Fuchsia Pink",
        "#FFC1A004" to "Buddha Gold",
        "#FFC1B7A4" to "Bison Hide",
        "#FFC1BAB0" to "Tea",
        "#FFC1BECD" to "Gray Suit",
        "#FFC1D7B0" to "Sprout",
        "#FFC1F07C" to "Sulu",
        "#FFC26B03" to "Indochine",
        "#FFC2955D" to "Twine",
        "#FFC2BDB6" to "Cotton Seed",
        "#FFC2CAC4" to "Pumice",
        "#FFC2E8E5" to "Jagged Ice",
        "#FFC32148" to "Maroon Flush",
        "#FFC3B091" to "Indian Khaki",
        "#FFC3BFC1" to "Pale Slate",
        "#FFC3C3BD" to "Gray Nickel",
        "#FFC3CDE6" to "Periwinkle Gray",
        "#FFC3D1D1" to "Tiara",
        "#FFC3DDF9" to "Tropical Blue",
        "#FFC41E3A" to "Cardinal",
        "#FFC45655" to "Fuzzy Wuzzy Brown",
        "#FFC45719" to "Orange Roughy",
        "#FFC4C4BC" to "Mist Gray",
        "#FFC4D0B0" to "Coriander",
        "#FFC4F4EB" to "Mint Tulip",
        "#FFC54B8C" to "Mulberry",
        "#FFC59922" to "Nugget",
        "#FFC5994B" to "Tussock",
        "#FFC5DBCA" to "Sea Mist",
        "#FFC5E17A" to "Yellow Green",
        "#FFC62D42" to "Brick Red",
        "#FFC6726B" to "Contessa",
        "#FFC69191" to "Oriental Pink",
        "#FFC6A84B" to "Roti",
        "#FFC6C3B5" to "Ash",
        "#FFC6C8BD" to "Kangaroo",
        "#FFC6E610" to "Las Palmas",
        "#FFC7031E" to "Monza",
        "#FFC71585" to "Red Violet",
        "#FFC7BCA2" to "Coral Reef",
        "#FFC7C1FF" to "Melrose",
        "#FFC7C4BF" to "Cloud",
        "#FFC7C9D5" to "Ghost",
        "#FFC7CD90" to "Pine Glade",
        "#FFC7DDE5" to "Botticelli",
        "#FFC88A65" to "Antique Brass",
        "#FFC8A2C8" to "Lilac",
        "#FFC8A528" to "Hokey Pokey",
        "#FFC8AABF" to "Lily",
        "#FFC8B568" to "Laser",
        "#FFC8E3D7" to "Edgewater",
        "#FFC96323" to "Piper",
        "#FFC99415" to "Pizza",
        "#FFC9A0DC" to "Light Wisteria",
        "#FFC9B29B" to "Rodeo Dust",
        "#FFC9B35B" to "Sundance",
        "#FFC9B93B" to "Earls Green",
        "#FFC9C0BB" to "Silver Rust",
        "#FFC9D9D2" to "Conch",
        "#FFC9FFA2" to "Reef",
        "#FFC9FFE5" to "Aero Blue",
        "#FFCA3435" to "Flush Mahogany",
        "#FFCABB48" to "Turmeric",
        "#FFCADCD4" to "Paris White",
        "#FFCAE00D" to "Bitter Lemon",
        "#FFCAE6DA" to "Skeptic",
        "#FFCB8FA9" to "Viola",
        "#FFCBCAB6" to "Foggy Gray",
        "#FFCBD3B0" to "Green Mist",
        "#FFCBDBD6" to "Nebula",
        "#FFCC3333" to "Persian Red",
        "#FFCC5501" to "Burnt Orange",
        "#FFCC7722" to "Ochre",
        "#FFCC8899" to "Puce",
        "#FFCCCAA8" to "Thistle Green",
        "#FFCCCCFF" to "Periwinkle",
        "#FFCCFF00" to "Electric Lime",
        "#FFCD5700" to "Tenn",
        "#FFCD5C5C" to "Chestnut Rose",
        "#FFCD8429" to "Brandy Punch",
        "#FFCDF4FF" to "Onahau",
        "#FFCEB98F" to "Sorrell Brown",
        "#FFCEBABA" to "Cold Turkey",
        "#FFCEC291" to "Yuma",
        "#FFCEC7A7" to "Chino",
        "#FFCFA39D" to "Eunry",
        "#FFCFB53B" to "Old Gold",
        "#FFCFDCCF" to "Tasman",
        "#FFCFE5D2" to "Surf Crest",
        "#FFCFF9F3" to "Humming Bird",
        "#FFCFFAF4" to "Scandal",
        "#FFD05F04" to "Red Stage",
        "#FFD06DA1" to "Hopbush",
        "#FFD07D12" to "Meteor",
        "#FFD0BEF8" to "Perfume",
        "#FFD0C0E5" to "Prelude",
        "#FFD0F0C0" to "Tea Green",
        "#FFD18F1B" to "Geebung",
        "#FFD1BEA8" to "Vanilla",
        "#FFD1C6B4" to "Soft Amber",
        "#FFD1D2CA" to "Celeste",
        "#FFD1D2DD" to "Mischka",
        "#FFD1E231" to "Pear",
        "#FFD2691E" to "Hot Cinnamon",
        "#FFD27D46" to "Raw Sienna",
        "#FFD29EAA" to "Careys Pink",
        "#FFD2B48C" to "Tan",
        "#FFD2DA97" to "Deco",
        "#FFD2F6DE" to "Blue Romance",
        "#FFD2F8B0" to "Gossip",
        "#FFD3CBBA" to "Sisal",
        "#FFD3CDC5" to "Swirl",
        "#FFD47494" to "Charm",
        "#FFD4B6AF" to "Clam Shell",
        "#FFD4BF8D" to "Straw",
        "#FFD4C4A8" to "Akaroa",
        "#FFD4CD16" to "Bird Flower",
        "#FFD4D7D9" to "Iron",
        "#FFD4DFE2" to "Geyser",
        "#FFD4E2FC" to "Hawkes Blue",
        "#FFD54600" to "Grenadier",
        "#FFD591A4" to "Can Can",
        "#FFD59A6F" to "Whiskey",
        "#FFD5D195" to "Winter Hazel",
        "#FFD5F6E3" to "Granny Apple",
        "#FFD69188" to "My Pink",
        "#FFD6C562" to "Tacha",
        "#FFD6CEF6" to "Moon Raker",
        "#FFD6D6D1" to "Quill Gray",
        "#FFD6FFDB" to "Snowy Mint",
        "#FFD7837F" to "New York Pink",
        "#FFD7C498" to "Pavlova",
        "#FFD7D0FF" to "Fog",
        "#FFD84437" to "Valencia",
        "#FFD87C63" to "Japonica",
        "#FFD8BFD8" to "Thistle",
        "#FFD8C2D5" to "Maverick",
        "#FFD8FCFA" to "Foam",
        "#FFD94972" to "Cabaret",
        "#FFD99376" to "Burning Sand",
        "#FFD9B99B" to "Cameo",
        "#FFD9D6CF" to "Timberwolf",
        "#FFD9DCC1" to "Tana",
        "#FFD9E4F5" to "Link Water",
        "#FFD9F7FF" to "Mabel",
        "#FFDA3287" to "Cerise",
        "#FFDA5B38" to "Flame Pea",
        "#FFDA6304" to "Bamboo",
        "#FFDA6A41" to "Red Damask",
        "#FFDA70D6" to "Orchid",
        "#FFDA8A67" to "Copperfield",
        "#FFDAA520" to "Golden Grass",
        "#FFDAECD6" to "Zanah",
        "#FFDAF4F0" to "Iceberg",
        "#FFDAFAFF" to "Oyster Bay",
        "#FFDB5079" to "Cranberry",
        "#FFDB9690" to "Petite Orchid",
        "#FFDB995E" to "Di Serria",
        "#FFDBDBDB" to "Alto",
        "#FFDBFFF8" to "Frosted Mint",
        "#FFDC143C" to "Crimson",
        "#FFDC4333" to "Punch",
        "#FFDCB20C" to "Galliano",
        "#FFDCB4BC" to "Blossom",
        "#FFDCD747" to "Wattle",
        "#FFDCD9D2" to "Westar",
        "#FFDCDDCC" to "Moon Mist",
        "#FFDCEDB4" to "Caper",
        "#FFDCF0EA" to "Swans Down",
        "#FFDDD6D5" to "Swiss Coffee",
        "#FFDDF9F1" to "White Ice",
        "#FFDE3163" to "Cerise Red",
        "#FFDE6360" to "Roman",
        "#FFDEA681" to "Tumbleweed",
        "#FFDEBA13" to "Gold Tips",
        "#FFDEC196" to "Brandy",
        "#FFDECBC6" to "Wafer",
        "#FFDED4A4" to "Sapling",
        "#FFDED717" to "Barberry",
        "#FFDEE5C0" to "Beryl Green",
        "#FFDEF5FF" to "Pattens Blue",
        "#FFDF73FF" to "Heliotrope",
        "#FFDFBE6F" to "Apache",
        "#FFDFCD6F" to "Chenin",
        "#FFDFCFDB" to "Lola",
        "#FFDFECDA" to "Willow Brook",
        "#FFDFFF00" to "Chartreuse Yellow",
        "#FFE0B0FF" to "Mauve",
        "#FFE0B646" to "Anzac",
        "#FFE0B974" to "Harvest Gold",
        "#FFE0C095" to "Calico",
        "#FFE0FFFF" to "Baby Blue",
        "#FFE16865" to "Sunglo",
        "#FFE1BC64" to "Equator",
        "#FFE1C0C8" to "Pink Flare",
        "#FFE1E6D6" to "Periglacial Blue",
        "#FFE1EAD4" to "Kidnapper",
        "#FFE1F6E8" to "Tara",
        "#FFE25465" to "Mandy",
        "#FFE2725B" to "Terracotta",
        "#FFE28913" to "Golden Bell",
        "#FFE292C0" to "Shocking",
        "#FFE29418" to "Dixie",
        "#FFE29CD2" to "Light Orchid",
        "#FFE2D8ED" to "Snuff",
        "#FFE2EBED" to "Mystic",
        "#FFE2F3EC" to "Apple Green",
        "#FFE30B5C" to "Razzmatazz",
        "#FFE32636" to "Alizarin Crimson",
        "#FFE34234" to "Cinnabar",
        "#FFE3BEBE" to "Cavern Pink",
        "#FFE3F5E1" to "Peppermint",
        "#FFE3F988" to "Mindaro",
        "#FFE47698" to "Deep Blush",
        "#FFE49B0F" to "Gamboge",
        "#FFE4C2D5" to "Melanie",
        "#FFE4CFDE" to "Twilight",
        "#FFE4D1C0" to "Bone",
        "#FFE4D422" to "Sunflower",
        "#FFE4D5B7" to "Grain Brown",
        "#FFE4D69B" to "Zombie",
        "#FFE4F6E7" to "Frostee",
        "#FFE4FFD1" to "Snow Flurry",
        "#FFE52B50" to "Amaranth",
        "#FFE5841B" to "Zest",
        "#FFE5CCC9" to "Dust Storm",
        "#FFE5D7BD" to "Stark White",
        "#FFE5D8AF" to "Hampton",
        "#FFE5E0E1" to "Bon Jour",
        "#FFE5E5E5" to "Mercury",
        "#FFE5F9F6" to "Polar",
        "#FFE64E03" to "Trinidad",
        "#FFE6BE8A" to "Gold Sand",
        "#FFE6BEA5" to "Cashmere",
        "#FFE6D7B9" to "Double Spanish White",
        "#FFE6E4D4" to "Satin Linen",
        "#FFE6F2EA" to "Harp",
        "#FFE6F8F3" to "Off Green",
        "#FFE6FFE9" to "Hint of Green",
        "#FFE6FFFF" to "Tranquil",
        "#FFE77200" to "Mango Tango",
        "#FFE7730A" to "Christine",
        "#FFE79F8C" to "Tony's Pink",
        "#FFE79FC4" to "Kobi",
        "#FFE7BCB4" to "Rose Fog",
        "#FFE7BF05" to "Corn",
        "#FFE7CD8C" to "Putty",
        "#FFE7ECE6" to "Gray Nurse",
        "#FFE7F8FF" to "Lily White",
        "#FFE7FEFF" to "Bubbles",
        "#FFE89928" to "Fire Bush",
        "#FFE8B9B3" to "Shilo",
        "#FFE8E0D5" to "Pearl Bush",
        "#FFE8EBE0" to "Green White",
        "#FFE8F1D4" to "Chrome White",
        "#FFE8F2EB" to "Gin",
        "#FFE8F5F2" to "Aqua Squeeze",
        "#FFE96E00" to "Clementine",
        "#FFE97451" to "Burnt Sienna",
        "#FFE97C07" to "Tahiti Gold",
        "#FFE9CECD" to "Oyster Pink",
        "#FFE9D75A" to "Confetti",
        "#FFE9E3E3" to "Ebb",
        "#FFE9F8ED" to "Ottoman",
        "#FFE9FFFD" to "Clear Day",
        "#FFEA88A8" to "Carissma",
        "#FFEAAE69" to "Porsche",
        "#FFEAB33B" to "Tulip Tree",
        "#FFEAC674" to "Rob Roy",
        "#FFEADAB8" to "Raffia",
        "#FFEAE8D4" to "White Rock",
        "#FFEAF6EE" to "Panache",
        "#FFEAF6FF" to "Solitude",
        "#FFEAF9F5" to "Aqua Spring",
        "#FFEAFFFE" to "Dew",
        "#FFEB9373" to "Apricot",
        "#FFEBC2AF" to "Zinnwaldite",
        "#FFECA927" to "Fuel Yellow",
        "#FFECC54E" to "Ronchi",
        "#FFECC7EE" to "French Lilac",
        "#FFECCDB9" to "Just Right",
        "#FFECE090" to "Wild Rice",
        "#FFECEBBD" to "Fall Green",
        "#FFECEBCE" to "Aths Special",
        "#FFECF245" to "Starship",
        "#FFED0A3F" to "Red Ribbon",
        "#FFED7A1C" to "Tango",
        "#FFED9121" to "Carrot Orange",
        "#FFED989E" to "Sea Pink",
        "#FFEDB381" to "Tacao",
        "#FFEDC9AF" to "Desert Sand",
        "#FFEDCDAB" to "Pancho",
        "#FFEDDCB1" to "Chamois",
        "#FFEDEA99" to "Primrose",
        "#FFEDF5DD" to "Frost",
        "#FFEDF5F5" to "Aqua Haze",
        "#FFEDF6FF" to "Zumthor",
        "#FFEDF9F1" to "Narvik",
        "#FFEDFC84" to "Honeysuckle",
        "#FFEE82EE" to "Lavender Magenta",
        "#FFEEC1BE" to "Beauty Bush",
        "#FFEED794" to "Chalky",
        "#FFEED9C4" to "Almond",
        "#FFEEDC82" to "Flax",
        "#FFEEDEDA" to "Bizarre",
        "#FFEEE3AD" to "Double Colonial White",
        "#FFEEEEE8" to "Cararra",
        "#FFEEEF78" to "Manz",
        "#FFEEF0C8" to "Tahuna Sands",
        "#FFEEF0F3" to "Athens Gray",
        "#FFEEF3C3" to "Tusk",
        "#FFEEF4DE" to "Loafer",
        "#FFEEF6F7" to "Catskill White",
        "#FFEEFDFF" to "Twilight Blue",
        "#FFEEFF9A" to "Jonquil",
        "#FFEEFFE2" to "Rice Flower",
        "#FFEF863F" to "Jaffa",
        "#FFEFEFEF" to "Gallery",
        "#FFEFF2F3" to "Porcelain",
        "#FFF091A9" to "Mauvelous",
        "#FFF0D52D" to "Golden Dream",
        "#FFF0DB7D" to "Golden Sand",
        "#FFF0DC82" to "Buff",
        "#FFF0E2EC" to "Prim",
        "#FFF0E68C" to "Khaki",
        "#FFF0EEFD" to "Selago",
        "#FFF0EEFF" to "Titan White",
        "#FFF0F8FF" to "Alice Blue",
        "#FFF0FCEA" to "Feta",
        "#FFF18200" to "Gold Drop",
        "#FFF19BAB" to "Wewak",
        "#FFF1E788" to "Sahara Sand",
        "#FFF1E9D2" to "Parchment",
        "#FFF1E9FF" to "Blue Chalk",
        "#FFF1EEC1" to "Mint Julep",
        "#FFF1F1F1" to "Seashell",
        "#FFF1F7F2" to "Saltpan",
        "#FFF1FFAD" to "Tidal",
        "#FFF1FFC8" to "Chiffon",
        "#FFF2552A" to "Flamingo",
        "#FFF28500" to "Tangerine",
        "#FFF2C3B2" to "Mandy's Pink",
        "#FFF2F2F2" to "Concrete",
        "#FFF2FAFA" to "Black Squeeze",
        "#FFF34723" to "Pomegranate",
        "#FFF3AD16" to "Buttercup",
        "#FFF3D69D" to "New Orleans",
        "#FFF3D9DF" to "Vanilla Ice",
        "#FFF3E7BB" to "Sidecar",
        "#FFF3E9E5" to "Dawn Pink",
        "#FFF3EDCF" to "Wheatfield",
        "#FFF3FB62" to "Canary",
        "#FFF3FBD4" to "Orinoco",
        "#FFF3FFD8" to "Carla",
        "#FFF400A1" to "Hollywood Cerise",
        "#FFF4A460" to "Sandy brown",
        "#FFF4C430" to "Saffron",
        "#FFF4D81C" to "Ripe Lemon",
        "#FFF4EBD3" to "Janna",
        "#FFF4F2EE" to "Pampas",
        "#FFF4F4F4" to "Wild Sand",
        "#FFF4F8FF" to "Zircon",
        "#FFF57584" to "Froly",
        "#FFF5C85C" to "Cream Can",
        "#FFF5C999" to "Manhattan",
        "#FFF5D5A0" to "Maize",
        "#FFF5DEB3" to "Wheat",
        "#FFF5E7A2" to "Sandwisp",
        "#FFF5E7E2" to "Pot Pourri",
        "#FFF5E9D3" to "Albescent White",
        "#FFF5EDEF" to "Soft Peach",
        "#FFF5F3E5" to "Ecru White",
        "#FFF5F5DC" to "Beige",
        "#FFF5FB3D" to "Golden Fizz",
        "#FFF5FFBE" to "Australian Mint",
        "#FFF64A8A" to "French Rose",
        "#FFF653A6" to "Brilliant Rose",
        "#FFF6A4C9" to "Illusion",
        "#FFF6F0E6" to "Merino",
        "#FFF6F7F7" to "Black Haze",
        "#FFF6FFDC" to "Spring Sun",
        "#FFF7468A" to "Violet Red",
        "#FFF77703" to "Chilean Fire",
        "#FFF77FBE" to "Persian Pink",
        "#FFF7B668" to "Rajah",
        "#FFF7C8DA" to "Azalea",
        "#FFF7DBE6" to "We Peep",
        "#FFF7F2E1" to "Quarter Spanish White",
        "#FFF7F5FA" to "Whisper",
        "#FFF7FAF7" to "Snow Drift",
        "#FFF8B853" to "Casablanca",
        "#FFF8C3DF" to "Chantilly",
        "#FFF8D9E9" to "Cherub",
        "#FFF8DB9D" to "Marzipan",
        "#FFF8DD5C" to "Energy Yellow",
        "#FFF8E4BF" to "Givry",
        "#FFF8F0E8" to "White Linen",
        "#FFF8F4FF" to "Magnolia",
        "#FFF8F6F1" to "Spring Wood",
        "#FFF8F7DC" to "Coconut Cream",
        "#FFF8F7FC" to "White Lilac",
        "#FFF8F8F7" to "Desert Storm",
        "#FFF8F99C" to "Texas",
        "#FFF8FACD" to "Corn Field",
        "#FFF8FDD3" to "Mimosa",
        "#FFF95A61" to "Carnation",
        "#FFF9BF58" to "Saffron Mango",
        "#FFF9E0ED" to "Carousel Pink",
        "#FFF9E4BC" to "Dairy Cream",
        "#FFF9E663" to "Portica",
        "#FFF9EAF3" to "Amour",
        "#FFF9F8E4" to "Rum Swizzle",
        "#FFF9FF8B" to "Dolly",
        "#FFF9FFF6" to "Sugar Cane",
        "#FFFA7814" to "Ecstasy",
        "#FFFA9D5A" to "Tan Hide",
        "#FFFAD3A2" to "Corvette",
        "#FFFADFAD" to "Peach Yellow",
        "#FFFAE600" to "Turbo",
        "#FFFAEAB9" to "Astra",
        "#FFFAECCC" to "Champagne",
        "#FFFAF0E6" to "Linen",
        "#FFFAF3F0" to "Fantasy",
        "#FFFAF7D6" to "Citrine White",
        "#FFFAFAFA" to "Alabaster",
        "#FFFAFDE4" to "Hint of Yellow",
        "#FFFAFFA4" to "Milan",
        "#FFFB607F" to "Brink Pink",
        "#FFFB8989" to "Geraldine",
        "#FFFBA0E3" to "Lavender Rose",
        "#FFFBA129" to "Sea Buckthorn",
        "#FFFBAC13" to "Sun",
        "#FFFBAED2" to "Lavender Pink",
        "#FFFBB2A3" to "Rose Bud",
        "#FFFBBEDA" to "Cupid",
        "#FFFBCCE7" to "Classic Rose",
        "#FFFBCEB1" to "Apricot Peach",
        "#FFFBE7B2" to "Banana Mania",
        "#FFFBE870" to "Marigold Yellow",
        "#FFFBE96C" to "Festival",
        "#FFFBEA8C" to "Sweet Corn",
        "#FFFBEC5D" to "Candy Corn",
        "#FFFBF9F9" to "Hint of Red",
        "#FFFBFFBA" to "Shalimar",
        "#FFFC0FC0" to "Shocking Pink",
        "#FFFC80A5" to "Tickle Me Pink",
        "#FFFC9C1D" to "Tree Poppy",
        "#FFFCC01E" to "Lightning Yellow",
        "#FFFCD667" to "Goldenrod",
        "#FFFCD917" to "Candlelight",
        "#FFFCDA98" to "Cherokee",
        "#FFFCF4D0" to "Double Pearl Lusta",
        "#FFFCF4DC" to "Pearl Lusta",
        "#FFFCF8F7" to "Vista White",
        "#FFFCFBF3" to "Bianca",
        "#FFFCFEDA" to "Moon Glow",
        "#FFFCFFE7" to "China Ivory",
        "#FFFCFFF9" to "Ceramic",
        "#FFFD0E35" to "Torch Red",
        "#FFFD5B78" to "Wild Watermelon",
        "#FFFD7B33" to "Crusta",
        "#FFFD7C07" to "Sorbus",
        "#FFFD9FA2" to "Sweet Pink",
        "#FFFDD5B1" to "Light Apricot",
        "#FFFDD7E4" to "Pig Pink",
        "#FFFDE1DC" to "Cinderella",
        "#FFFDE295" to "Golden Glow",
        "#FFFDE910" to "Lemon",
        "#FFFDF5E6" to "Old Lace",
        "#FFFDF6D3" to "Half Colonial White",
        "#FFFDF7AD" to "Drover",
        "#FFFDFEB8" to "Pale Prim",
        "#FFFDFFD5" to "Cumulus",
        "#FFFE28A2" to "Persian Rose",
        "#FFFE4C40" to "Sunset Orange",
        "#FFFE6F5E" to "Bittersweet",
        "#FFFE9D04" to "California",
        "#FFFEA904" to "Yellow Sea",
        "#FFFEBAAD" to "Melon",
        "#FFFED33C" to "Bright Sun",
        "#FFFED85D" to "Dandelion",
        "#FFFEDB8D" to "Salomie",
        "#FFFEE5AC" to "Cape Honey",
        "#FFFEEBF3" to "Remy",
        "#FFFEEFCE" to "Oasis",
        "#FFFEF0EC" to "Bridesmaid",
        "#FFFEF2C7" to "Beeswax",
        "#FFFEF3D8" to "Bleach White",
        "#FFFEF4CC" to "Pipi",
        "#FFFEF4DB" to "Half Spanish White",
        "#FFFEF4F8" to "Wisp Pink",
        "#FFFEF5F1" to "Provincial Pink",
        "#FFFEF7DE" to "Half Dutch White",
        "#FFFEF8E2" to "Solitaire",
        "#FFFEF8FF" to "White Pointer",
        "#FFFEF9E3" to "Off Yellow",
        "#FFFEFCED" to "Orange White",
        "#FFFF0000" to "Red",
        "#FFFF007F" to "Rose",
        "#FFFF00CC" to "Purple Pizzazz",
        "#FFFF00FF" to "Magenta / Fuchsia",
        "#FFFF2400" to "Scarlet",
        "#FFFF3399" to "Wild Strawberry",
        "#FFFF33CC" to "Razzle Dazzle Rose",
        "#FFFF355E" to "Radical Red",
        "#FFFF3F34" to "Red Orange",
        "#FFFF4040" to "Coral Red",
        "#FFFF4D00" to "Vermilion",
        "#FFFF4F00" to "International Orange",
        "#FFFF6037" to "Outrageous Orange",
        "#FFFF6600" to "Blaze Orange",
        "#FFFF66FF" to "Pink Flamingo",
        "#FFFF681F" to "Orange",
        "#FFFF69B4" to "Hot Pink",
        "#FFFF6B53" to "Persimmon",
        "#FFFF6FFF" to "Blush Pink",
        "#FFFF7034" to "Burning Orange",
        "#FFFF7518" to "Pumpkin",
        "#FFFF7D07" to "Flamenco",
        "#FFFF7F00" to "Flush Orange",
        "#FFFF7F50" to "Coral",
        "#FFFF8C69" to "Salmon",
        "#FFFF9000" to "Pizazz",
        "#FFFF910F" to "West Side",
        "#FFFF91A4" to "Pink Salmon",
        "#FFFF9933" to "Neon Carrot",
        "#FFFF9966" to "Atomic Tangerine",
        "#FFFF9980" to "Vivid Tangerine",
        "#FFFF9E2C" to "Sunshade",
        "#FFFFA000" to "Orange Peel",
        "#FFFFA194" to "Mona Lisa",
        "#FFFFA500" to "Web Orange",
        "#FFFFA6C9" to "Carnation Pink",
        "#FFFFAB81" to "Hit Pink",
        "#FFFFAE42" to "Yellow Orange",
        "#FFFFB0AC" to "Cornflower Lilac",
        "#FFFFB1B3" to "Sundown",
        "#FFFFB31F" to "My Sin",
        "#FFFFB555" to "Texas Rose",
        "#FFFFB7D5" to "Cotton Candy",
        "#FFFFB97B" to "Macaroni and Cheese",
        "#FFFFBA00" to "Selective Yellow",
        "#FFFFBD5F" to "Koromiko",
        "#FFFFBF00" to "Amber",
        "#FFFFC0A8" to "Wax Flower",
        "#FFFFC0CB" to "Pink",
        "#FFFFC3C0" to "Your Pink",
        "#FFFFC901" to "Supernova",
        "#FFFFCBA4" to "Flesh",
        "#FFFFCC33" to "Sunglow",
        "#FFFFCC5C" to "Golden Tainoi",
        "#FFFFCC99" to "Peach Orange",
        "#FFFFCD8C" to "Chardonnay",
        "#FFFFD1DC" to "Pastel Pink",
        "#FFFFD2B7" to "Romantic",
        "#FFFFD38C" to "Grandis",
        "#FFFFD700" to "Gold",
        "#FFFFD801" to "School bus Yellow",
        "#FFFFD8D9" to "Cosmos",
        "#FFFFDB58" to "Mustard",
        "#FFFFDCD6" to "Peach Schnapps",
        "#FFFFDDAF" to "Caramel",
        "#FFFFDDCD" to "Tuft Bush",
        "#FFFFDDCF" to "Watusi",
        "#FFFFDDF4" to "Pink Lace",
        "#FFFFDEAD" to "Navajo White",
        "#FFFFDEB3" to "Frangipani",
        "#FFFFE1DF" to "Pippin",
        "#FFFFE1F2" to "Pale Rose",
        "#FFFFE2C5" to "Negroni",
        "#FFFFE5A0" to "Cream Brulee",
        "#FFFFE5B4" to "Peach",
        "#FFFFE6C7" to "Tequila",
        "#FFFFE772" to "Kournikova",
        "#FFFFEAC8" to "Sandy Beach",
        "#FFFFEAD4" to "Karry",
        "#FFFFEC13" to "Broom",
        "#FFFFEDBC" to "Colonial White",
        "#FFFFEED8" to "Derby",
        "#FFFFEFA1" to "Vis Vis",
        "#FFFFEFC1" to "Egg White",
        "#FFFFEFD5" to "Papaya Whip",
        "#FFFFEFEC" to "Fair Pink",
        "#FFFFF0DB" to "Peach Cream",
        "#FFFFF0F5" to "Lavender blush",
        "#FFFFF14F" to "Gorse",
        "#FFFFF1B5" to "Buttermilk",
        "#FFFFF1D8" to "Pink Lady",
        "#FFFFF1EE" to "Forget Me Not",
        "#FFFFF1F9" to "Tutu",
        "#FFFFF39D" to "Picasso",
        "#FFFFF3F1" to "Chardon",
        "#FFFFF46E" to "Paris Daisy",
        "#FFFFF4CE" to "Barley White",
        "#FFFFF4DD" to "Egg Sour",
        "#FFFFF4E0" to "Sazerac",
        "#FFFFF4E8" to "Serenade",
        "#FFFFF4F3" to "Chablis",
        "#FFFFF5EE" to "Seashell Peach",
        "#FFFFF5F3" to "Sauvignon",
        "#FFFFF6D4" to "Milk Punch",
        "#FFFFF6DF" to "Varden",
        "#FFFFF6F5" to "Rose White",
        "#FFFFF8D1" to "Baja White",
        "#FFFFF9E2" to "Gin Fizz",
        "#FFFFF9E6" to "Early Dawn",
        "#FFFFFACD" to "Lemon Chiffon",
        "#FFFFFAF4" to "Bridal Heath",
        "#FFFFFBDC" to "Scotch Mist",
        "#FFFFFBF9" to "Soapstone",
        "#FFFFFC99" to "Witch Haze",
        "#FFFFFCEA" to "Buttery White",
        "#FFFFFCEE" to "Island Spice",
        "#FFFFFDD0" to "Cream",
        "#FFFFFDE6" to "Chilean Heath",
        "#FFFFFDE8" to "Travertine",
        "#FFFFFDF3" to "Orchid White",
        "#FFFFFDF4" to "Quarter Pearl Lusta",
        "#FFFFFEE1" to "Half and Half",
        "#FFFFFEEC" to "Apricot White",
        "#FFFFFEF0" to "Rice Cake",
        "#FFFFFEF6" to "Black White",
        "#FFFFFEFD" to "Romance",
        "#FFFFFF00" to "Yellow",
        "#FFFFFF66" to "Laser Lemon",
        "#FFFFFF99" to "Pale Canary",
        "#FFFFFFB4" to "Portafino",
        "#FFFFFFF0" to "Ivory",
        "#FFFFFFFF" to "White"
    )
}
        