/*
 * ImageToolbox is an image editor for android
 * Copyright (c) 2026 T8RIN (Malik Mukhametzyanov)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * You should have received a copy of the Apache License
 * along with this program.  If not, see <http://www.apache.org/licenses/LICENSE-2.0>.
 */

package com.t8rin.imagetoolbox.feature.code_preview.presentation.model

class CodeLanguage private constructor(
    val title: String,
    val highlightKey: String,
    val fileExtension: String
) {
    companion object {
        val Kotlin = create("kotlin")

        val entries: List<CodeLanguage> = buildList {
            add(Kotlin)
            (PopularLanguageKeys.drop(1) + BundledLanguageKeys)
                .distinct()
                .filterNot { it == Kotlin.highlightKey }
                .mapTo(this, ::create)
        }

        private fun create(key: String) = CodeLanguage(
            title = DisplayNames[key] ?: key.toDisplayName(),
            highlightKey = key,
            fileExtension = FileExtensions[key] ?: key
        )
    }
}

private fun String.toDisplayName(): String = split('-').joinToString(" ") { part ->
    part.replaceFirstChar(Char::uppercase)
}

private val PopularLanguageKeys = listOf(
    "kotlin",
    "java",
    "javascript",
    "typescript",
    "python",
    "rust",
    "go",
    "swift",
    "dart",
    "c",
    "cpp",
    "csharp",
    "json",
    "xml",
    "css",
    "bash",
    "sql",
    "yaml",
    "markdown"
)

private val BundledLanguageKeys = listOf(
    "1c",
    "abnf",
    "accesslog",
    "actionscript",
    "ada",
    "angelscript",
    "apache",
    "applescript",
    "arcade",
    "arduino",
    "armasm",
    "xml",
    "asciidoc",
    "aspectj",
    "autohotkey",
    "autoit",
    "avrasm",
    "awk",
    "axapta",
    "bash",
    "basic",
    "bnf",
    "brainfuck",
    "c",
    "cal",
    "capnproto",
    "ceylon",
    "clean",
    "clojure",
    "clojure-repl",
    "cmake",
    "coffeescript",
    "coq",
    "cos",
    "cpp",
    "crmsh",
    "crystal",
    "csharp",
    "csp",
    "css",
    "d",
    "markdown",
    "dart",
    "delphi",
    "diff",
    "django",
    "dns",
    "dockerfile",
    "dos",
    "dsconfig",
    "dts",
    "dust",
    "ebnf",
    "elixir",
    "elm",
    "ruby",
    "erb",
    "erlang-repl",
    "erlang",
    "excel",
    "fix",
    "flix",
    "fortran",
    "fsharp",
    "gams",
    "gauss",
    "gcode",
    "gherkin",
    "glsl",
    "gml",
    "go",
    "golo",
    "gradle",
    "graphql",
    "groovy",
    "haml",
    "handlebars",
    "haskell",
    "haxe",
    "hsp",
    "http",
    "hy",
    "inform7",
    "ini",
    "irpf90",
    "isbl",
    "java",
    "javascript",
    "jboss-cli",
    "json",
    "julia",
    "julia-repl",
    "kotlin",
    "lasso",
    "latex",
    "ldif",
    "leaf",
    "less",
    "lisp",
    "livecodeserver",
    "livescript",
    "llvm",
    "lsl",
    "lua",
    "makefile",
    "mathematica",
    "matlab",
    "maxima",
    "mel",
    "mercury",
    "mipsasm",
    "mizar",
    "perl",
    "mojolicious",
    "monkey",
    "moonscript",
    "n1ql",
    "nestedtext",
    "nginx",
    "nim",
    "nix",
    "node-repl",
    "nsis",
    "objectivec",
    "ocaml",
    "openscad",
    "oxygene",
    "parser3",
    "pf",
    "pgsql",
    "php",
    "php-template",
    "plaintext",
    "pony",
    "powershell",
    "processing",
    "profile",
    "prolog",
    "properties",
    "protobuf",
    "puppet",
    "purebasic",
    "python",
    "python-repl",
    "q",
    "qml",
    "r",
    "reasonml",
    "rib",
    "roboconf",
    "routeros",
    "rsl",
    "ruleslanguage",
    "rust",
    "sas",
    "scala",
    "scheme",
    "scilab",
    "scss",
    "shell",
    "smali",
    "smalltalk",
    "sml",
    "sqf",
    "sql",
    "stan",
    "stata",
    "step21",
    "stylus",
    "subunit",
    "swift",
    "taggerscript",
    "yaml",
    "tap",
    "tcl",
    "thrift",
    "tp",
    "twig",
    "typescript",
    "vala",
    "vbnet",
    "vbscript",
    "vbscript-html",
    "verilog",
    "vhdl",
    "vim",
    "wasm",
    "wren",
    "x86asm",
    "xl",
    "xquery",
    "zephir"
)

private val DisplayNames = mapOf(
    "1c" to "1C",
    "abnf" to "ABNF",
    "accesslog" to "Access Log",
    "actionscript" to "ActionScript",
    "angelscript" to "AngelScript",
    "applescript" to "AppleScript",
    "armasm" to "ARM Assembly",
    "xml" to "HTML / XML",
    "asciidoc" to "AsciiDoc",
    "aspectj" to "AspectJ",
    "autohotkey" to "AutoHotkey",
    "autoit" to "AutoIt",
    "avrasm" to "AVR Assembly",
    "awk" to "AWK",
    "bnf" to "BNF",
    "capnproto" to "Cap’n Proto",
    "clojure-repl" to "Clojure REPL",
    "cmake" to "CMake",
    "coffeescript" to "CoffeeScript",
    "cpp" to "C++",
    "csharp" to "C#",
    "csp" to "CSP",
    "css" to "CSS",
    "d" to "D",
    "dns" to "DNS",
    "dos" to "DOS",
    "ebnf" to "EBNF",
    "erb" to "ERB",
    "erlang-repl" to "Erlang REPL",
    "fix" to "FIX",
    "fsharp" to "F#",
    "gams" to "GAMS",
    "gcode" to "G-code",
    "glsl" to "GLSL",
    "gml" to "GML",
    "graphql" to "GraphQL",
    "haml" to "HAML",
    "hsp" to "HSP",
    "http" to "HTTP",
    "ini" to "INI",
    "irpf90" to "IRPF90",
    "isbl" to "ISBL",
    "javascript" to "JavaScript",
    "jboss-cli" to "JBoss CLI",
    "json" to "JSON",
    "julia-repl" to "Julia REPL",
    "latex" to "LaTeX",
    "ldif" to "LDIF",
    "less" to "LESS",
    "livecodeserver" to "LiveCode Server",
    "livescript" to "LiveScript",
    "llvm" to "LLVM",
    "lsl" to "LSL",
    "matlab" to "MATLAB",
    "mel" to "MEL",
    "mipsasm" to "MIPS Assembly",
    "n1ql" to "N1QL",
    "node-repl" to "Node.js REPL",
    "nsis" to "NSIS",
    "objectivec" to "Objective-C",
    "openscad" to "OpenSCAD",
    "pgsql" to "PostgreSQL",
    "php" to "PHP",
    "php-template" to "PHP Template",
    "plaintext" to "Plain Text",
    "python-repl" to "Python REPL",
    "qml" to "QML",
    "reasonml" to "ReasonML",
    "r" to "R",
    "routeros" to "RouterOS",
    "sas" to "SAS",
    "scss" to "SCSS",
    "sml" to "SML",
    "sql" to "SQL",
    "step21" to "STEP Part 21",
    "taggerscript" to "TaggerScript",
    "typescript" to "TypeScript",
    "vbnet" to "VB.NET",
    "vbscript" to "VBScript",
    "vbscript-html" to "VBScript in HTML",
    "vhdl" to "VHDL",
    "wasm" to "WebAssembly",
    "x86asm" to "x86 Assembly",
    "yaml" to "YAML"
)

private val FileExtensions = mapOf(
    "1c" to "bsl",
    "accesslog" to "log",
    "actionscript" to "as",
    "angelscript" to "as",
    "apache" to "conf",
    "arduino" to "ino",
    "armasm" to "s",
    "xml" to "html",
    "asciidoc" to "adoc",
    "autohotkey" to "ahk",
    "autoit" to "au3",
    "avrasm" to "asm",
    "axapta" to "x++",
    "bash" to "sh",
    "basic" to "bas",
    "brainfuck" to "bf",
    "capnproto" to "capnp",
    "clean" to "dcl",
    "clojure" to "clj",
    "clojure-repl" to "clj",
    "coffeescript" to "coffee",
    "coq" to "v",
    "crystal" to "cr",
    "csharp" to "cs",
    "markdown" to "md",
    "delphi" to "pas",
    "django" to "html",
    "dns" to "zone",
    "dockerfile" to "Dockerfile",
    "dos" to "bat",
    "dsconfig" to "conf",
    "elixir" to "ex",
    "ruby" to "rb",
    "erlang" to "erl",
    "erlang-repl" to "erl",
    "fortran" to "f90",
    "fsharp" to "fs",
    "gams" to "gms",
    "gherkin" to "feature",
    "handlebars" to "hbs",
    "haskell" to "hs",
    "haxe" to "hx",
    "inform7" to "ni",
    "javascript" to "js",
    "julia" to "jl",
    "julia-repl" to "jl",
    "kotlin" to "kt",
    "latex" to "tex",
    "livecodeserver" to "lc",
    "livescript" to "ls",
    "llvm" to "ll",
    "makefile" to "Makefile",
    "mathematica" to "wl",
    "matlab" to "m",
    "maxima" to "mac",
    "mercury" to "m",
    "mipsasm" to "asm",
    "objectivec" to "m",
    "ocaml" to "ml",
    "openscad" to "scad",
    "parser3" to "p",
    "pf" to "conf",
    "pgsql" to "sql",
    "plaintext" to "txt",
    "powershell" to "ps1",
    "processing" to "pde",
    "prolog" to "pl",
    "protobuf" to "proto",
    "puppet" to "pp",
    "purebasic" to "pb",
    "python" to "py",
    "python-repl" to "py",
    "reasonml" to "re",
    "roboconf" to "graph",
    "routeros" to "rsc",
    "rust" to "rs",
    "scheme" to "scm",
    "scilab" to "sci",
    "shell" to "sh",
    "smalltalk" to "st",
    "stata" to "do",
    "step21" to "stp",
    "stylus" to "styl",
    "taggerscript" to "tagscript",
    "typescript" to "ts",
    "vbnet" to "vb",
    "vbscript" to "vbs",
    "vbscript-html" to "html",
    "verilog" to "v",
    "vhdl" to "vhd",
    "wasm" to "wat",
    "x86asm" to "asm",
    "xquery" to "xq",
    "zephir" to "zep"
)
